### ISSUE TITLE
Syndicating juju related blogs to jujucharms.com

### ISSUE THREAD

**Issue by tcallway** [canonical/jujucharms.com#103]
We'd like to start syndicating juju ecosystem blogs on jujucharms.com which pick up specific tags like #juju-blog or #juju-insights
First raised in LaunchPad - https://bugs.launchpad.net/resource-centre/+bug/1458791

**Comment by mitechie** [comment]
We pull blog entries from https://juju.ubuntu.com/feed/?tags=juju in production mangaged by the web team. Since you've contacted and are working with them and we'll auto pull it once that's updated closing this issue as there's nothing to do on the site itself.
