### ISSUE TITLE
~bigdata-charmers charms not showing up on jujucharms.com

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#104]
Yesterday, I pushed 8 charms and 3 bundles to ~bigdata-charmers:

https://code.launchpad.net/~bigdata-charmers

apache-hadoop-client
apache-hadoop-compute-slave
apache-hadoop-hdfs-master
apache-hadoop-hdfs-secondary
apache-hadoop-plugin
apache-hadoop-yarn-master
apache-hive
apache-pig

These are not showing up on jujucharms.com

https://jujucharms.com/q/bigdata-charmers/apache

Am I just being impatient waiting for a store refresh, or is there something special with the ~bigdata-charmers namespace that would prevent auto ingestion? At the moment, deployments are failing when trying to deploy charms thusly:

$ juju deploy cs:~bigdata-charmers/trusty/apache-hadoop-yarn-master
ERROR cannot resolve charm URL "cs:~bigdata-charmers/trusty/apache-hadoop-yarn-master": charm not found

**Comment by jcsackett** [comment]
There are currently some server issues with the charmstore being resolved by ops; as part of that ingestion is currently off. We'll keep an eye on it and update this when those issues are resolved, at which point those branches should auto-ingest.

**Comment by urosj** [comment]
The ingestion was run yesterday. New charms and bundles should be available now.

**Comment by kwmonroe** [comment]
Awesome!  All charms/bundles are where i expected them to be.  Thanks!
