### ISSUE TITLE
Logon problem

### ISSUE THREAD

**Issue by xolile** [canonical/jujucharms.com#106]
When I try to logon I get the following error - "Sorry for the inconvenience, please pop back soon"

**Comment by mitechie** [comment]
Sorry for the timing. We're in the middle of migrating the site over and you're probably caught in the middle. Leaving this issue open and will note/double check once the migration is done and DNS is updated that all is well.

**Comment by mitechie** [comment]
Login should be corrected. We've updated the release on the site and if you cannot login please let me know. It's working correctly in all tests currently.
