### ISSUE TITLE
promulgated lp:~bigdata-charmers charms aren't showing up in the store

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#107]
Hi friends, last Friday (6/12), we had the following charms/bundle promulgated:

https://bugs.launchpad.net/charms/+bug/1440161/comments/8

Yet when I search the store for any of those, I only see the `bigdata-dev` and `bigdata-charmers` charms.  I expected to see these owned by `charmers` after promulgation.  For example, there's no `apache-hadoop-yarn-master` with `charmers` as the author:

https://jujucharms.com/q/apache/hadoop/yarn/master

This is causing deployments to fail like so:

```
$ juju deploy apache-hadoop-yarn-master
ERROR cannot resolve charm URL "cs:apache-hadoop-yarn-master": charm not found
```

We can work around this by forcing a namespace, e.g.:

```
$ juju deploy cs:~bigdata-charmers/apache-hadoop-yarn-master
Added charm "cs:~bigdata-charmers/trusty/apache-hadoop-yarn-master-0" to the environment.
```

But we'd rather use the simpler syntax in our documentation.  Is there something we're missing to get charms promulgated from ~bigdata-charmers to show up as such in the store?

**Comment by mitechie** [comment]
The new system now has ingestion running and the charms are there. 

https://jujucharms.com/apache-hadoop-hdfs-master/trusty/2

for instance is the promulgated version without the username. 

Apologies for the ingestion issues we suffered and please let us know if anything else is not correct.
