### ISSUE TITLE
change google+ link in Juju website

### ISSUE THREAD

**Issue by ae5202** [canonical/jujucharms.com#108]
The Google+ link on https://jujucharms.com/community leads to a
  Google+ page which has been abandoned. We would like it to now link to
  this Google+ page:
  https://plus.google.com/106305712267007929608/posts.

  Thanks,
  Alexia

**Comment by mitechie** [comment]
Thanks, we'll get this updated in the next release.

**Comment by ae5202** [comment]
Great, thanks!
