### ISSUE TITLE
502 proxy server error on some pages

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#109]
Trying to access https://jujucharms.com/ and https://jujucharms.com/u/adam-stokes both are responding with a 502 proxy server error:

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

Apache/2.4.7 (Ubuntu) Server at jujucharms.com Port 443
```

Other pages such as:
https://jujucharms.com/community
https://demo.jujucharms.com/

Work as expected

**Comment by huwshimi** [comment]
Hi @battlemidget could you try something and logout (https://jujucharms.com/logout) and log back in again? We've just made a release and I've seen issues with migrating sessions before, I'd like to check if that resolves the error.

**Comment by huwshimi** [comment]
I just tried this myself, I logged in and was able to view the homepage but I got 502 proxy error on my profile, logging out and back in again resolved the issue on my profile page.

**Comment by adam-stokes** [comment]
@huwshimi wow that fixed it!

However, when I try to sign back in it seems to redirect me back to jujucharms.com after performing the auth but never renders the page. But if I stop that current request and reload jujucharms.com it shows up now with me logged in

p.s. cleared out my cache completely after logging out

**Comment by mitechie** [comment]
Has this settled and are you able to log in successfully now?

**Comment by adam-stokes** [comment]
I just tried again a few times signing out and back in and everything seems back to normal. I'll close this out.

Thanks!
