### ISSUE TITLE
Ingestion to CS takes too much time!

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#11]
juju-gui rev 16 publish time: Date: 2014-11-27 18:35:28 UTC

On the other hand: 
http get https://api.jujucharms.com/charmstore/v4/juju-gui-16/meta/archive-upload-time
returns
{ "UploadTime": "2014-11-28T03:45:22.265Z" }

That's 9h difference.  

With 4.0.2 we are adding ingestion start/finish times to debug status as well as to ingestion logs at /log. We will be able to see when ingestions start and how long they take.

**Comment by mitechie** [comment]
This isn't really user facing and something we can investigate internally. Closing here, I think there's better places to work on this.
