### ISSUE TITLE
readme markdown seems to have heading style reversed

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#110]
Markdown headings seem backwards.  `##` should be bigger than `###`, but it is not.  As an example, the word `Overview` on the following page is a `##` and the next line is a `###`, yet the rendered output shows `Overview` smaller:

https://jujucharms.com/u/bigdata-dev/apache-spark/21

The raw md:

https://api.jujucharms.com/charmstore/v4/~bigdata-dev/trusty/apache-spark-21/archive/README.md

**Comment by makyo** [comment]
Appears to be a styling issue - Overview is an `<h2>`, the next line is an `<h3>`.  Will investigate further.

**Comment by mitechie** [comment]
This is coming from the ubuntu style guide css we load. I'm going to assign this over to @anthonydillon to look into as he's the only one I know I can blame it on :)

**Comment by anthonydillon** [comment]
Looks like we are missing h3 - h6 styling. Will add the full heading styles to the readme widget.

**Comment by mitechie** [comment]
For some reason the H3 style is still smaller than the h4 style. E.g. compare
https://jujucharms.com/docs/stable/howto-juju-block#understanding-and-applying-restrictions
(an h3) with the heading immediately below it (h4)

**Comment by mitechie** [comment]
from @evilnick ^

**Comment by evilnick** [comment]
See the test page: https://jujucharms.com/docs/devel/test

h3 is still > h2

**Comment by frankban** [comment]
This seems fixed now.
