### ISSUE TITLE
Please add Marketo munchkin to Juju website 

### ISSUE THREAD

**Issue by ae5202** [canonical/jujucharms.com#111]
We would like to get the Marketo Munchin code added to the Juju website for better lead tracking. 

Thanks,
Alexia

**Comment by mitechie** [comment]
Thanks Alexia, is there documentation and references for this material? We're not familiar with this tool and how/what it's used for. A quick google shows it's something to coordinate with other tools. I'd like to see how this would work and make sure it's something that we are aware of as we put together the site and future updates.

**Comment by ae5202** [comment]
Hi Rick,

I'm adding Peter to the thread as he knows more about the process of adding
the munchin code. Peter can you please see @Rick's response to my request
to add the munchkin to the juju website and advise him?

Thanks,
Alexia

**Comment by pmahnke** [comment]
Rick

Munchkin is the tracking app for Marketo.

Marketo is the company's form processing, campaign management and user nurturing program.  Basically all marketing qualified leads for webforms and events go into it... and based on a user's activities across our sites, get scored and then contacted by sales when their actives merit a call.

We have this code on many pages on ubuntu.com and insights.u.c.

Here are some docs: http://developers.marketo.com/documentation/websites/lead-tracking-munchkin-js/

Here is the snippet: https://pastebin.canonical.com/134204/

Peter

**Comment by ae5202** [comment]
thanks Peter that's very helpful!

**Comment by ae5202** [comment]
Hi Rick,

do you need more info on this? If not, can you please let me know once it's
been implemented?

Thanks,
Alexia

**Comment by mitechie** [comment]
@ae5202 we're good. I've added the task to the todo list and will look at getting out in the next release to production.

**Comment by ae5202** [comment]
great thanks!

can you let me know when that is approx.?

**Comment by mitechie** [comment]
It's targeted at 0.1.30 which is scheduled for approx July 14th. https://github.com/CanonicalLtd/jujucharms.com/milestones

We've got a release going out the door today and this came in too late to make that release so it'll be in the next two week iteration.

**Comment by ae5202** [comment]
Sounds great thank you!

**Comment by mitechie** [comment]
This is now live.

**Comment by ae5202** [comment]
Thanks Rick, thats great news!
