### ISSUE TITLE
jujucharms.com/community/blog --> Proxy Error

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#112]
/community/blog seems to be having a Proxy Error atm. This bug is to address that failure.  

We would also like to ensure the blog feed is pulling on "juju" content that TomC is marking from insights.ubuntu.com as well as feeds the Eco team helps curates, such as feeds from http://blog.juju.solutions/

-thanks,
Antonio

**Comment by mitechie** [comment]
The new deployment is complete and it loading now for me. It corrects the timeout issue we were hitting getting the blog content.

We pull content from https://juju.ubuntu.com/feed/?tags=juju

We've talked with Tom about making sure anything he wants visible is added to that via working with the web team who control the feed. 

Closing, please reopen if you've additional questions or concerns.
