### ISSUE TITLE
MVP/Milestone 1 of Community Page Rework

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#113]
**Objective: reorganize page to feature contributors, and how to get involved.**

This is milestone 1 for the re-work of the community page. The structure below is how we would like to see the page organized as a user scrolls from top to bottom
## Tag line
- old:
  `The Juju community provides a strong support network that can help you get going with Juju, Charms and help solve your cloud deployment and scaling challenges. Join in, share your knowledge and help get the word out.`
- new:
  `Pioneers in service modeling. Deploy your solution, charm your software, or discuss your ideas. Contribute to the community and help push the line.`
- Link to Contributor page (/community/charmers).
## Horizontally splice our centers of gravity:
- [openstack][bigdata][containers][benchmarking] … or talk to us about starting your own “subcommunity”, there are hundreds of solutions available; want to be that champion? 
- Hero Highlight, 
  - start with a monthly update. 
  - User picture, small bio, solution, who they work for, WHY, what cloud?
  - Picture of the deployment in the GUI. 
  - One per center of gravity, underneath each one. Link to technical landing page on github. That page should have the list of new bugs and how to contribute. 
## Videos and Education
- Featured Videos
- Link to How to: https://jujucharms.com/docs/stable/howto
- Link to full video page.
## Blog posts
- Pull feed from insights.ubuntu.com TomC marks as Juju
- Pull feed from posts the Eco team highlights such as http://blog.juju.solutions/ or http://blog.jujugui.org/
- See https://github.com/CanonicalLtd/jujucharms.com/issues/112
- Link to full feed page
## Events
- Pull content from insight events for Juju
## Juju Partner Programmes
- Update Charm Partner Programme link to:  http://partners.ubuntu.com/programmes/charm
- Update OIL link to: http://partners.ubuntu.com/programmes/openstack
## Connect section:
- Move to footer, this is incidentals that every project has, but needs.
## Subpages:
- jujucharms.com/community/charmers
  - static list of contributors (rick, will the gravatar thing work here?) 
  - Thanks to our contributors
- jujucharms.com/blog
- jujuchars.com/videos
  - Featured videos
  - Link to all videos and resources

Additional Information @ https://docs.google.com/document/d/1EKsajcvH2G7uTCIBVpjRHgIdD8XfEXiBR8nqLF77p_4/edit#

**Comment by Lucapaulina** [comment]
A few changes from the eco team:
1. Remove 'charms' and 'commits' in the by line under the contributor.
2. Change all affiliations to 'Canonical Ltd'
3.  Add a link in the Openstack solutions section which says 'OpenStack community ›' and link it to https://wiki.ubuntu.com/ServerTeam/OpenStackCharms with an external link.

**Comment by anthonydillon** [comment]
@Lucapaulina thanks, where should I place the OpenStack community › link in that section. Adding it below the bundle vis will misalign the Contribute buttons. Also should I add a How to guides › link under the more Videos in the Videos section?

**Comment by Lucapaulina** [comment]
I knew I was missing one! Yes, please add the how to link.

Spencer said to add the link next to the 'Openstack base' link. Is that ok?

**Comment by anthonydillon** [comment]
@Lucapaulina thanks.

This ok?
![community juju](https://cloud.githubusercontent.com/assets/1413534/8695290/1e0fe8b0-2adc-11e5-9b2f-43f8075b30ff.png)
