### ISSUE TITLE
Search on docs site turns up a dead link

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#116]
While using the jujucharms.com docs site I performed a search for "peer", the second link appears to be invalid.  Here is the link that was in the search results:

https://jujucharms.com/docs/authors-charm-interfaces

The nearest page is:  https://jujucharms.com/docs/stable/authors-relations

I don't know how to update the index or fix this link in the search results.  Please advise or at least share with me how this is done so I can fix the next one.

Thank you!

**Comment by mitechie** [comment]
Thanks, we'll investigate and see if something is wrong with how we update elasticsearch when we pull down doc updates.

**Comment by mitechie** [comment]
Just to come back to this. We've found that there's issues with how search doesn't handle the multiple versions as it should. There's WIP to correct this and allow a true search across multiple versions.

**Comment by fabricematrat** [comment]
@mbruzek  I think this one is fixed since a long time.
