### ISSUE TITLE
jujucharms.com/about missing GCE as a provider

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#118]
This bug is to add Google Compute Engine[0], ie Google's Public Cloud, to the list of supported providers on the /about page.

Google is part of the Certified Public Cloud program[1]. As part of that program GCE is enabled as an official Juju provider. Now that Ubuntu images, Juju support, and docs[2] are available we should add their logo.

This is right under the "Deploy to bare metal and public or private clouds." Also should we add a link in this section that says "Get set up" and link to our getting started page (https://jujucharms.com/get-started)?

[0] https://cloud.google.com/compute/
[1] http://partners.ubuntu.com/programmes/public-cloud
[2] https://jujucharms.com/docs/stable/config-gce

-thanks,
Antonio

**Comment by mitechie** [comment]
Thanks Antonio. @Lucapaulina @anthonydillon can we get updated assets to update this one please?

**Comment by frankban** [comment]
@Lucapaulina please check if this is still an issue.

**Comment by Lucapaulina** [comment]
Not an issue.
