### ISSUE TITLE
Link to bundles containing the charm from charm page is empty

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#123]
On the [Kubernetes charm page](https://jujucharms.com/u/kubernetes/kubernetes-master/trusty/6#related) using Firefox 39.0 I see two empty boxes below the "Used in 2 solutions" header.

![kubernetes master-screenshot](https://cloud.githubusercontent.com/assets/246192/8872939/fb83ee18-3201-11e5-9b3f-caa08dd773b9.png)

**Comment by sparkiegeek** [comment]
Looking closer, I see 500 errors talking to the API.

The page is trying to issue a GET to https://api.jujucharms.com/charmstore/v4/meta/any?id=cs:~yellow/bundle/kubernetes-cluster-0&id=cs:~kubernetes/bundle/kubernetes-cluster-7&include=bundle-metadata&include=stats which fails with a complaint about missing macaroons

**Comment by rogpeppe** [comment]
I suspect this because you have visited staging.jujucharms.com previously and that that added a cookie for anything under jujucharms.com holding a macaroon valid only for the staging service.
You can work around this bug by clearing cookies for jujucharms.com

**Comment by urosj** [comment]
Ty, @sparkiegeek. This is partially due to the bug in charm store in the  /meta/bundles-containing endpoint. We'll fix this in the new CS release and then the results will be ok.

**Comment by frankban** [comment]
This seems to be no longer an issue.
