### ISSUE TITLE
https://jujucharms.com/community "Contribute" Links

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#124]
Openstack Contribute --> https://wiki.ubuntu.com/ServerTeam/OpenStackCharms
- Thus the "OpenStack community ›" can be dropped

Big Data solutions contribute --> https://github.com/juju-solutions/bigdata-community

Containers solutions contribute --> https://github.com/juju-solutions/tupperware

Benchmarking solutions contribute --> Keep as is for now, but will be at https://github.com/cloud-benchmarks/benchmark-docs

**Comment by Lucapaulina** [comment]
@arosales  For clarity is the big data contribute link this instead: http://bigdata.juju.solutions/ ?

**Comment by elvirafigueras** [comment]
Include two different links in each one of the three sections: one for the external link and one for topics page.
