### ISSUE TITLE
https://jujucharms.com/community/blog not indexing all blogs

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#125]
/community/blog doesn't seem to be ingesting all of our blogs. Could we confirm the ingest is consuming:
- Ubuntu Insights blogs tagged with Juju
- http://bruzer.net/
- http://blog.dasroot.net/
- http://www.jorgecastro.org/
- http://marcoceppi.com/

and a few others I need to confirm on, but I wanted to start this thread.

**Comment by arosales** [comment]
- http://blog.juju.solutions/
- http://blog.cloud-benchmarks.org/

**Comment by mitechie** [comment]
Blogs aggregated are managed by the web team and insights.canonical.com

**Comment by mitechie** [comment]
Adding @pmahnke

**Comment by anthonydillon** [comment]
I will work with IS to add permissions to the syndication list. Allowing more visibility of the list and maybe editor rights. Will keep you updated with my progress.

**Comment by pmahnke** [comment]
@anthonydillon is this currently served from the old juju.ubuntu.com site?  spoke with @arosales about moving this over to insights and training him to use the feedwordpress there... what do you think?

**Comment by anthonydillon** [comment]
Feedwordpress on Insight requires moderation of the posts coming in. Happy to pull a feed from insights if were happy to pull external posts into insights?

**Comment by pmahnke** [comment]
I spoke to Rick H about this as well... we are ok to move what's on the old
juju.ubuntu.com to insights, kill juju.ubuntu.com and teach Antonio how to
approve and add blogs... adding a tag, then you can pull that new tag feed
into jujucharms.org.

On 27 July 2015 at 15:54, Anthony Dillon notifications@github.com wrote:

> Feedwordpress on Insight requires moderation of the posts coming in. Happy
> to pull a feed from insights if were happy to pull external posts into
> insights?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CanonicalLtd/jujucharms.com/issues/125#issuecomment-125214403
> .

## 

Peter Mahnke
Head of Web development

Canonical
0796 108 4362
peter.mahnke@canonical.com

**Comment by mitechie** [comment]
Just to confirm, I was mistaken. We pull from insights with the video and events feeds. We do pull blogs from:

https://juju.ubuntu.com/feed/?tags=juju

So once this is updated we'll need to update our feed url and deploy to get things onto the new setup.

**Comment by arosales** [comment]
Just wanted to follow up here to see if any other action is needed to pull insight.ubuntu.com blogs tagged with "juju" into jujucharms.com/blog ?

ref = https://github.com/CanonicalLtd/jujucharms.com/issues/147

@castrojo is working to get all content onto insights.ubuntu.com and tagging with "juju."
