### ISSUE TITLE
Series in search result is only showing different font for percise

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#126]
For example searching for apache:
https://jujucharms.com/q/apache

Shows "Precise" as a different font than "Trusty" which at first glance leads me to believe that Trusty isn't enabled.

**Comment by Lucapaulina** [comment]
Ah, I think your saying that the text in orange looks like it's the "active" one when actually the black one is the "active" series, is this right?

**Comment by mitechie** [comment]
Basically, the orange looks 'highlighted' when it's really nothing we want folks to use.

**Comment by Lucapaulina** [comment]
yeah, we'll work on this.

**Comment by Lucapaulina** [comment]
We've handed designs over for this and implementation will follow shortly.
