### ISSUE TITLE
Wrong placement of data listing bundles on user profile pages

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#127]
Looking at results from https://jujucharms.com/u/lazypower

The placement is wrong in the bundle section.

**Comment by fabricematrat** [comment]
I would say the same for the charms under it.

**Comment by mitechie** [comment]
I'm not following what you're saying here. Can you be a bit more specific
on what is out of place?

**Comment by urosj** [comment]
Well, it might be planned to look like this, but it feels like data is all over the place. If this is planned placement on the results table feel free to close this.

<img width="1026" alt="misplacement of data" src="https://cloud.githubusercontent.com/assets/8036113/8931834/764d1018-3539-11e5-88a2-805c776ea227.png">

**Comment by mitechie** [comment]
adding @Lucapaulina and @spencerbygraves to provide feedback.

**Comment by huwshimi** [comment]
This looks like an issue with the widths of the columns. I have a fix coming.
