### ISSUE TITLE
jujucharms.com/docs/stable/reference-release-notes not formatting correctly in Firefox

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#128]
Viewing release notes such as https://jujucharms.com/docs/stable/reference-release-notes in a Firefox web browser has "odd" formatting. Specifically, the wrapping in code segments is not correct.  Interestingly, the formatting is correct in Chrome.

**Comment by anthonydillon** [comment]
This is due the a `details` element polyfill for Firefox as it does not support the accordion behaviour. I will work on a fix now.

**Comment by anthonydillon** [comment]
We have swapped out the code highlighting tool used before for Prism which does not have this issue. Therefore marking as fix committed and will be part of the next release.

**Comment by fabricematrat** [comment]
@arosales Fix released
