### ISSUE TITLE
jujucharms.com/solutions page is missing

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#129]
Seems like it got messed up during the last deployment, the page redirects to /store now.

**Comment by mitechie** [comment]
The solutions phrasing was deemed poor and it was renamed store. We've kept a redirect so old links should continue to work.

**Comment by mitechie** [comment]
The solutions phrasing was deemed poor and it was renamed store. We've kept a redirect so old links should continue to work.

**Comment by castrojo** [comment]
@mitechie This isn't about the URL, it's that the content itself is missing, the big buttons to click on either OpenStack, Big Data, etc. are now gone. People need to find a way to get to the individual solutions pages.

**Comment by mitechie** [comment]
Oh the topic pages?

**Comment by mitechie** [comment]
Luca says there's a design for this coming. Well coordinate with him and
get it fixed asap.

**Comment by castrojo** [comment]
Can we reopen this? This has been a regression for a long time.

**Comment by mitechie** [comment]
Isn't this fixed? https://jujucharms.com/store

**Comment by Lucapaulina** [comment]
I think there is some confusion over the URLs. /solutions was renamed
/store back in Nuremburg, I've got an hour with you guys tomorrow so let's
go through this issue then.
