### ISSUE TITLE
Add new contributor to community page

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#131]
Please replace Chuck Butler with Philip, also change the header from Containers to "Database Solutions" 

Philip Stoev is a QA and Release Manager with Galera Cluster,
responsible for the overall quality of the product. He has worked on
distributed systems and databases for more than a decade at Oracle,
MariaDB and NuoDB. His database testing framework, the RQG, is widely
used in the MySQL ecosystem and won the Application of the Year MySQL
Community Award in 2014.

![philip-stoev-small480](https://cloud.githubusercontent.com/assets/1264109/9115287/427b0aa2-3c2c-11e5-8947-56e8efa54156.jpg)

**Comment by castrojo** [comment]
Here is a link to the charm: https://jujucharms.com/galera-cluster/trusty/0

**Comment by Lucapaulina** [comment]
Thanks Jorge, Spencer is away this week and I would like him to mock it up before implementation. We'll schedule it in for next week.

**Comment by Lucapaulina** [comment]
@castrojo can you review Philips profile on https://jujucharms.com/community and tell us what changes are needed to make it right? Do we need the contribution link?

**Comment by castrojo** [comment]
This was already done, left over ticket, closing.
