### ISSUE TITLE
new bundle not showing up

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#133]
Hey folks, I pushed a new ~bigdata-dev bundle up yesterday, but am not seeing it in the store:

https://code.launchpad.net/~bigdata-dev/charms/bundles/realtime-syslog-analytics/trunk

This could be my fault as I can never remember if the branch name must be `bundle` or `trunk`.  Or perhaps I haven't waited long enough.  What's the lead time for new bundles to be ingested?

**Comment by jrwren** [comment]
Hey Kevin,

I wasn't sure if the branch name should be bundle or trunk either. You made me second guess myself.

I was able to figure it out by visiting http://www.jujucharms.com clicking store, clicking bundles clicking the first bundle and clicking view code, which brought me to a launchpad branch ending in bundle.

So yes, bundle instead of trunk. Push to /bundle and everything should be fine.

**Comment by bac** [comment]
Here is the documentation for bundles, which also gives the naming convention:

https://jujucharms.com/docs/1.24/charms-bundles

Let us know if you run into other issues.

**Comment by kwmonroe** [comment]
Those docs say to use `bundles.yaml`, but I thought new bundles should use the v4 `bundle.yaml`.

At any rate, I've moved by branch from `trunk` to `bundle` and will close this out when it shows up in the store. Thanks!

**Comment by kwmonroe** [comment]
Hmm, it's been about a day since I set the branch name to 'bundle', yet i'm still not seeing this in the store:

https://code.launchpad.net/~bigdata-dev/charms/bundles/realtime-syslog-analytics/bundle

Should I move the 'bundle.yaml' to 'bundles.yaml'?

FYI, I'm expecting to see `realtime syslog analytics` with this search:

https://jujucharms.com/q/realtime/syslog?type=bundle

**Comment by urosj** [comment]
I'll investigate logs what happens in ingestion. 

OTOH, at a first glance, the relations made by the bundle translator tool seem to require a bit different yaml form. For an example, you can take a look at https://api.jujucharms.com/charmstore/v4/bundle/rails-example-scalable-6/archive/bundle.yaml

**Comment by urosj** [comment]
Hi, @kwmonroe 

Attached you can find the error:

cannot post archive to cs:~bigdata-dev/bundle/realtime-syslog-analytics-2: bundle verification failed: ["cannot infer endpoint between flume-hdfs and plugin: charm \"cs:trusty/apache-flume-hdfs\" from service \"flume-hdfs\" not found","cannot infer endpoint between flume-syslog and flume-hdfs: charm \"cs:trusty/apache-flume-syslog\" from service \"flume-syslog\" not found","cannot infer endpoint between rsyslog-forwarder and flume-syslog: charm \"cs:trusty/apache-flume-syslog\" from service \"flume-syslog\" not found","service \"flume-hdfs\" refers to non-existent charm \"cs:trusty/apache-flume-hdfs\"","service \"flume-syslog\" refers to non-existent charm \"cs:trusty/apache-flume-syslog\""]

**Comment by urosj** [comment]
@kwmonroe Are those charms supposed to be promulgated? They are under ~bigdata-dev namespace, but not marked as promulgated in charm store. If you refer to them as cs:~bigdata-dev/trusty/\* instead of just cs:trusty/\* it should work.

**Comment by kwmonroe** [comment]
Yup Uros, that's it!  Sorry for the noise, this was my bad.  The Flume charms needed to be namespaced.
