### ISSUE TITLE
No documentation on status-set/status-get

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#134]
https://jujucharms.com/docs/search/?text=status-set&version=1.24

The only docs are the references for the status enumeration, but there is no guidance on how status-set works, what --service is for, when it should be used, etc.

**Comment by sparkiegeek** [comment]
Note that the 1.24.0 release notes have some coverage of the new commands

https://jujucharms.com/docs/1.24/reference-release-notes

Is it expected that the docs search doesn't find release-notes?

**Comment by kadams54** [comment]
The '-' character is a reserved character for searches, used to indicate negation (i.e., 'foo -bar' searches for all documents with 'foo' but not 'bar'). Consequently any search terms with '-' need to be in double quotes: "release-notes" and "status-set".

We have a card to talk about how we want to best handle reserved characters, as the current UX is not ideal.

**Comment by evilnick** [comment]
just an FYI, status-set (https://jujucharms.com/docs/stable/authors-hook-environment#status-set) and status-get (https://jujucharms.com/docs/stable/authors-hook-environment#status-get) have been in the main documentation since 1.24 was released (at the same time the table of values was added)
