### ISSUE TITLE
Distinguish between an error condition and 0 search results.

### ISSUE THREAD

**Issue by kadams54** [canonical/jujucharms.com#136]
Right now we display an error message ("Search results unavailable") any time 0 search results are returned. Consequently searching the docs for something like "bork" makes it look like doc search is down.

**Comment by Lucapaulina** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0sRuYvYz&#x2F;35-search-empty-state-charm-not-found-be-the-first-to-write-one"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Search empty state &quot;Charm not found, be the first to write one!&quot;</a>

**Comment by frankban** [comment]
This seems to be fixed now.
