### ISSUE TITLE
'Community Recommended' and 'Recommended' In Charm Results

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#137]
I know we have discussed this before, but what I recall and I think makes more sense is:

Community Recommended - These are charms that have passed policy review[0], and thus is _recommended_.

Community - These are the rest of the charms and have _not_ passed policy review[0], and thus do not carry a recommended status.

Currently we show "recommended" for everything when in fact only one class of charms are recommended as they have passed policy review[0]. 

This bug is to ask for "Recommended" for all non-charmer non-policy reviewed charms to be called "Community"

[0] https://jujucharms.com/docs/stable/authors-charm-policy

-thanks,
Antonio

**Comment by Lucapaulina** [comment]
+1 on this.

**Comment by kwmonroe** [comment]
+1 from me as well.. I'm confused by "recommended" in both headings, and I'm pretty smart.

**Comment by merlijn-sebrechts** [comment]
[This is a Charm that Canonical "recommends"](https://jujucharms.com/u/jamesbeedy/isc-dhcp/trusty/1). This Charm does nothing, it is the Python template charm with edited `metadata.yaml`.

This issue should be resolved asap. The whole ecosystem looks bad and very immature because of this confusing wording...

**Comment by urosj** [comment]
Just to confirm, @arosales  and @Lucapaulina:
- community recommended => recommended
- recommended => community

**Comment by Lucapaulina** [comment]
Sounds good to me.

**Comment by ivoks** [comment]
Recommended/Commuity implies that community is not involved in recommendations. Recommended also doesn't express all the executed effort. I'd vote for Approved/Incubating or something like that.

**Comment by merlijn-sebrechts** [comment]
Incubating implies that it is is currently in process of becoming
recommended. Although I can understand the preference for approved over
recommended. What about 'community approved'/'community'?

2016-01-14 12:47 GMT+01:00 ivoks notifications@github.com:

**Comment by arosales** [comment]
We could go with:

community recommended => community recommended [no change]
recommended => community

Ante does bring up a good point on the word "recommended."

Luca,
Any UX consideration for the appropriate word here, specifically for "recommended."

-thanks,
Antonio
