### ISSUE TITLE
Bundle search results when browsing users doesn't click through to the bundle

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#138]
I wanted to browse all the charmers made by a certain team

https://jujucharms.com/u/bigdata-charmers/

Clicking through the bundle results just expands the picture, it doesn't click through to the actual bundle. This bug seems to be unique to the user view, the normal search results for bundles appears to work as it should.

**Comment by Lucapaulina** [comment]
Hi Jorge,

That page you actually linked to is a profile page for a user, it's not the same as a search result as it exposes different information. We're due to do QA for this page and we'll get this issue fixed.

Luca

**Comment by castrojo** [comment]
Yep, I recognize that it's a user's page, but in this case I was interested in the bundles this "user" had created, because it's a team of folks. Was just expecting to be able to drill down to the bundle like the rest of the search results.

**Comment by Lucapaulina** [comment]
I'm going to close the issue as this is currently being fixed.
