### ISSUE TITLE
See if google can prefer /stable/ doc links instead of /devel/

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#144]
Searching for "juju constraints" or any kind of juju terminology on Google results in docs being found, yay! However they're the `devel` branch and not `stable`. 

Can we investigate making the stable branches the `canonical` link so that Google does the right thing?

**Comment by kadams54** [comment]
See https://en.wikipedia.org/wiki/Canonical_link_element for more info; we may need to add this across all versions and have it point on `stable`.

**Comment by mitechie** [comment]
Thanks @kadams54, seems like we should be able to automate that pretty easily.

**Comment by frankban** [comment]
Is this bug still relevant?
