### ISSUE TITLE
Add two new logos to the user's page

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#145]
Please add Deutsche Telekom and Verizon to the Juju user's page, thanks!

**Comment by Lucapaulina** [comment]
To the homepage?

**Comment by castrojo** [comment]
Yes, to the logos section.

**Comment by Lucapaulina** [comment]
Hi Jorge, we'll schedule this in and get it updated as soon as possible.

**Comment by anthonydillon** [comment]
This is live.
