### ISSUE TITLE
"Charm not found, be the first to write one!"

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#146]
Minor feature request. Go to jujucharms.com and search for something made up, like say jorgedb:

404: Sorry, we couldn’t find the page.
Try one of the following:
Your search for ‘jorgedb’ returned 30 results

It'd be neat if instead we did something like:
Sorry, we couldn’t find the page for 'jorgedb' in the charm store, you could be the first to submit one though [link to getting started docs], or check out our [charm partner program].

This would give people a place to go if they don't find what they are looking for in the store.

**Comment by Lucapaulina** [comment]
We did have something like this a whole ago and changed it, however I like this story. We'll schedule it in and work on another iteration.

**Comment by Lucapaulina** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0sRuYvYz&#x2F;35-search-empty-state-charm-not-found-be-the-first-to-write-one"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Search empty state &quot;Charm not found, be the first to write one!&quot;</a>

**Comment by castrojo** [comment]
@Lucapaulina This appears to have landed in the store. Ok to close?

**Comment by Lucapaulina** [comment]
Can you give me a link because I can't see that it's landed.

**Comment by castrojo** [comment]
https://jujucharms.com/q/? took me there, I don't recall how I got there. 

It's hard to find something with 0 results, even something silly like searching for `ninjas` doesn't take me to that page, so it appears to be there, just not connected?
