### ISSUE TITLE
Update community blog link and syndication

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#147]
https://jujucharms.com/community

Section "Latest from the Blog" is syndicating a blog we don't maintain anymore, can we have that suck in insights.u.c posts tagged with juju instead?

**Comment by arosales** [comment]
related: https://github.com/CanonicalLtd/jujucharms.com/issues/125

**Comment by Lucapaulina** [comment]
@castrojo In Seattle it was decided that you would make us an RSS feed to pull from and provide @anthonydillon with a new feed URL to use. Is this still the case?

**Comment by castrojo** [comment]
Yep, here it is: http://insights.ubuntu.com/tag/juju/feed

**Comment by anthonydillon** [comment]
Updated the feed URL and will be live in the next release.
