### ISSUE TITLE
authors-charm-writing does not note to install charm-tools package

### ISSUE THREAD

**Issue by raema** [canonical/jujucharms.com#148]
authors-charm-writing does not note that it is required to install charm-tools to use commands like 'juju charm create vanilla'

Should the doc have a step to install charm-tools? otherwise, the first command using 'juju charm create' will fail with 'unrecognized command' which doesn't make it quite clear that the charm-tools package is missing. 

$ juju charm create vanilla
ERROR unrecognized command: juju charm

**Comment by mitechie** [comment]
Thanks for the report @raema. I've replicated this issue on the juju docs and movement will happen there. https://github.com/juju/docs/issues/646
