### ISSUE TITLE
promulgated charms not showing up as 'community recommended' by charmers

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#149]
Hey folks, both apache-hive and apache-pig are promulgated:

https://jujucharms.com/apache-hive/
https://jujucharms.com/apache-pig/

When I search for them, they are not listed in the top "Community Recommended" box, eg:

https://jujucharms.com/q/apache/hive

I don't see any "apache hive" results owned by "charmers", even though the `lp:~bigdata-charmers/charms/trusty/apache-hive/trunk` branch does appear to be correctly linked to `lp:charms/trusty/apache-hive`:

https://code.launchpad.net/~bigdata-charmers/charms/trusty/apache-hive/trunk

**Comment by urosj** [comment]
Hi, 

Those charms are not marked as promulgated in the charm store. We're investigating what the issue is.

**Comment by arosales** [comment]
Well in general there is some confusion.

It should state:
promulgated charms = "Recommended"
everything else = "Community"

**Comment by arosales** [comment]
Ignore my previous comment that was meant for issue 137.

**Comment by urosj** [comment]
@arosales Seems this promulgation issue was introduced when we cleaned promulgation ingestion. We (or eco team) can promulgate charms with the charm2 command now.
