### ISSUE TITLE
link from charms-bundles page is broken

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#150]
The link to "search the store for bundles" in the 2nd paragraph here is broken:

https://jujucharms.com/docs/stable/charms-bundles

It's trying to go here, but I'm not sure what the correct URL would be:

https://jujucharms.com/sidebar/search/?text=bundle

**Comment by bac** [comment]
@kwmonroe Thanks for filing the bug.  It should actually be filed against the juju/docs project.  I'll open one over there.
