### ISSUE TITLE
Remove confusing personal charm for ubuntu-repository-cache

### ISSUE THREAD

**Issue by rcj4747** [canonical/jujucharms.com#151]
I've deleted lp:~rcj/charms/trusty/ubuntu-repository-cache/trunk and I'd like https://jujucharms.com/u/rcj/ubuntu-repository-cache/trusty to be removed to reduce confusion.  I would like one less charm distracting from the oficial charm of https://jujucharms.com/ubuntu-repository-cache/trusty

**Comment by frankban** [comment]
We need to put the ability to disable/remove a charm in place in the charm store. That's on the roadmap.
