### ISSUE TITLE
Sorting on https://jujucharms.com/store broken?

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#152]
Not sure how we're sorting this page but it doesn't seem to be downloads anymore?

**Comment by mitechie** [comment]
Thanks, something is definitely not right. I'm guessing that the series combining is messing with the numbers in the right order and we'll investigate.

**Comment by urosj** [comment]
@castrojo The mysql is an anomaly in the system, precise version has high DL numbers, while trusty not so much. The system favours latest LTS, so when we combine the DL stats for all series, it is ranked third. Unfortunately, we can't make all the rules and boostings be correct all the time, and this is the best that we can do with current requirements.
