### ISSUE TITLE
Get started page should document local provider gotchas

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#154]
Step 4 needs to be documented a bit wrt. to the local provider or perhaps consider versioning this page: https://jujucharms.com/get-started

I had a user who had an error because in older Juju's we needed sudo permissions, etc.

To reproduce follow the instructions on that page with Juju 1.18.

**Comment by mitechie** [comment]
Thanks @castrojo, I'm sorry the user hit this. However, 1.18 is not a supported version of Juju. It's not one that any user should be using to work on. Updates have been pushed to get 1.22.6 into trusty [1] and I feel like the real community issue here is how to get the users to update Juju vs adding documentation forks for unsupported versions. If you have any ideas/suggestions for how the user was using 1.18 and what can be done to update I'd love to help move that forward with the Juju teams.

1: https://launchpad.net/ubuntu/+source/juju-core
