### ISSUE TITLE
Charm store can't find "cassandra-stress" when using that term in a search

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#155]
Marco wrote a "cassandra-stress" charm in his personal namespace. 

When you search for "cassandra-stress" in the store, the charm doesn't come up, the only way to find it is to URL hack it as far as we can tell.

**Comment by mitechie** [comment]
Thanks for the report. Investigation notes that elasticsearch is splitting the search term into 
- cassandra
- -stress

Meaning "don't give me things with stress in them"

Searching with the term quoted works properly:

https://jujucharms.com/q/"cassandra-stress"

We'll investigate how to work around ES in this.

**Comment by urosj** [comment]
cassandra-stress is shown down in recommended charms as first hit, and api provides proper result. It's all about how we put promulgated higher than user namespaced ones.

https://api.jujucharms.com/charmstore/v4/search?text=cassandra-stress

So it's not really a bug, IMHO.

**Comment by mitechie** [comment]
Ah, I thought this was related to a previous issue but you're right that it's there. You're right @urosj apologies for missing that.

There are two other bugs on fixing the naming of the sections and fixing how search results appear. So closing this ack'ing that there are ways of improving that are in flight currently.

**Comment by castrojo** [comment]
> It's all about how we put promulgated higher than user namespaced ones.

Yeah unfortunately this isn't about priority sorting, it's about the result being missing entirely.

**Comment by mitechie** [comment]
@castrojo is it not this one at the top of "recommended" (e.g. community charms)? 

This is from https://jujucharms.com/q/cassandra-stress, just doing a search for cassandra-stress.

![selection_022](https://cloud.githubusercontent.com/assets/75915/9966980/f55dcfee-5e0d-11e5-82f4-eaa841e94e4c.png)

**Comment by castrojo** [comment]
Yep, when I went back and looked the result is there, it seems like there are just too many recommended ones that are entirely unrelated before we get to the the unrecommended ones that by the time I had gotten down that low I already gave up.
