### ISSUE TITLE
jujucharms.com/docs searching of release notes UX needs to be better

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#156]
If I search for a new Juju feature I heard of and it is only documented in the release notes :-/ search finds it, but when I click on the text it sends me to a very long juju release note list I have to manually expand and search the page on. this is cumbersome as I have to open up each Juju release and then "Find" on the web page.

For example, I am searching for leader election.
https://jujucharms.com/docs/search/?text=leader+election&version=1.24
I click on the first returned result:
https://jujucharms.com/docs/1.24/reference-release-notes
However, now I don't see any text relating leader election results until I expand each Juju release. For leader election I had to do this until I found 1.23.2.

**Comment by mitechie** [comment]
Migrated to work with the docs folks on this one: https://github.com/juju/docs/issues/690
