### ISSUE TITLE
juju dependency misspelt - `uvtool-libvivrt`

### ISSUE THREAD

**Issue by kunal15595** [canonical/jujucharms.com#157]
In documentaion for configuring juju for KVM at https://jujucharms.com/docs/devel/config-KVM, there's a typo.
`uvtool-libvivrt` --> `uvtool-libvirt`

**Comment by mitechie** [comment]
Copied to the docs repo for work and follow up please see:

https://github.com/juju/docs/issues/691

**Comment by mitechie** [comment]
And thanks for the report! Always great to have more eyes on things.
