### ISSUE TITLE
Missing plumgrid bundle

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#158]
I pushed the plumgrid bundle this morning - the bundle passes proof and lives in the proper location for recommended bundles. https://code.launchpad.net/~charmers/charms/bundles/plumgrid-ons/bundle

Yet it looks like it hasn't made it into the store. https://jujucharms.com/q/plumgrid?

**Comment by mitechie** [comment]
Welcome to our problem child. We don't load bundles or charms that don't exist in charmworld so the api data is consistent. However, you've got an awesome and amazing v4 format bundle which we would love to have...but charmworld doesn't know it to be a valid bundle. 

Sooooo, the best way forward is to fake charmworld out, and add a minimal bundles.yaml file that will validate, and leave the bundle.yaml file. 

In this way you get past our issue of two systems atm. I believe this is the current issue.

**Comment by lazypower** [comment]
I updated w/ the recommended bundle pattern and it appears to still not be ingesting, but i'm also now emitting errors when attempting to proof. I now believe this to be the reason its not pulling in w/ the associated bundle naming + file inclusions.. Will post back results once the bundle passes proof and time has passed for another ingest.

**Comment by lazypower** [comment]
@mitechie I think we have a winner - look at this beautiful sight https://jujucharms.com/plumgrid-ons/9

**Comment by mitechie** [comment]
Woooo! what did you end up having to tweak? Apologies if I led you astray there.

**Comment by lazypower** [comment]
It needed the v3 bundle format to ingest. You lead me on the right path, and once the proof errors went, the bundle was g2g. The relations appear to have been the culprit.
