### ISSUE TITLE
https://jujucharms.com/get-started "only available" should include references to vagrant and docker

### ISSUE THREAD

**Issue by andrewdmcleod** [canonical/jujucharms.com#159]
the following sentence on https://jujucharms.com/get-started: 

"juju quickstart is only available on Ubuntu and OSX"

may be technically accurate but is exclusive and reference should be made to Vagrant (https://jujucharms.com/docs/stable/config-vagrant) and docker images (https://github.com/juju-solutions/charmbox??) so that adoption/deployment isn't blocked by this sentence.

**Comment by evilnick** [comment]
There are lots of options. I think it would be best to just remove that line. If people are running Windows they will surely see the link to the 'proper' instructions there!

**Comment by Lucapaulina** [comment]
This has been addressed.
