### ISSUE TITLE
howto-authorised-keys page is missing

### ISSUE THREAD

**Issue by tyloch** [canonical/jujucharms.com#160]
this page
https://jujucharms.com/docs/howto-authorised-keys/

 is listed for master and other versions in search results:
https://jujucharms.com/docs/search/?text=authorized%20keys

but exists only for some e.g. 1.18:
https://jujucharms.com/docs/1.18/howto-authorised-keys

**Comment by bac** [comment]
@tyloch The docs are being displayed correctly.  That file existed in 1.18 but for some reason was removed from later versions of the documentation.  @evilnick can you provide the backstory?

**Comment by evilnick** [comment]
this is already discussed here :) https://github.com/juju/docs/issues/699

**Comment by bac** [comment]
Duplicate
