### ISSUE TITLE
Update jujucharms.com/big-data landing page

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#161]
We have some great Apache Hadoop Content we would like to highlight on the landing page.

We have documented our thoughts in the Google doc:
https://docs.google.com/document/d/1Y1yB7lhR2OHuO8ZAqJBdM3bl9dafeH9wT9BU6-Hfjig/edit#

Also an interesting presentation to walkthough these updates is at:
https://docs.google.com/presentation/d/18NYrTKceFWp0Syw8PqNhb0LxQTnhWiORroEVKksNbj8/edit#slide=id.gbc5e00fe5_3_115

Let us know if any other input is needed to help update this page.

-thanks,
Antonio

**Comment by Lucapaulina** [comment]
Hi Antonio,

Let's find some time to talk this through while we are in Seattle.

Luca

**Comment by arosales** [comment]
@Lucapaulina 

Hello, I just wanted to touch base with you on the status of this.

**Comment by johnsca** [comment]
The Google Docs link above should still capture the desired changes.

**Comment by anthonydillon** [comment]
I am currently working on the new design. Should be ready shortly.

**Comment by arosales** [comment]
@anthonydillon thanks for the work on this. The good news is we are having folks hit the jujucharms.com/big-data landing page. The bad news is they are deploying they old bundles, and not our shiny new bits.

We have the updates at:
https://docs.google.com/document/d/1Y1yB7lhR2OHuO8ZAqJBdM3bl9dafeH9wT9BU6-Hfjig/edit

Do you have an ETA on when updates to jujucharms.com/big-data will go live?

If there is any question on content please let us know and we would be glad to discuss.

-thanks,
Antonio

**Comment by Lucapaulina** [comment]
Hi Antonio,

It's built and ready to go, you can see it here:
http://www.jujugui.org/big-data. We're awaiting a large release of the
storefront. This has been delayed due to the conferences w/c 1st Feb and
the UI sprint w/c 8th Feb in Rome. I'm not sure when the release is
scheduled but it should be soon.

Luca

**Comment by johnsca** [comment]
Any update on the storefront release?

**Comment by Lucapaulina** [comment]
Hi Cory,

The new storefront is being released this week.

Luca

**Comment by arosales** [comment]
@Lucapaulina thanks for the update. Looking forward to the update this week.

-Antonio
