### ISSUE TITLE
Can't relate services when starting with a bundle

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#162]
I visit the bundle:
https://jujucharms.com/apache-core-batch-processing/18

Click "Add to Demo"

Press "Commit" and "Confirm" in the GUI

Search for "apache-pig" and add that to the Canvas (commit & automatically place)

Try to create a relation from apache-pig to plugin but the GUI doesn't respond.

I try this in a live AWS environment and it works. The impact is for folks wanting to build additional bundles and share are unable to in the demo GUI.  We would like to promote folks looking at our base big-data bundle and then adding in other plugin charms to build a solution they need.

Let us know if you need any other feedback to help resolve this issue.

-thanks,
Antonio

**Comment by mitechie** [comment]
Thanks for the report. There's a bug in the JS around the relations. Another user reported the GUI bug here that we'll use to track and try to get corrected. 

https://bugs.launchpad.net/juju-gui/+bug/1499857
