### ISSUE TITLE
Juju + Azure docs - Location West US invalid

### ISSUE THREAD

**Issue by andrewdmcleod** [canonical/jujucharms.com#165]
https://jujucharms.com/docs/stable/config-azure

Location: West US 

is no longer valid - Central US (or others?) is. Trying to use West US gives:

2015-10-09 17:00:39 ERROR juju.cmd supercommand.go:430 failed to bootstrap environment: cannot get available role sizes: location "West US" not found

Also further down on this page, instructions referring to where/what to click for creating the storage domain seem a bit outdated (you no longer necessarily need to click anything as it is on "Quick Create" by default, and Disabling "Enable Geo-Replication" is no longer worded as such.

Furthermore, First 'note' box is not clear and may appear to conflict with last 'note' box.

**Comment by evilnick** [comment]
I opened an issue for docs on this:
https://github.com/juju/docs/issues/704

We will run through the azure instructions again - this is something that frequently happens when the provider website/console changes.

However, I did check with Azure. West US is a valid location, and does work for launching instances, so i am not currently sure where the problem with this lies - possibly with the Azure provider.

**Comment by andrewdmcleod** [comment]
Perhaps its an issue with the free tier account - because I am able to create certain resources in West US, but it is not available as a location for a Virtual Machine, either in their new portal management or the classic manager:

<img width="1085" alt="screen shot 2015-10-10 at 11 12 51" src="https://cloud.githubusercontent.com/assets/7427352/10410651/301ad8d2-6f40-11e5-96fd-48ed730af2f9.png">
<img width="1158" alt="screen shot 2015-10-10 at 11 13 11" src="https://cloud.githubusercontent.com/assets/7427352/10410653/3477ef82-6f40-11e5-8a9c-510fbbda662f.png">

I have a feeling this is an issue with my account specifically - @azuresupport on twitter couldnt help me and suggested I contact support - unfortunately I can't log a support request with a free tier account.

**Comment by frankban** [comment]
An issue as been opened for docs, so closing this one.
