### ISSUE TITLE
Wording on community page needs an update

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#166]
"Or talk to us about starting your own “subcommunity”, there are hundreds of solutions available; want to be that champion?"

In hindsight the word "subcommunity" doesn't really seem flattering, can we update this to a more positive-leaning word?

**Comment by Lucapaulina** [comment]
We'll sort this out when we do the community page update.

**Comment by Lucapaulina** [comment]
Done and awaiting the latest release of jujucharms.
