### ISSUE TITLE
Add two more people to the community page

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#170]
Hi!

Arosales would like for us to not just highlight 4 contributors, but at least one contributor in each center of gravity. That means we need two more, one for big data and one for containers. From talking in the session the simplest idea was to just add two more people to the current group of 4, thoughts?

**Comment by Lucapaulina** [comment]
Heya,

We're going to be working on the contributors page (jujucharms.com/community/contributors) this week and next would that content be better suited to that page?

If not, then we can explore having sections based on OpenStack, Big Data and Container, each with one contributor and links to the topic page and external contribution page (Github, etc)

Let us know.

**Comment by castrojo** [comment]
Yes that sounds more inline with what we intended. 

jujucharms.com/community/contributors for people
jujucharms.com/community with top level centers of gravity.

**Comment by Lucapaulina** [comment]
This is implemented and we are waiting for it to land.
