### ISSUE TITLE
Missing diagram in landscape-dense bundle - not a valid position

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#171]
The [Landscape dense bundle](https://jujucharms.com/u/landscape/landscape-dense/)

Includes
https://api.jujucharms.com/charmstore/v4/~landscape/bundle/landscape-dense-8/diagram.svg

which, is not a valid SVG and contains an error message

`{"Message":"cannot create canvas: service \"landscape-server\" does not have a valid position","Code":""}`

**Comment by sparkiegeek** [comment]
https://api.jujucharms.com/charmstore/v4/~landscape/bundle/landscape-dense-8/archive/bundles.yaml.orig has placement annotations for all services _except_ landscape-server. Is this perhaps a validation issue?

**Comment by makyo** [comment]
We seem to have a different set of requirements for bundle proof and for displaying an SVG in the charmstore.  This might be worth bringing up with those working on proof (eco, I believe?) as well as the owner of the bundle.  However, in the future, we do have some plans for adding automatic placement to the jujusvg package, depending on when we have some time to do so.  I'll be working on cleaning up the jujusvg package for a new release on some Friday time coming up, and I'll make that a priority.
