### ISSUE TITLE
Consider putting a link to the blog in the footer

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#172]
Now that the blog RSS has been fixed (not yet deployed), can we consider putting a link to the blog in the footer along with the other topics down there so that it's reachable from any page on the site?

**Comment by Lucapaulina** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;LCMlGVW5&#x2F;34-add-blog-link-to-footer"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add blog link to footer</a>

**Comment by anthonydillon** [comment]
Thank for the suggestion @castrojo. Will add now.
