### ISSUE TITLE
"Upcoming events" on https://jujucharms.com/community is out of date

### ISSUE THREAD

**Issue by mikemccracken** [canonical/jujucharms.com#173]
the upcoming events section has two events, both in the past, one is from July.

**Comment by urosj** [comment]
The events should be tagged "juju" to be shown. jujucharms.com shows the last events that were tagged.

**Comment by mikemccracken** [comment]
@urosj thanks for the explanation about how it works.
However, the issue is not fixed - the site is still showing events that are in the past in a list of "upcoming events". This is confusing and IMO makes the site look a little uncared-for.
If it's possible to change the code that pulls in the tagged events and filter out anything in the past, that'd be ideal.

I tried looking through the source a bit, but wasn't able to follow where the events-feed was coming from - I'm unfamiliar with YUI and don't know where the repository for the javascript for the site is.

**Comment by anthonydillon** [comment]
Technically this is not an issue. However, I agree the wording is
misleading and therefore is a design/user experience issue.

I propose changing the title from " upcoming events" to "latest events".
Design may even consider styling past events differently.

**Comment by mikemccracken** [comment]
@anthonydillon - thanks for your attention here. Is it a lot of work to filter out past events? Your proposal does correct the mismatch, but I'm not sure it's useful to see past events on the page, unless there's some recap or link to video for most of them that gets added later…

**Comment by anthonydillon** [comment]
It issue would be that in this case with no active events coming up there
would be nothing in the section of the page and we would have to design a
replacement.

**Comment by mikemccracken** [comment]
Understood. Thanks for looking into this.

**Comment by Lucapaulina** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dtArDmY1&#x2F;33-upcoming-events-on-https-jujucharms-com-community-is-out-of-date"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> &quot;Upcoming events&quot; on https:&#x2F;&#x2F;jujucharms.com&#x2F;community is out of date</a>

**Comment by anthonydillon** [comment]
The events feed is correct. It is showing the latest two events on insights.ubuntu.com that are tagged "juju".
