### ISSUE TITLE
"juju quickstart openstack-base" doesn't work as written on the site

### ISSUE THREAD

**Issue by mikemccracken** [canonical/jujucharms.com#174]
A few places on the site show the command 'juju quickstart openstack-base' - e.g. if you click on the 'terminal' text box in the 'base cloud' box on the first section of `juju quickstart openstack-base`, you get this in your clipboard: `juju quickstart openstack-base`
1. I tried this in a default install and didn't have juju-quickstart installed, so I got an unhelpful error. We should probably be clearer about that.
2. after installing juju-quickstart, that command gives me an interactive environment setup wizard, then this error: 

```
% juju quickstart openstack-base
interactive session closed
changes to the environments file have been saved
usage: juju-quickstart [-h] [-e ENV_NAME] [-n BUNDLE_NAME] [-i]
                       [--environments-file ENV_FILE]
                       [--gui-charm-url CHARM_URL] [--no-browser]
                       [--distro-only] [--ppa] [--version] [--debug]
                       [--description] [--upload-tools]
                       [--upload-series UPLOAD_SERIES]
                       [--constraints CONSTRAINTS]
                       [bundle]
juju-quickstart: error: unable to open bundle file: [Errno 2] No such file or directory: '/home/ubuntu/openstack-base'
ERROR subprocess encountered error code 2
```

I then pressed the 'view the details' box to get more info about the bundle, and maybe the right way to invoke quickstart, thus I went to this page: `https://jujucharms.com/openstack-base/`\- here under 'Deployment', we are advising this: `juju quickstart bundle:openstack-base`. That also doesn't work:

```
$ juju quickstart bundle:openstack-base
usage: juju-quickstart [-h] [-e ENV_NAME] [-n BUNDLE_NAME] [-i]
                       [--environments-file ENV_FILE]
                       [--gui-charm-url CHARM_URL] [--no-browser]
                       [--distro-only] [--ppa] [--version] [--debug]
                       [--description] [--upload-tools]
                       [--upload-series UPLOAD_SERIES]
                       [--constraints CONSTRAINTS]
                       [bundle]
juju-quickstart: error: unable to open the bundle: invalid bundle URL: bundle:openstack-base
ERROR subprocess encountered error code 2
```

I couldn't figure out how to get quickstart to open the bundle. It'd be nice if the site had the right directions.

**Comment by frankban** [comment]
What version of juju quickstart are you using?
`juju-quickstart --version`.
Could you pleas etry again after updating to the latest version?

```
sudo apt-add-repository ppa:juju/stable
sudo apt-get update
sudo apt-get upgrade
```

**Comment by mikemccracken** [comment]
Ah, that's it. this is a stock wily system without the PPA, so it installed juju-quickstart 1.6.0

Why does wily have such an old version of quickstart, when it has a pretty recent juju-core?

Seems to me the instructions on the site should either mention the PPA or we should be more aggressive about releasing and SRUing quickstart. Ideally the latter, since adding PPA details to the site would be cluttering it up.

**Comment by frankban** [comment]
FWIW https://jujucharms.com/get-started mentions the PPA installation. Anyway, you are right about the SRU, but closing the bug here as this is not related to jujucharms and moreover we are switching away from quickstart in juju2.
