### ISSUE TITLE
Feature: Javascript widget for deploying certain bundles/charms

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#175]
Similar to "Deploy on Heroku" https://devcenter.heroku.com/articles/heroku-button I think it would be really cool to have something similar for the charms/bundles to embed on product pages (outside of jujucharms.com) to promote deploying their application via Juju.

Maybe a javascript embedable widget like:

![image](https://cloud.githubusercontent.com/assets/51892/10971943/f5f52eb8-83a4-11e5-8460-7ed551326e69.png)

Changing "Add to demo" with "Deploy with Juju".

**Comment by Lucapaulina** [comment]
Hi Adam,

We're currently building an embeddable card system to make it easier for users to embed charms, bundles and their profile in external sites. This should be released in the next few weeks and it should solve this issue :)

Luca

**Comment by adam-stokes** [comment]
@Lucapaulina sweet! I'll keep this open so I can track when its ready

**Comment by lazypower** [comment]
This looks like it was pushed out with the last store publication. There are embeddable cards in the bottom right of each charm/bundle listing.

\o/

**Comment by adam-stokes** [comment]
Sweet!!
