### ISSUE TITLE
Namespaced bundle not showing up

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#176]
I pushed a bundle to my launchpad account roughly 3 hours ago and it hasn't shown up under my jujucharms.com account. I was told to file a bug on this:

https://jujucharms.com/u/adam-stokes/

My bundle:
https://code.launchpad.net/~adam-stokes/charms/bundles/ghost/bundle

I pushed updated charms which have since been updated on the website so those seem to be working.

**Comment by urosj** [comment]
Hi @battlemidget, 

We still need to have bundles.yaml due to the legacy store, however it can be empty. Only bundle.yaml will be used though.

**Comment by adam-stokes** [comment]
@urosj I updated the repo, http://bazaar.launchpad.net/~adam-stokes/charms/bundles/ghost/bundle/files

Does that look correct now? I saw some of the bundles on jujucharms.com have a `bundles.yaml.orig` but when I go to view their code the file isn't listed, like https://jujucharms.com/mediawiki-single/9 for example

**Comment by adam-stokes** [comment]
This still doesn't seem to work after adding the bundles.yaml file.

**Comment by adam-stokes** [comment]
Ok, so I pushed to a new repo `ghost-mysql/bundle` and it worked. So maybe having a charm and a bundle the same name under a namespace won't work? If so, should that be a bug?

**Comment by urosj** [comment]
We do not allow bundles and charms to have the same name due to the URL names. /u/bob/ghost can not be both. Great to hear that it is resolved now.
