### ISSUE TITLE
RestComm juju charm not updated in charm store after bzr push

### ISSUE THREAD

**Issue by deruelle** [canonical/jujucharms.com#177]
I pushed some changes to https://code.launchpad.net/~jean-deruelle/charms/trusty/mobicents-restcomm-charm/trunk but I don't see the charm updated on https://jujucharms.com/u/jean-deruelle/mobicents-restcomm-charm/trusty/#revisions while the changes to https://code.launchpad.net/~jean-deruelle/charms/bundles/mobicents-restcomm-mysql-bundle/bundle were taken https://jujucharms.com/u/jean-deruelle/mobicents-restcomm-mysql-bundle/bundle/5/ does anyone have any clue  on why this may be happenin ?

**Comment by urosj** [comment]
Hi @deruelle ,

Sometimes the revisions get out of sync, a process we're currently improving. However, your charms did get published and the code is there even though the old revision is shown.

{"Id":"cs:~jean-deruelle/bundle/mobicents-restcomm-mysql-bundle-5","PublishTime":"2015-11-06T12:32:59.348Z"},{"Id":"cs:~jean-deruelle/trusty/mobicents-restcomm-charm-3","PublishTime":"2015-11-06T12:31:14.358Z"}

The bzr-digest also shows this:
https://api.jujucharms.com/charmstore/v4/~jean-deruelle/trusty/mobicents-restcomm-charm-3/meta/extra-info/bzr-digest
"jean.deruelle@telestax.com-20151106122222-r4thvig6zop0zyi4"

**Comment by deruelle** [comment]
great thx then !
