### ISSUE TITLE
Search for "relation" on jujucharms.com/docs site returns Server Error

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#178]
I am on the page https://jujucharms.com/docs/stable/getting-started and search for "relation" that returns a page that tells me a Server Error has occurred.  The search term "relations" works fine, I get normal search results.

We should not return a Server Error when a term is not found in search results.  Can someone help me fix this problem?
![jujucharms com_server_error](https://cloud.githubusercontent.com/assets/6385185/11007145/9748a252-848d-11e5-949c-de374bf2e175.png)

**Comment by mbruzek** [comment]
More information:  I search for other words that would not be in our docs such as "crazy" and that returns a results page with zero results (as I would expect).  

I am very confused why "relation" returns a server error.

**Comment by mitechie** [comment]
Looks like the team has an update for this.

**Comment by mbruzek** [comment]
@fabricematrat Do you have a link to the code that addresses this issue? I don't think the problem is fixed, I tried the search again today:  https://jujucharms.com/docs/search/?text=relation&version=1.25 and get the Server Error page.

**Comment by bac** [comment]
@mbruzek The fix is being QA'd now and will land in our trunk soon. I'm not sure when it will be released to production.

**Comment by fabricematrat** [comment]
@mbruzek this is why I put fix committed not released sorry for the
confusion I will let you know as soon as it is released

**Comment by mbruzek** [comment]
@fabricematrat How does your fix work?  Is there a list of words that do not return anything?  I searched today for "icon" and got the same error page.  Do I need to create a separate bug for that each word I find?  Can you give me some insight on why this was broken and how you fixed it?

**Comment by mbruzek** [comment]
Also "copyright" does not return a result.

**Comment by fabricematrat** [comment]
Sorry but we did not yet release to prod, this will happens most likely next week.
The error was coming from a parse and unicode error not catched.

**Comment by urosj** [comment]
Fix was released today.
