### ISSUE TITLE
Missing redirect on docs for composing a charm

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#179]
Search interwebs for "juju charm layers", top hit is https://jujucharms.com/docs/stable/authors-charm-composing , le click = 404.

I expect a redirect to https://jujucharms.com/docs/stable/authors-charm-building

**Comment by mitechie** [comment]
Can you replicate this? I've tried logged in and in a private browsing window and the first result is always the charm building doc. 

I've searched the history of the docs thinking that perhaps that file 'author-charm-composing' was committed and then moved/removed but I can't find that in the history at all. As far as I can tell, that page you found via google never existed and I'm not sure why Google would have that indexed. 

Did you search a different engine that Google? If so which one?

Thanks

**Comment by sparkiegeek** [comment]
For the record I use Duck Duck Go, but I can't reproduce it anymore either. :disappointed:
