### ISSUE TITLE
bzr revision not properly imported

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#180]
Looking at the [nova-compute-32](https://jujucharms.com/nova-compute-32/trusty/) page on jujucharms.com it seems like Marco was the last person to touch the charm, and it wasn't updated since 23rd October. Which is exactly the same state as [nova-compute-31](https://jujucharms.com/nova-compute-31/trusty/).

The file changed in [r142](http://bazaar.launchpad.net/~openstack-charmers/charms/trusty/nova-compute/trunk/revision/142) is correctly shown in the [archive for nova-compute-32](https://api.jujucharms.com/charmstore/v4/trusty/nova-compute-32/archive/hooks/nova_compute_context.py) but the [API's revision log](https://api.jujucharms.com/charmstore/v4/trusty/nova-compute-32/meta/extra-info) doesn't show r142 despite having the bzr digest which points at it.

**Comment by urosj** [comment]
Unfortunately this is a known syncing bug. It will be addressed with new publishing.

**Comment by frankban** [comment]
So closing this now.
