### ISSUE TITLE
get-started page doesn't work as written

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#182]
Hi, I'm following the [get-started](https://jujucharms.com/get-started) page to use juju on a fresh trusty install.  I follow the first code block like this:

```
sudo add-apt-repository ppa:juju/stable
sudo apt-get update
sudo apt-get install juju-quickstart
```

Then try the next block:

```
juju quickstart mediawiki-single
```

And get this:

```
The program 'juju' is currently not installed. You can install it by typing:
sudo apt-get install juju-core
```

Once fix is to apt-get install 'juju-core' in addition to 'juju-quickstart' in the first code block.. Another is to make 'juju-quickstart' depend on 'juju-core' and install it if it's missing.  Fwiw, the quickstart version i get after install is:

```
juju-quickstart                           2.2.2+bzr142+ppa39~ubuntu
```

**Comment by kwmonroe** [comment]
Still failing with: juju-quickstart 2.2.3+bzr146+ppa40~ubuntu14.04.1

**Comment by kwmonroe** [comment]
Hit the button too soon -- i meant to say the instructions are still not usable as written.  The latest juju-quickstart doesn't bring in juju-core, so it either needs a dep update, or the instructions should include 'juju-core' in addition to 'juju-quickstart'.

**Comment by marcoceppi** [comment]
https://code.launchpad.net/~marcoceppi/juju-quickstart/recommend-juju/+merge/283745

**Comment by arosales** [comment]
Excellent to see the fix is in the packaging and not extra instructions. Given https://code.launchpad.net/~marcoceppi/juju-quickstart/recommend-juju/+merge/283745 is merged @kwmonroe could you give this a try and see if this resolves your issue?

-thanks,
Antonio

**Comment by arosales** [comment]
Note @kwmonroe we'll have to wait until quickstart is released into juju:stable before testing this.

**Comment by Lucapaulina** [comment]
The page has been tested to work so I'll be closing this issue.
