### ISSUE TITLE
GCE Juju Provider Example Is Out Of Date

### ISSUE THREAD

**Issue by loslosbaby** [canonical/jujucharms.com#185]
This page: https://jujucharms.com/docs/stable/config-gce

...is great, but there are issues:
- the screen captures are out of date
- the JSON for the OAuth has tags that have to be deleted before juju bootstrap will work

juju bootstrap fails with:
Bootstrap failed, cleaning up the environment.
ERROR there was an issue examining the environment: invalid config: key "auth_uri" not supported

The tags that have to be deleted are:
- auth_uri
- token_uri
- auth_provider_x509_cert_url
- client_x509_cert_url

Alternately, juju can be modified to ignore the tags.  I'll let you decide if a bug needs to be filed.

**Comment by mitechie** [comment]
Moved to the docs repo for the team to update. Thanks for the report!

https://github.com/juju/docs/issues/747
