### ISSUE TITLE
Diagrams on homepage should be SVG

### ISSUE THREAD

**Issue by yaili** [canonical/jujucharms.com#186]

**Comment by anthonydillon** [comment]
This is good practise and although a design issue still valid here.

**Comment by spencerbygraves** [comment]
I'll ask Matthieu for the SVGs and pass them onto @anthonydillon

**Comment by Lukewh** [comment]
@anthonydillon did this get done?

**Comment by anthonydillon** [comment]
Yes all SVGs.
