### ISSUE TITLE
bug reporting link is basically invisible

### ISSUE THREAD

**Issue by natefinch** [canonical/jujucharms.com#191]
![image](https://cloud.githubusercontent.com/assets/3185864/12181325/8a91fa5c-b54f-11e5-8394-56c802bd4015.png)

The link for reporting a bug on the site is grouped with the copyright notice, styled to look like the rest of the copyright (and not a link), and far away from the rest of the links in the footer... either we don't want people to report bugs, in which case, we should just remove it, or we should make it a heck of a lot easier to find.  I was actively looking in the footer for exactly that link, and didn't see it until Rick told me to look again.

**Comment by pmatulis** [comment]
Happened to me today exactly as you described but s/Rick/Nick .

**Comment by pmatulis** [comment]
The Doc team would like the following done to this link:
1. Make it more visible (ideas: blue colour, underlined, larger font, embolden font)
2. For [Juju documentation](https://jujucharms.com/docs) pages, make its effective target be https://github.com/juju/docs/issues/new

**Comment by pmatulis** [comment]
Today I noticed that the link has changed. The visible text is now mushed together with preceding text (no space) and it points to https://bugs.launchpad.net/ubuntu-website-content/ instead of the previous https://github.com/CanonicalLtd/jujucharms.com/issues .

**Comment by pmatulis** [comment]
There was a change again but the doc pages still have a link pointing to https://github.com/CanonicalLtd/jujucharms.com/issues .

**Comment by frankban** [comment]
This seems to be solved now, I see the link properly underlined.
