### ISSUE TITLE
Search textbox is invisible

### ISSUE THREAD

**Issue by natefinch** [canonical/jujucharms.com#193]
![image](https://cloud.githubusercontent.com/assets/3185864/12181148/8743fe0a-b54e-11e5-851f-7dde92678113.png)

Is "search the store" a button with an icon?  Is there a text box somewhere in there where I can enter some text?  I can't tell.  It just looks like an icon with some text next to it.

As a user, I wanted to search, but I had no idea where I should click over there, or what would happen when I did so.  What actually happened was that I clicked on the magnifying glass and it brought me to the search results page with a large list of results... and still no help on what to do with the search UI in the upper right.  So, I then carefully moved my mouse cursor from the left of the magnifying glass, over to the right until it turned into a text entry cursor, and then I knew I could click to enter text.

We should make it more obvious that the textbox is a place where you can click to enter text.  What I would expect is for the textbox to have and outline and make the background shaded, and make the "search the store" text gray to show that it'll go away when you type there.

This is in Chrome 47 on Wily, in case that matters.

**Comment by Lucapaulina** [comment]
We've changed the way the search works quite recently which should of solved this issue.
