### ISSUE TITLE
authors-charm-writing conf.php mode

### ISSUE THREAD

**Issue by macgreagoir** [canonical/jujucharms.com#194]
In the https://jujucharms.com/docs/devel/authors-charm-writing install hook example, /var/www/vanilla/conf/ mode is recursively changed to 777, so that the apache user has full access. For a new installation, in this example, /var/www/vanilla/conf/config.php is not present until the database-relation-changed hook writes it, leaving the new file's mode 0644 (for root:root).

Perhaps the config.php file could be touch-ed in an else clause to the config.php cp block, or the file's mode changed (again) in the database-relation-changed hook.

**Comment by frankban** [comment]
Moved to https://github.com/juju/docs/issues/1110
