### ISSUE TITLE
authors-charm-writing vhost conf name

### ISSUE THREAD

**Issue by macgreagoir** [canonical/jujucharms.com#195]
In the https://jujucharms.com/docs/devel/authors-charm-writing install hook example, the vanilla vhost conf file is written without a .conf suffix: 'vanilla' rather than 'vanilla.conf'. In a default trusty apache2 2.4.7-1ubuntu4.8 configuration, en2site expects a .conf suffix to the vhost file name.

**Comment by frankban** [comment]
This seems to be fixed now. And should be directed to juju/docs.
