### ISSUE TITLE
Remove google analytics and marketo tracking codes

### ISSUE THREAD

**Issue by pmahnke** [canonical/jujucharms.com#197]
In an effort to clean-up our tracking codes, we are moving to google tag manager -- which is already installed on the site.

Can you remove the current google analytics code:

<script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1018242-44']);
  _gaq.push(['_trackPageview']);

  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

 and the marketo code:

<script src='//munchkin.marketo.net/munchkin.js' type="text/javascript"></script>

<script>Munchkin.init('066-EOV-335');</script>

It will be added via GTM

**Comment by anthonydillon** [comment]
Fixed
