### ISSUE TITLE
https://jujucharms.com/get-started does not include instructions for OSX

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#20]
The getting started page states:

"Juju quickstart is only available on Ubuntu and OSX. To install Juju on Windows or configure MAAS follow the instructions in the docs."

This implies I could install quickstart on OSX. However the first step only includes instructions for Ubuntu. We should also include instructions for OSX here (and Windows when that arrives).

-thanks,
Antonio

**Comment by fabricematrat** [comment]
@arosales Fix delivered on jujucharms.com
