### ISSUE TITLE
See less button shouldn't jump my scroll position

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#201]
If I click a "See more" link then, as expected, the area expands to show more _things_, but if I then click "See less" I don't expect my scroll position to change.

I note that the anchor in the URL is changing too.

So I start on https://jujucharms.com/landscape-server/trusty/, I click See more for the Connects to section, then when I click See less the URL changes to https://jujucharms.com/landscape-server/trusty/#connects-to

**Comment by sparkiegeek** [comment]
PS Firefox 43.0.4 on Ubuntu 15.10

**Comment by anthonydillon** [comment]
This was done to jump the users view back up to the top of the box. Otherwise the revisions are hidden and leaves the user with an empty view and they need to scroll up to see where they are.

**Comment by sparkiegeek** [comment]
@anthonydillon you mean if I scroll so that the top of the box is above my scroll position, when I click "See less" I don't just lose the box? (is that the intent?)

**Comment by anthonydillon** [comment]
Yes exactly.

**Comment by sparkiegeek** [comment]
Can we instead add smarts so that it only does this if the top of the box **is** outside the viewport?

**Comment by anthonydillon** [comment]
Maybe we can but that would introduce JS a believe. Maybe over working this
issue.

**Comment by anthonydillon** [comment]
@sparkiegeek What do you think of removing the anchor and just have the box shrink? Leaving you in the same position. 

I don't like the idea of controlling the users by jumping them up the page and adding items to the browser history.
