### ISSUE TITLE
Search shows unrelated information

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#204]
Searching for `consul` gets me these results.

The first six results are completely unrelated to consul and shouldn't even be shown. On my laptop I have to scroll to even see the consul results. `consul` is an exact text match, it should be at the top of the results.

![screenshot from 2016-01-27 06-51-51](https://cloud.githubusercontent.com/assets/1264109/12617222/8c7b0dd0-c4c3-11e5-8493-d7abdede6b6a.png)

**Comment by urosj** [comment]
@castrojo Search results restored.

**Comment by castrojo** [comment]
@urosj This isn't related to the outage, I tried it on staging and the now-restored prod instance, same problem.

**Comment by urosj** [comment]
@castrojo this is the same N-gram search issue we always had. Until we break current one bulk search into more staged search results, this will be the case for now.
