### ISSUE TITLE
Strange circular crop of bundle diagram in Firefox 44.0

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#206]
The bundle preview diagram has a [strange crop](http://i.imgur.com/sIkLdRQ.png) in Firefox 44.0 on Ubuntu Wily. The [same URL](https://api.jujucharms.com/charmstore/v5/~openstack-charmers-next/bundle/openstack-lxd-51/diagram.svg) looks fine in Chrome

**Comment by makyo** [comment]
Fix will be available sometime next week, if all goes according to plan.
