### ISSUE TITLE
Charm not ingested: bird

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#207]
I promulgated https://code.launchpad.net/~charmers/charms/trusty/bird/trusty last week but it has not been ingested into the store: https://jujucharms.com/bird/

For reference, I also promulgated neutron-calico (https://code.launchpad.net/~charmers/charms/trusty/neutron-calico/trunk) at the same time and it is ingested: https://jujucharms.com/neutron-calico/

**Comment by urosj** [comment]
Hi, @johnsca 

Shouldn't the LP path be https://code.launchpad.net/%7Echarmers/charms/trusty/bird/trunk and not https://code.launchpad.net/%7Echarmers/charms/trusty/bird/trusty? 

There are no ~charmers/trusty/bird charms in the charm store at all.

**Comment by johnsca** [comment]
Gah.  You're absolutely right.
