### ISSUE TITLE
jujucharms.com and jujucharms.com/docs should search the same things

### ISSUE THREAD

**Issue by marcoceppi** [canonical/jujucharms.com#208]
We should investigate merging the search boxes so that they are unified. For example I can't search the docs from the jujucharms.com root website and I can't search for charms from the docs.

**Comment by Lucapaulina** [comment]
We prioritise the store content over the other aspects of the site because this is the primary journey. Having both docs search and store search in the same results would provide an experience which wouldn't cater to their respective audiences fully.
