### ISSUE TITLE
Version numbered of docs should not be indexed by Google

### ISSUE THREAD

**Issue by marcoceppi** [canonical/jujucharms.com#209]
_From @castrojo on February 3, 2016 7:44_

In GA we're seeing people coming into google hitting versioned URLs like so: jujucharms.com/docs/1.24/pagetitle. 

Google should only be indexing the /stable/ series so when people do a search they end up at the latest stable release docs and not an older version. Probably some combination of robots.txt and sitemap.xml

_Copied from original issue: juju/docs#848_

**Comment by marcoceppi** [comment]
_From @evilnick on February 3, 2016 12:44_
- This doesn't seem like a docs bug, more a jujucharms one
- There are some instances where you _do_ want to find results in a particular version. Moreso after the 2.0 release, because a lot of 1.x stuff won't be searchable at all otherwise, so simply not indexing those pages isn't an option

**Comment by marcoceppi** [comment]
_From @evilnick on February 3, 2016 13:42_

Addendum:  I just checked the analytics. This seems to account for around 0.0015% of searches and they seem to have searched specifically for those urls. Am I missing something?

**Comment by marcoceppi** [comment]
_From @evilnick on February 3, 2016 14:1_

Although, when I do a search for e.g. 'juju cloud provider' I do get references to specific versions, so something is screwy. I thought this was supposed to be solved by the 'canonical' metatag?

**Comment by marcoceppi** [comment]
_From @castrojo on February 3, 2016 14:27_

We're at a sprint so we weren't able to dig into GA, so I filed this in the middle of the guy's lightning talk where I saw the result; mostly as a placeholder that we should investigate. Should I close here and refile under jujucharms.com?

**Comment by evilnick** [comment]
@marcoceppi thx
