### ISSUE TITLE
promulgated charm not showing up as "Recommended"

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#211]
I promulgated ibm-xlc yesterday:

https://jujucharms.com/ibm-xlc/

However, when I search for this charm, it falls under the "Community Recommended" section vs "Recommended".  It does correctly show this being owned by "charmers", but it's not in the right section:

https://jujucharms.com/q/ibm-xlc

**Comment by fabricematrat** [comment]
The main issue is coming from 
https://api.jujucharms.com/charmstore/v5/~charmers/trusty/ibm-xlc-1/meta/any?include=promulgated
Seems that it is not promulgated.

**Comment by arosales** [comment]
As an update, I ran into this issue when searching for realtime-syslog-analytics bundle in the charm store as well as in the Juju GUI

In the charm store when searching for "realtime" (jujucharms.com/q/realtime)  I see the realtime syslog analytics bundle by "charmers" in the "community" space. Should be in the recommended space.

![charm-store-realtime-search](https://cloud.githubusercontent.com/assets/1707853/14479755/0a0486e4-00df-11e6-80fe-528f55532b8b.png)

To make it a little more confusing to users when they deploy the Juju GUI charm and search for realtime they seen an even different result.  The recommended realtime syslog analytics bundle by bigdata-charmers is in the recommended section while the realtime syslog analytics bundle by charmers is in the community section. Note, I have seen Juju users deploy the bundle in this manner (ie via the GUI). 

![screenshot from 2016-04-12 18-38-30](https://cloud.githubusercontent.com/assets/1707853/14479714/9fa93d26-00de-11e6-9b60-1a44a98f4f42.png)

**Comment by kwmonroe** [comment]
To add to Antonio's report, it's strange that you do not see the ~charmers bundle in recommended with this search:

https://jujucharms.com/q/realtime

But you do if you add "syslog" to the search query:

https://jujucharms.com/q/realtime/syslog

And note that neither of those search queries on jujucharms.com show the ~bigdata-charmers version of the bundle as seen in antonio's 2nd screenshot (from juju-gui), though it is promulgated:

```
$ charm show cs:~bigdata-charmers/bundle/realtime-syslog-analytics id promulgated                                                                               
id:
  Id: cs:~bigdata-charmers/bundle/realtime-syslog-analytics-1
  Name: realtime-syslog-analytics
  Revision: 1
  Series: bundle
  User: bigdata-charmers
promulgated:
  Promulgated: true
```

**Comment by urosj** [comment]
This seems to be in an issue in the store front. Both charm store and the gui find the given bundle

https://api.jujucharms.com/charmstore/v5/search?text=realtime&series=bundle

https://demo.staging.jujucharms.com/?search=realtime

Will investigate.
