### ISSUE TITLE
Juju GUI Feedback from IBM Interconnect Conference

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#213]
This bug is to leave feedback, while I remember it, from IBM Interconnect conference.

Folks were really impressed with Juju, and the GUI provided a great way to tell a story in a short time.

Current GUI:
- no readily available way to look at at deployed charm readme on the canvas. There is a link on the "upgrade" portion on the canvas, but I had to hunt and guess. This is not intuitive to a user, and a common feature we used in the previous GUI. The SA, experienced, in Juju could not find this and asked me how to find it and I stumbled upon it when seeing a hypelink next to upgrade, but I think a user may not find this and if they did it may not be intuitive to find the readme there.
- Scroll wheel not available on the right hand side to zoom in an out. I was able to zoom in and out with middle click, but others didn't readily know how to do this.
- Firefox (version:44.0.2) on Trusty has broken icon images in the jujucharms.com charm store browser. Specifically, only showing 1/3 of the icon.

Apologies if they are known issues logged for this already, but I did want to send feedback while I remembered :-)

-thanks,
Antonio

**Comment by mitechie** [comment]
Thanks Antonio. I know @Lucapaulina is working on the first one as it's a chunk of functionality missing from the old pre-2.0 GUI that we want back. 

The second one I'm not sure if we've thought about bringing back any sort of zoom UI component. 

The third one is bug #206 which is fix-comitted and should be in the next release.

**Comment by Lucapaulina** [comment]
We've made significant updates to usability over the last 2 months which should have addressed these issues.

**Comment by anthonydillon** [comment]
I believe the first two issues here are still valid.
1. There was talk of having a link to the charms details in the inspector. Is this still the case?
2. I wonder if scrolling is discoveriblle enough. Can I suggest we add back a simplified version of the zoom widget? Such as the one on google maps.
![google maps](https://cloud.githubusercontent.com/assets/1413534/17250845/168d9d4c-559e-11e6-8700-14de266eb274.png)
3. This issue has been resolved.

**Comment by spencerbygraves** [comment]
We have agreed on a design update for the canvas zoom:

https://github.com/CanonicalLtd/juju-design/issues/158

**Comment by anthonydillon** [comment]
The zoom component has been added to the canvas.
