### ISSUE TITLE
Cards link to the wrong place

### ISSUE THREAD

**Issue by buggtb** [canonical/jujucharms.com#216]
For example:
http://www.meteoriteconsulting.com/spinning-up-pentaho-data-integrations-quickly-with-juju/

If you click the link it goes to:
https://jujucharms.com/pentahodataintegration/trusty/0

not: 
https://jujucharms.com/u/f-tom-n/pentahodataintegration/trusty/0

**Comment by marcoceppi** [comment]
@anthonydillon

**Comment by marcoceppi** [comment]
This issue was moved to CanonicalLtd/juju-cards#10
