### ISSUE TITLE
Docs: Search facility text field does not echo entered text

### ISSUE THREAD

**Issue by pmatulis** [canonical/jujucharms.com#217]
The search facility (box) on https://jujucharms.com/docs works but its text field does not echo entered text. Only the most determined geek will derive any value out of it. To the casual user it is effectively unusable.

**Comment by pmatulis** [comment]
This looks like it's getting fixed here:
https://github.com/CanonicalLtd/blues_browser/pull/1186

**Comment by bac** [comment]
Yes, it is in work @pmatulis . Thanks for noticing and filing the issue.

**Comment by fabricematrat** [comment]
@pmatulis  fix released
