### ISSUE TITLE
misplaced footer on get-started page

### ISSUE THREAD

**Issue by gmeszaros** [canonical/jujucharms.com#219]
https://jujucharms.com/get-started has a misplaced Model, configure and manage Get started div at the bottom.

```
<div class="store-cta">
    <p class="intro">Model, configure and manage <a href="/get-started" class="button--primary">Get started</a></p>
</div>
```

This just links back to the same page, it's a bit confusing.

**Comment by Lucapaulina** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yphoi89u&#x2F;32-misplaced-footer-on-get-started-page"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> misplaced footer on get-started page</a>

**Comment by Lucapaulina** [comment]
Heya,

Thanks for pointing this out. We'll pick this up and get it fixed in the next release.

**Comment by elvirafigueras** [comment]
Hey @gmeszaros, thank you this. We will remove the footer on that page.

**Comment by Lucapaulina** [comment]
The get-started page has been removed recently and should of fixed this issue.
