### ISSUE TITLE
README.md from something totally unrelated.

### ISSUE THREAD

**Issue by stub42** [canonical/jujucharms.com#22]
On https://manage.jujucharms.com/charms/precise/storage, the rendered README is from a totally unrelated project. The readme in the charm seems fine. Something is very confused.

**Comment by mitechie** [comment]
Thanks @stub42. There does seem a bug in charmworld. However that's the old site on old code that's not intended for users. The new site is showing correctly on jujucharms.com 

https://jujucharms.com/storage

I'm closing the bug on this end and recommend we move everyone off of the manage site. It will be deprecated and eventually turned off once all api clients have moved to off of the manage.jujucharms.com/v3 api to the new v4 api on api.jujucharms.com.

It's also loading correctly from the GUI:
https://demo.jujucharms.com/precise/storage-2
