### ISSUE TITLE
"Juju" not prominent on first page

### ISSUE THREAD

**Issue by bac** [canonical/jujucharms.com#220]
After the release on 2016-03-03 I got the following feedback:

So... the front page doesn't actually say Juju anywhere, except in a tiny image in the far upper left.  When I open the url, my brain really only sees the middle 60% of the webpage, which means I see this:

![jujucharms](https://cloud.githubusercontent.com/assets/617845/13573616/edc0b510-e456-11e5-9a51-cb627223d8d0.jpeg)

Which just makes me think "What is the fastest way to model my service?"

Maybe we should put the juju name/logo above this text, so it's right dead center where you can't miss it?

**Comment by Lucapaulina** [comment]
We've updated the homepage which should of solved this issue.
