### ISSUE TITLE
typos / text changes

### ISSUE THREAD

**Issue by bac** [canonical/jujucharms.com#221]
On https://jujucharms.com
s/Juju is a application/Juju is an application/

**Comment by bac** [comment]
Also:
deploy and manage entire cloud environments 
should be
deploy and manage applications in the cloud

**Comment by bac** [comment]
On get-started s/for local environments/for local deployments/

**Comment by bac** [comment]
In jaas_storefront/templates/static_pages/community.jinja2 use the British spelling 'modelling' for consistency.

**Comment by bac** [comment]
s/Big Data environment/Big Data model /

**Comment by fabricematrat** [comment]
@bac fix released
