### ISSUE TITLE
Search for ceilometer-agent returns old charm revision instead of latest

### ISSUE THREAD

**Issue by panlinux** [canonical/jujucharms.com#222]
If I search for ceilometer-agent (https://jujucharms.com/q/ceilometer-agent?type=charm), the first result is https://jujucharms.com/ceilometer-agent/trusty/14

That is not the latest version of the charm. I can "hack" the URL and use, say, https://jujucharms.com/ceilometer-agent/trusty/56, and that will also work.

In fact, at the time I write this, the last version is 57 (https://api.jujucharms.com/charmstore/v4/ceilometer-agent/meta/any).

Besides this, the "By <name>" text just below the charm name reads differently between r14 and r56. In r14, it reads " By openstack-charmers-archive" and in r56 it reads "By openstack-charmers". It's as if ownership changed.

**Comment by urosj** [comment]
https://api.jujucharms.com/charmstore/v4/search?text=ceilometer-agent

Ownership issue we had long time ago. we return two promulgated charms with different owners (openstack-charmers and charmers). This applies to charm store search index primarily, @mhilton, @rogpeppe .

**Comment by panlinux** [comment]
This happens with other charms as well. For example, glance:
- https://jujucharms.com/q/glance has https://jujucharms.com/glance/trusty/31 as the first hit, but the current revision of that charm (https://api.jujucharms.com/v4/glance/meta/any) is 157 ({"Id":"cs:trusty/glance-157"})
