### ISSUE TITLE
https://jujucharms.com/openstack openstack-base bundle does not match component list

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#224]
On the openstack landing page the openstack-base bundle layout is showing but the services don't match what is shown in the bundle SVG layout. Namely neutron-gateway is missing from the individual charms

Also the MySQL icon is not showing correctly in the bundle layout.

**Comment by urosj** [comment]
@arosales bundle defines service name as mysql, but the charm for the service used is actually charm: cs:trusty/percona-cluster-32 ... so the visualization is correct.

**Comment by arosales** [comment]
@urosj,

Thanks for the reply. That helps with the MySQL issue, but the neutron-gateway charm is still missing from the individual charm list.

**Comment by arosales** [comment]
I think the solution here is to remove quantum-gateway from the charm list below the bundle, and add neutron-gateway to the charm list.
