### ISSUE TITLE
Replace Ubuntu logo in "Users and contributors"

### ISSUE THREAD

**Issue by yaili** [canonical/jujucharms.com#226]
In the section "Users and contributors" on the homepage the Ubuntu logo is the full orange version.

We should use the black and orange logo: https://assets.ubuntu.com/v1/adac6928-ubuntu.svg

**Comment by bac** [comment]
Hi @yaili can you include the URL you are referencing?

**Comment by Lucapaulina** [comment]
Hi Brad,

The section in question is: www.jujucharms.com

**Comment by bac** [comment]
Ah, thanks @Lucapaulina .  That page is not seen if you are logged in...which I was.

**Comment by yaili** [comment]
Thanks, @Lucapaulina 

Let me know if you need anything else @bac
