### ISSUE TITLE
The charmstore does not support the full range of markdown

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#228]
I was using some tables in markdown for consistently in data presentation about where the layers live that the charm was built from. This seemed like something handy to have in a readme right?

https://jujucharms.com/u/containers/logstash/trusty/1

Sadly the store markdown processor either doesn't allow tables, or doesn't know about them. Any chance we can get some github flavored markdown support there?

_edit_

Full list of what we have found to be broken/missing/incomplete

BlockQuotes with '>'
Tick Fenced code  ```
tables support (listed above)
nested lists with - and {spaces} -  to sub-tree the lists.

**Comment by lazypower** [comment]
I did some digging and I have a potential lead on this:

https://github.com/russross/blackfriday

Looks like blackfriday when combined with bluemonday has a really good GFMD combo along with output sanitization. As the README's are by definition, user defined input.

**Comment by bac** [comment]
Thanks for the report and possible solution @chuckbutler

**Comment by AdamIsrael** [comment]
+1 to this problem. I've seen several charms in the store with misrendered markdown due to this, i.e., https://jujucharms.com/nrpe/

**Comment by mbruzek** [comment]
+1 to this problem. We have several inconsistencies between online markdown renders and what is showing up in the charm store.

**Comment by frankban** [comment]
We now support a wider markdown range, including github extensions.
