### ISSUE TITLE
Machine count for bundle on profile page is always 0?

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#232]
On [Landscape profile page](https://jujucharms.com/u/landscape/) for all three bundles there is a machine count of 0, but actually looking at the [bun](https://jujucharms.com/u/landscape/landscape-dense-maas/)[dle](https://jujucharms.com/u/landscape/landscape-dense/) [pages](https://jujucharms.com/u/landscape/landscape-scalable/) I see the correct numbers

**Comment by fabricematrat** [comment]
Fix released.
