### ISSUE TITLE
Investigate why launchpad.net is getting higher SEO than jujucharms.com

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#234]
Search for "fiche jujucharms" and it returns the launchpad branches ahead of the jujucharms.com page. We should investigate if there's a way we can make the store page more attractive to indexers so those pages come up first.

I don't think cross-domain rel canonical tags would not work, it's not duplicate content per-se.

**Comment by bac** [comment]
First thought is it might be hard. Charms ingested from Launchpad have all of the same information as the Launchpad page.   Given the history and reputation of Launchpad those pages will probably continue to have better SEO than us, all things being equal.

Here is the meta data for `https://jujucharms.com/fiche/trusty/2`. Interesting to note the page on Launchpad has no keywords or meta tags.

```
<meta charset="UTF-8" />
<meta name="description" content="Deploy fiche to bare metal and public or private clouds using the Juju GUI or command line." />
<meta name="keywords" content="juju, charms, services, cloud, deployment, puppet, chef, fuel, cloud tools, service management, cloud management, configuration management, linux tool, openstack tool, ubuntu, cloud design, applications, model, modelling, cloud orchestration, service orchestration" />

    <meta property="og:title" content="fiche" />
    <meta property="og:url" content="https://jujucharms.com/fiche/trusty/2" />

      <meta property="og:description" content="Fiche is an open source command line pastebin server. It can be found here:
https://github.com/solusipse/fiche
" />
```

If we're using the same keywords on all of jujucharms.com pages that might be penalizing us.

In the long run, we'll turn off ingestion from Launchpad and the ecosystem will just be on jujucharms.com. That isn't helpful right now, though.

**Comment by castrojo** [comment]
We have meta content in the charms themselves for tags, I was wondering if we should investigate ingesting those and adding it to the meta tag?

Also with ingestion going away and lp not being the one-true-source anymore this will probably resolve itself, so maybe we should retarget this bug to be more about meta information?

**Comment by frankban** [comment]
This seems not to be an issue anymore.
