### ISSUE TITLE
getting-started devel docs 404 on credential guide

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#235]
https://jujucharms.com/docs/devel/getting-started

Section 3, "Enter your credentials" has a link at the very end that tells the reader to "see this guide to credentials".  It points here:

https://jujucharms.com/docs/devel/credentials/

And that 404s.

**Comment by pmatulis** [comment]
Migrated to https://github.com/juju/docs/issues/938
Please close this.

**Comment by kwmonroe** [comment]
Cool, thanks for moving this to the right place.
