### ISSUE TITLE
User pages don't allow for clicking on bundles

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#237]
When I visit a jujucharms.com user page such as:
https://jujucharms.com/u/containers/

I can see the bundles, but I can't click on them to get the deploy command or learn more about them via the readme.

For example, on https://jujucharms.com/u/containers/ I see the "auditable kubernets" bundle and clicking on it expands so I can see the bundle SVG but no details on how to deploy, and I can't seem to click on it to see more details.  Ideally, I want to click on the "auditable kubernetes" bundle and see an option to view the full details via https://jujucharms.com/u/containers/auditable-kubernetes/bundle/2.

**Comment by Lucapaulina** [comment]
Thanks, this is a known bug and is currently being fixed.

**Comment by Lucapaulina** [comment]
Can someone confirm if this is fixed? Last I saw this was done.

**Comment by anthonydillon** [comment]
We added a View button to the expanded panel. Therefore this is resolved.
