### ISSUE TITLE
https://jujucharms.com/docs/devel/credentials is 404

### ISSUE THREAD

**Issue by nskaggs** [canonical/jujucharms.com#238]
https://jujucharms.com/docs/devel/credentials is linked from https://jujucharms.com/docs/devel/getting-started, but does not exist.

**Comment by pmatulis** [comment]
Thank you but this is a duplicate of https://github.com/juju/docs/issues/938.
Please close this.

**Comment by bac** [comment]
Thanks for the report @nskaggs but as it is a duplicate of the juju/docs issue I'm closing this one.
