### ISSUE TITLE
Big Data landing page charm changes

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#239]
We promulgated the new big data bundles, which use a few new charms.  However, the "Key Big Data charms" section on https://jujucharms.com/big-data still references the old charms.  Please replace those charms with the following:
- apache-hadoop-namenode
- apache-hadoop-resourcemanager
- apache-hadoop-slave
- apache-spark

**Comment by kwmonroe** [comment]
I have a couple notes to add here.. First, we had 3 bundle name changes in the following sections:
- Apache MapReduce
  - **apache-core-batch-processing** is now [apache-processing-mapreduce](https://jujucharms.com/apache-processing-mapreduce/)
- Apache Spark
  - **apache-hadoop-spark** is now [apache-processing-spark](https://jujucharms.com/apache-processing-spark/)
- Kafka Data Ingest Bundle
  - **apache-ingestion-flume-kafka** (which was in the ~bigdata-dev namespace) is now [apache-ingestion-kafka](https://jujucharms.com/apache-ingestion-kafka/) (which is in the promulgated namespace)

And secondly, I just wanted to clarify Cory's initial comment about the "Key Big Data charms" section:
- **apache-hadoop-yarn-master** is now [apache-hadoop-resourcemanager](https://jujucharms.com/apache-hadoop-resourcemanager/)
- **apache-hadoop-hdfs-master** is now [apache-hadoop-namenode](https://jujucharms.com/apache-hadoop-namenode/)
- **apache-hadoop-compute-slave** is now [apache-hadoop-slave](https://jujucharms.com/apache-hadoop-slave/)
- **apache-hadoop-hdfs-secondary** should be removed
- **apache-spark** stays the same

If removing the hdfs-secondary charm throws off the balance of the "Key Big Data charms" box, you can add this one:
- [apache-kafka](https://jujucharms.com/apache-kafka/)

Apologies for so many changes, but we've finally named our core charms/bundles to something the community might actually recognize, which is a big improvement for us.  Thanks for your help in updating the landing page!!

**Comment by anthonydillon** [comment]
Thank you very much. The changes have been made and will be live with the next release.
