### ISSUE TITLE
charmstore units filling up /tmp

### ISSUE THREAD

**Issue by hloeung** [canonical/jujucharms.com#240]
Hi,

We're receiving regular alerts about disk usage on the charmstore units. On inspection, it seems it's mostly the charm cache directories as per https://pastebin.canonical.com/153369/.

Any chance we could have this addressed and so we're not constantly being alerted about it?

Thanks,

Haw

**Comment by urosj** [comment]
@hloeung We're killing this process in a month, but if it's an easy fix to not use /tmp cache, then we'll fix it. I also believe that we'll need to think about migrating to a bigger storage for the DB, that one will get filled up so.

**Comment by urosj** [comment]
Update to charmload process to land today/tomorrow.
