### ISSUE TITLE
Update bundle to use on the get-started page.

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#242]
We've created a new awesome `wiki-single` bundle: https://jujucharms.com/wiki-simple/

We'd like this to replace the old bundle, but we need to update instructions first:

Step 2 should be `juju quickstart wiki-simple`
Step 4 should be `juju expose wiki`
Step 5 should be `juju status wiki`

**Comment by urosj** [comment]
With Juju 2.0 just around the corner, I'd like to replace all "quickstart" instructions with native deploy.

**Comment by urosj** [comment]
Also, UX has new designs in place.

**Comment by Lucapaulina** [comment]
Hey @urosj, this page is being removed in the near future with the content to be consolidated into the docs. We don't have new designs for it.

**Comment by castrojo** [comment]
@Lucapaulina Can you confirm what you mean by "being removed"? Do you mean you'll forward /get-started to the current doc's get started page? It's important that we do not break that URL.

**Comment by marcoceppi** [comment]
Also, why is it being removed at all? I understand not linking to it - but just deleting it?

**Comment by Lucapaulina** [comment]
We'll link to the docs page. It's counter intuitive to have so many "get
started" pages. We should focus our efforts to see the best results.

**Comment by marcoceppi** [comment]
Okay, well we'll want to keep that get-started page HTML - it's slick, and just put it in the docs

**Comment by Lucapaulina** [comment]
I the page url will redirect to the new place. I'm not sure if we'll keep the design of the page as docs has a different look and feel. We'll be working closer with @evilnick on the get-started stuff in the future.

**Comment by urosj** [comment]
@Lucapaulina the page should stay until we have equivalent in the docs.
