### ISSUE TITLE
"undefined" charm owner in Preview sidebar

### ISSUE THREAD

**Issue by ursinha** [canonical/jujucharms.com#245]
A new version of landscape-server charm was uploaded to the store yesterday, and as can be seen at https://jujucharms.com/landscape-server/trusty/14, the owner of the charm in the Preview sidepanel says "undefined" (which amusingly links to an existing user in launchpad):
![preview-undefined](https://cloud.githubusercontent.com/assets/215685/14395744/dd3d504c-fda9-11e5-850e-a70783308938.png)

Previous version (https://jujucharms.com/landscape-server/trusty/13) displays the right owner, landscape-charmers.

**Comment by ursinha** [comment]
bac pointed that landscape-server is not the only one with this problem: https://jujucharms.com/u/juju-gui-charmers/juju-gui/trusty/53. At the top it says "by charmers", it is the "card" at the bottom right that displays the problem.

**Comment by anthonydillon** [comment]
This has been fixed in the latest release of Juju cards (1.2.0). This has
been committed to the jujucharms code base and will be live with the next
release of jujucharms.

**Comment by johnsca** [comment]
We have been able to work around this for the big data charms by setting the `bzr-owner` under `extra-info`:

```
charm set cs:~bigdata-charmers/apache-hadoop-namenode bzr-owner=bigdata-charmers
```

But, clearly, this is not ideal and I'm looking forward to the proper fix.

**Comment by anthonydillon** [comment]
This has gone live. Thank you.
