### ISSUE TITLE
"View code" in bundle page links to juju store url with version "None" (instead of a launchpad branch) resulting in a 404

### ISSUE THREAD

**Issue by ursinha** [canonical/jujucharms.com#246]
landscape-server bundles were uploaded to the store yesterday (https://jujucharms.com/u/landscape/landscape-dense-maas/bundle/18), when looking for the source code I noticed "View code" at the side bar gives you a store url with version "None": https://jujucharms.com/u/landscape/landscape-dense-maas/bundle/None. I would expect a launchpad URL pointing to a branch.

Version uploaded yesterday is 18, and same problem can be observed in v17. For v16 (https://jujucharms.com/u/landscape/landscape-dense-maas/bundle/16) the "View code" link is a launchpad one as it should be: http://code.launchpad.net/~landscape/charms/bundles/landscape-dense-maas/bundle. Something happened in the meantime?

I believe it's not only related to landscape bundles, I noticed this regression because I knew when they were uploaded and I could see when it started breaking.

**Comment by ursinha** [comment]
Seems to be a dupe of https://github.com/CanonicalLtd/jujucharms.com/issues/241.

**Comment by anthonydillon** [comment]
The view code has been removed from the details pages as we now have charm push which results in no project page.
