### ISSUE TITLE
Namespace issues 

### ISSUE THREAD

**Issue by Yrrsinn** [canonical/jujucharms.com#248]
When using '`charm push`' and '`charm publish`' my namespace is not updated, still pointing to old revisions of my charms. Other parts of the store seem to be not affected. Included is an irc-chat from #juju with the details. 

> BrunoR  after charm push and publish, the named store still shows the old revision of my charm. is there a step which I overlooked?
> cory_fu BrunoR: What's the charm store URL?
> cory_fu BrunoR: You might need to set the acl, or if you're referring to a promulgated charm then it requires a charmer and another step for promulgation
> BrunoR  cory_fu: https://jujucharms.com/u/3-bruno/ , e.g. the quobyte-registry charm is linked in revision 2, I would expect revision 4
> cory_fu BrunoR: Hrm.  That's odd.  https://jujucharms.com/u/3-bruno/quobyte-registry/ points to 4 and everything looks fine in `charm show cs:~3-bruno/trusty/quobyte-registry id published perm`
> cory_fu But your namespace isn't updated
> cory_fu The search page is up to date as well: https://jujucharms.com/q/quobyte-registry
> cory_fu BrunoR: Looks like an issue with namespaces
> cory_fu Looks like it's affecting ~bigdata-charmers as well
> cory_fu BrunoR: Please file a bug at https://github.com/CanonicalLtd/jujucharms.com/issues

**Comment by urosj** [comment]
Seems that there's an error in /list API of charm store, which returns two results for the same charm, revision 4 and the also revision 2 and in the web, we show only the last one. 

charm list -u 3-bruno
cs:~3-bruno/trusty/quobyte-api-1
cs:~3-bruno/trusty/quobyte-data-1
cs:~3-bruno/trusty/quobyte-metadata-1
cs:~3-bruno/trusty/quobyte-registry-4
cs:~3-bruno/trusty/quobyte-registry-2
cs:~3-bruno/trusty/quobyte-webconsole-1

**Comment by urosj** [comment]
Is this still valid? AFAIK 3-bruno user has been deactivated.

**Comment by Yrrsinn** [comment]
renamed, but I guess the issue can be closed
