### ISSUE TITLE
https://jujucharms.com/solutions returns 502

### ISSUE THREAD

**Issue by nskaggs** [canonical/jujucharms.com#25]
Clicking the prominent button to 'see all solutions' from jujucharms.com results in a bad gateway error.

**Comment by mitechie** [comment]
thank you for the report @nskaggs we're working with our ops team to figure out why our elasticserach service isn't responding and will get this back up asap.

**Comment by mitechie** [comment]
the site is back up and background processes are recovering. Closing as fixed. Thanks for the report!
