### ISSUE TITLE
Documentation leaves you at a dead end

### ISSUE THREAD

**Issue by warsaw** [canonical/jujucharms.com#253]
When you follow the getting started guide at https://jujucharms.com/docs/devel/getting-started and finish playing around, you'd like to then play with deploying charms at https://jujucharms.com/docs/devel/charms

However, one of the last things the getting started guide instructs you to do is:

```
Note: To remove all the services in the model you just created, it is often quickest to destroy the model with the command 'juju destroy-model default` and then create a new model.
```

It doesn't really tell you how to create a new model.  But now when you `juju deploy mediawiki` you get the following error:

```
% juju deploy mediawiki
Added charm "cs:trusty/mediawiki-5" to the model.
Deploying charm "cs:trusty/mediawiki-5" with the charm series "trusty".
ERROR cannot add service "mediawiki": model "default" is no longer alive
```

You cannot `juju create-model default` because it already exists.  Thus it's not clear what state the default model is in, nor how to proceed.

**Comment by bac** [comment]
Hi @warsaw thanks for the bug report. Glad to have someone looking through the docs and taking notes.

The documentation for juju is actually a separate project: juju/docs.  I've copied this issue over to its tracker: https://github.com/juju/docs/issues/1012.  Please follow it over there.

**Comment by warsaw** [comment]
@bac Thanks!  I'll watch both projects.
