### ISSUE TITLE
searching for "storage" returns a deadlink

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#256]
I searched the Juju docs for "storage" and clicked on the first link titled "Storage support" which brings me to the 
# Sorry, we couldn’t find the page you’re looking for.

page for the link: https://jujucharms.com/docs/master/storage/

I know how to clone and edit text on pages, but this appears to be a search issue. How do we remove old pages from the search index?

**Comment by frankban** [comment]
This seems to be fixed now. Please reopen if that's not the case.
