### ISSUE TITLE
Cannot deploy juju-gui on the openstack internal juju environment. 

### ISSUE THREAD

**Issue by shadaab** [canonical/jujucharms.com#257]
HI.
I am running juju version 1.25.5-trusty-amd64.
I get this error while deploying juju-gui in the internal juju environment of the openstack cloud.

landscape@juju-machine-0-lxc-1:~$ juju deploy --to 0 juju-gui
ERROR cannot load cookies: file locked for too long; giving up: cannot acquire lock: open /home/ubuntu/.go-cookies.lock: permission denied

**Comment by hatched** [comment]
Hi shadaab,

This is typically caused by another juju process already running. Check that first and if this isn't the case then you can remove `/home/ubuntu/.go-cookies.lock`. If none of these work for you then you can file an issue here: https://github.com/juju/juju/issues

**Comment by shadaab** [comment]
Thanks,
I dont have any other juju process running nor there is any .go-cookies.look file in the home directory.

These are the steps that i followed:
1.export JUJU_HOME=~/.cloud-install/juju
2. juju ssh landscape-server/0 sudo 'JUJU_HOME=/var/lib/landscape/juju-homes/`sudo ls -rt /var/lib/landscape/juju-homes/ | tail -1` sudo -u landscape -E bash'
3.juju status
4juju deploy --to 0 juju-gui

Is this the correct way of deploying juju-gui in the internal juju environment?
