### ISSUE TITLE
Search doesn't bring best results

### ISSUE THREAD

**Issue by panlinux** [canonical/jujucharms.com#26]
While searching for the landscape-server charm, jujucharms.com is presenting me with lots of unrelated results first.

The URL is https://jujucharms.com/q/landscape-server, and check out the attached screenshot showing what I get back.
![screenshot_005](https://cloud.githubusercontent.com/assets/5117210/5361836/87570c7c-7fb5-11e4-9afc-731874b95950.png)

**Comment by mitechie** [comment]
We were having some downtime with elasticsearch powering our search and the results weren't complete or correct. Now that we've corrected things look much better. 

https://staging.jujucharms.com/q/landscape
