### ISSUE TITLE
Can't see private charms unless I log out and log back in

### ISSUE THREAD

**Issue by cmars** [canonical/jujucharms.com#261]
Several times when I've searched for private charms that I have access to, I get zero results. If I log out and log back in through the webpage, I then see the charms.

Is this a known issue? Is it being worked on?

**Comment by mattyw** [comment]
Just to add my 2c. I've been able to reproduce it daily for a few months now

**Comment by cmars** [comment]
I haven't been able to reproduce this one. If @mattyw can't either, I move to close it.

**Comment by anthonydillon** [comment]
I can reproduce too.

**Comment by frankban** [comment]
With the public beta now opened, authenticated users now use the GUI when looking at the store, so this issue should be now fixed. Please reopen this bug if any other inconsistencies are encountered.
