### ISSUE TITLE
deploy cs:trusty/ubuntu deploys Xenial charm

### ISSUE THREAD

**Issue by stub42** [canonical/jujucharms.com#263]
Attempting to use the cs:trusty/ubuntu charm to deploy a Trusty image, I instead end up with Xenial.

stub@uurp:~$ juju deploy cs:ubuntu
Added charm "cs:ubuntu-0" to the model.
Deploying charm "cs:ubuntu-0" with the default charm metadata series "xenial".
stub@uurp:~$ juju deploy cs:trusty/ubuntu u2
Added charm "cs:ubuntu-0" to the model.
Deploying charm "cs:ubuntu-0" with the default charm metadata series "xenial".

I suspect this is charmstore behaviour and belongs here, rather than juju-core?

**Comment by stub42** [comment]
Duplicated at https://bugs.launchpad.net/juju-core/+bug/1582555

**Comment by lazypower** [comment]
I think this is core's issue, as I've seen this happen many times with series in metadata, it seems to default to whatever is listed first in the series key in metadata unless you override it with --series=foo

The charm store url has a definite identifier, an should be respected, so i'm inclined to think its more targeted at core than the store, as the store did what was appropriate, it served the charm residing at that location, juju just did the wrong thing with what it was given.

Similar story uncovered when using amulet and series-in-metadata: https://github.com/juju/amulet/issues/137

/my2cents

**Comment by mhilton** [comment]
This looks like a juju-core issue to me, The charmstore will resolve the charm to the same thing as latest ubuntu charm supports both series. juju-core should be determining that trusty series was asked for and install the correct OS image.

**Comment by jcsackett** [comment]
Closing here so the issue can be tracked at the LP link.
