### ISSUE TITLE
Unable to load bundle details into canvas

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#268]
I deploy a Juju 2.0 controller, and then issue a 'juju gui.'  From there I want to deploy a bundle from the GUI so I search for "bigtop."  
![bigtop-search](https://cloud.githubusercontent.com/assets/1707853/15303095/f3cecc3a-1b6a-11e6-94e5-cd1bcce1f8f1.png)

I find the bundle I want under "Community" and I click on that bundle to them deploy it via the GUI. However, I get the error, "There was a problem while loading the entity details. You could try searching for another charm or bundle or go back."

![bigtop-gui-fail](https://cloud.githubusercontent.com/assets/1707853/15303114/06c89244-1b6b-11e6-93d8-208525d0bc5d.png)

The deployed GUI does seem to be able to deploy non-recommended charms.

-thanks,
Antonio

**Comment by frankban** [comment]
Moved to the GUI project at https://github.com/juju/juju-gui/issues/1685 
I also have a question there.
