### ISSUE TITLE
Non recommended charm shown as owned by ~charmers in deployed GUI

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#269]
I see the development version of a bundle in a personal name space:
https://jujucharms.com/u/bigdata-dev/bigtop-processing-mapreduce/bundle/11

However, when I search for this same bundle in the deployed GUI I see it owned by ~charmers which is incorrect:

![bigtop-search](https://cloud.githubusercontent.com/assets/1707853/15303209/6a6dd80e-1b6b-11e6-83a5-67f3f86d8669.png)

**Comment by frankban** [comment]
Opened against the GUI project.
