### ISSUE TITLE
Enable compression for svg

### ISSUE THREAD

**Issue by fabricematrat** [canonical/jujucharms.com#27]
Icons, bundle visualization are in svg format which could be highly compressed so we should enable copression for those types.

**Comment by kapilt** [comment]
fwiw, they are transferred compressed (gzip) if your looking at headers on
svg resource off the site. static might be nicer than runtime + cache
though.

**Comment by mitechie** [comment]
Oh man, we were looking at https://api.jujucharms.com/v4/mediawiki/icon.svg and it was so big I just assumed it wasn't compressed. I missed that the compressed size is 214k. 

Thanks for correcting this and we'll take this up with the icon folks to see if we can get a better compressed icon for this very common charm.
