### ISSUE TITLE
"Used in these solutions" results should include personal name spaces

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#270]
The "Used in X solutions" section in the store only shows things that are promulgated. 

https://jujucharms.com/store/filebeat/trusty/1

It would be useful to show what other bundles are using those charms below the promulgated space.

**Comment by urosj** [comment]
I think this is expected behaviour.

**Comment by urosj** [comment]
We might add "see all" section, however, in long term, this will be handled differently.

**Comment by anthonydillon** [comment]
We no longer have a "Used in X solutions" section in charm details pages.
