### ISSUE TITLE
Typo on the juju layers page

### ISSUE THREAD

**Issue by cholcombe973** [canonical/jujucharms.com#271]
layers.yaml should read layer.yaml in this sentence: `We will put these in a layers.yaml file, which tells the builder what layers and interfaces to combine with yours to create the finished charm:`

**Comment by lazypower** [comment]
@cholcombe973 - what page url did you find this on?

**Comment by cholcombe973** [comment]
@chuckbutler it was here: https://jujucharms.com/docs/devel/authors-charm-building  Looks like it's been fixed already!
