### ISSUE TITLE
adding description to bundle.yaml causes a rendering issue with page

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#273]
I added

```
description: |
  This bundle deploys an OpenStack Cloud (Mitaka release), configured to use LXD
  (the lightweight container hypervisor), on Ubuntu 16.04, providing Dashboard,
  Compute, Network, Object Storage, Identity and Image services.
```

After a charm push/publish the resulting page looks like this:

![image](https://cloud.githubusercontent.com/assets/51892/15432082/ad1c231a-1e7a-11e6-8a4d-0f14faec983b.png)

Full page can be seen here:
https://jujucharms.com/u/conjure/openstack-novalxd/bundle/5

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue to us. A fix has been proposed and the issue should be resolved in the next release of the site.

**Comment by adam-stokes** [comment]
Why is this closed? I don't see the changes on jujucharms.com

**Comment by anthonydillon** [comment]
This was auto closed as it was referenced in the PR which landed but has
not been pushed live yet.

Will reopen until live.

**Comment by adam-stokes** [comment]
ah ok, thanks for the update
