### ISSUE TITLE
It's not obvious when you're on a promulgated charm's page

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#274]
I was looking for some kibana charms and ended up on the promulgated page and some personal pages. Other than looking at the URL it's not obvious which one is the recommended one and which one is in a personal name space.

It should be obvious and in my face visually that the kibana page I am on is the recommended one, and that the others ones are not. 

cc @Lucapaulina

**Comment by Lucapaulina** [comment]
We've changed the store recently to show only promulgated charms so I think this would be finished.

**Comment by anthonydillon** [comment]
I believe this issue is regarding no visual difference between a none promulgated and promulgated details pages. It would be nice to explain the design stance on this suggestion.

**Comment by anthonydillon** [comment]
This will need some design exploration. Therefore this issue has been raised in juju-design. Please track its progress there.

**Comment by Lukewh** [comment]
The juju-design issue has been closed. Closing this one too.
