### ISSUE TITLE
View code link no longer works

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#275]
Going to: https://jujucharms.com/u/bigdata-dev/apache-processing-spark/

Click on view code, it tries to send you here: https://jujucharms.com/u/bigdata-dev/apache-processing-spark/None

Which doesn't exist. The charm author has pushed the right metadata for the "Home" field, so perhaps when that is present don't show this link?

**Comment by anthonydillon** [comment]
This has been removed and will be live in the next release.

**Comment by anthonydillon** [comment]
Reopening until the fix has landed.

**Comment by anthonydillon** [comment]
The view code link has been removed from details pages as we now have charm push.
