### ISSUE TITLE
Markdown code blocks are not rendered with newlines

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#276]
In my published charm (https://jujucharms.com/u/mbruzek/kubernetes/trusty/5) the README is not getting rendered correctly on the Charm Store.

The readme markdown starts and ends a code a block with three backticks:

```
juju deploy trusty/etcd
juju deploy local:trusty/kubernetes
juju add-relation kubernetes etcd
```

This block gets rendered without any newlines as:

`juju deploy trusty/etcd juju deploy local:trusty/kubernetes juju add-relation kubernetes etcd`

We should preserve the newlines in code blocks or I suspect you will have many other people finding this a problem.

**Comment by jrwren** [comment]
Also, sometimes the blocks are rendered with the ``` being displayed.

https://jujucharms.com/u/evarlast/parse-server/trusty/0  See the _Using it_ section.

**Comment by lazypower** [comment]
Linking this with #228  as we've had some issues with the markdown parser, and I still feel that GFMD would solve a lot of these issues (its territory well traveled)

**Comment by arosales** [comment]
We are seeing this in a few places now, any ideas on how we can fix this?

-thanks,
Antonio

**Comment by anthonydillon** [comment]
Our supported markdown syntax for code blocks and code are as follows.

To produce a code block, simply indent every line of the block by at least 4 spaces or 1 tab. For example, given this input:

```
This is a normal paragraph:

    This is a code block.
```

Will generate:

``` html
<p>This is a normal paragraph:</p>

<pre><code>This is a code block.
</code></pre> 
```

To include a literal backtick character within a code span, you can use multiple backticks as the opening and closing delimiters:

```There is a literal backtick (`) here.```

Will produce this:

``` html
<p><code>There is a literal backtick (`) here.</code></p>
```

The code blocks need to be wrapped in a `pre` tag to show new lines so the above juju commands should be tabbed instead of ticked. We should document this syntax for charmers to reference or could move to GitHub style markdown.

**Comment by mbruzek** [comment]
Thanks @anthonydillon for comment. I think we must respect new lines **with in** the multiple backtick blocks. The reason I opened this bug is because I believe the Canonical process is not displaying/rendering the markdown correctly. 

Markdown source:
![screenshot from 2016-06-07 10-32-48](https://cloud.githubusercontent.com/assets/6385185/15864148/81ba3372-2c9b-11e6-8079-98b1213f1e64.png)

File rendered on the Charm Store:
![screenshot from 2016-06-07 10-32-38](https://cloud.githubusercontent.com/assets/6385185/15864154/87528f78-2c9b-11e6-8592-8e470addb6e7.png)

In the [README.md](https://jujucharms.com/u/mbruzek/kubernetes/trusty/5) I expected to see the different commands on their own line and they have all newlines (view source [here](https://api.jujucharms.com/charmstore/v5/~mbruzek/trusty/kubernetes-5/archive/README.md)) removed because this is what I saw on Markdown preview tools when I was writing the file.

The three backticks allow authors to specify which language the code block is, so syntax highlighting works better for many cases where we want to display code.

I can fix my README.md to the other code block style, but the charm store has many different authors who may have used the three backtick method (which is completely valid in markdown). We must display these blocks as the authors expected, and can not ask them to re-write their files using the other block style.

**Comment by mbruzek** [comment]
I believe the way we render this will be a problem for anyone who puts code in the three backtick code blocks.  Example: https://gist.github.com/anonymous/f98f024db6e9bab0732bb705e2a630db
Click on RAW to view the Markdown source.

**Comment by ryan-beisner** [comment]
We have README.md files which render correctly on github, but squash newlines within the triple backtick code blocks on the charm store.  Is there an ETA for resolving this, or should we be updating mds in a special way so that the cham store will also render them as expected?

**Comment by frankban** [comment]
This is done, we now support github markdown extensions.

**Comment by ryan-beisner** [comment]
Woot, thanks :+1:

**Comment by BokaiChen-Pony** [comment]
`test\new line`

**Comment by BokaiChen-Pony** [comment]
`test
next line
third line`
