### ISSUE TITLE
Provide aggregate download counts across all charm series

### ISSUE THREAD

**Issue by async-security-team** [canonical/jujucharms.com#277]
If I search for a hot charm like Keystone, and click on the the first hit, it takes me here:

  https://jujucharms.com/keystone/xenial/1

That shows only 32 deploys, which is not really representative:

  29,981 https://jujucharms.com/keystone/trusty/1
           1 https://jujucharms.com/keystone/precise/1

Could we instead say something equivalent to:

  32 deploys (of 30,014 all-time)

**Comment by urosj** [comment]
Downloads are no longer shown.

**Comment by kikoreis** [comment]
This kind of doesn't help at all.

**Comment by urosj** [comment]
Sorry, this was poorly handled. I've closed this issue as the downloads are currently not shown. We're working on another iteration of UX on how to better show the revisions and download stats.
