### ISSUE TITLE
No way to browse for a charm's distroreleases 

### ISSUE THREAD

**Issue by async-security-team** [canonical/jujucharms.com#278]
If I visit

  https://jujucharms.com/keystone/
  https://jujucharms.com/keystone/xenial/

I don't see an obvious way of navigating to the trusty and precise versions of that charm beyond hacking the URL.

**Comment by Lucapaulina** [comment]
The series section is missing from the page and a work item has been created to add it. @anthonydillon

**Comment by anthonydillon** [comment]
Thanks, will add this shortly.

**Comment by anthonydillon** [comment]
This is in fact the correct to display keystone as a single series charm is not a multi-series charm. If this was a multi-series charm like [Ubuntu](https://jujucharms.com/ubuntu/) it would display the series below the description.
