### ISSUE TITLE
Design: Remove redundant 'Readme' title

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#279]
Every README.md starts with a title itself (# Name of Charm), so the explicit "Readme" title being generated is poor design. 

![readme-design-problems](https://cloud.githubusercontent.com/assets/5455357/15518289/d0f44624-21c1-11e6-8019-2e8a4a49f891.png)

**Comment by adam-stokes** [comment]
Can we get an acknowledgement on this issue?

**Comment by anthonydillon** [comment]
Sorry for the delay Adam. Are you suggesting we removed the Readme title?
The example in the image doesn't not have a name of charm title at the
beginning.

**Comment by adam-stokes** [comment]
I think the original suggestion was to remove the actual name of the readme, in this case 'Readme'

**Comment by anthonydillon** [comment]
Thanks for clarifying @battlemidget. I will pass this on to our use
experience team to confirm. @lucapaulina

**Comment by ghost** [comment]
@battlemidget correct. Reading through the Charm store I noticed this as a potential UI smell.

**Comment by ghost** [comment]
An alternative solution could be to keep the Readme header, but distinguish it from the Readme content. Consider something like Bootstrap panels.

![panels](https://cloud.githubusercontent.com/assets/5455357/15765670/00a5ec32-28fd-11e6-8924-4c58c48406a0.png)

**Comment by Lucapaulina** [comment]
I think the issue here is type hierarchy. In the new design which is implemented in demo.jujucharms.com you can see the new type styles. I'm not sure removing the title "Readme" solves much, as it's something users scan for while scrolling down the page.

![image](https://cloud.githubusercontent.com/assets/5873394/15784088/d9d3076e-29a8-11e6-861d-b1ed306ad2ad.png)

**Comment by adam-stokes** [comment]
I guess I don't understand why you need to say this is a 'Readme' rather than just displaying the readme information as part of the page.

**Comment by anthonydillon** [comment]
I agree, simply displaying the README content is 'README' enough.

Other stores like NPM simply display the README as the page content without
titling it README.

**Comment by jrwren** [comment]
Alternatively, github clearly shows that the content you are seeing is the
readme. It is headed by README or README.md in a bootstrap like title
(thanks Andy)  and the content is framed:
https://github.com/juju/charmstore

**Comment by adam-stokes** [comment]
This is true, however, with github.com you are obviously browsing a listing of files so the title of the filename makes more sense here.

**Comment by ghost** [comment]
![charmstore-juju-gui-framedtitle](https://cloud.githubusercontent.com/assets/5455357/15840169/aeab3202-2c0d-11e6-9e1d-e0ea5c409656.png)

**Comment by ghost** [comment]
![charmstore-juju-gui-notitle](https://cloud.githubusercontent.com/assets/5455357/15840173/b859397a-2c0d-11e6-95d7-98e1fcd3c5ad.png)

**Comment by ghost** [comment]
Tangentially related;do we even need a Description header? Doesn't the README solve the design problem of introducing the charm to new users? 

I understand the desire for uniformity in the charm store, but it seems forced and slightly redundant.

**Comment by Lucapaulina** [comment]
Let's remove the "Readme" title
