### ISSUE TITLE
Search box is not obvious on landing page

### ISSUE THREAD

**Issue by axw** [canonical/jujucharms.com#28]
I find the search box washes out over the laptop image on the landing page, and is not immediately obvious. On more than one occasion I've had to look around for it, rather than immediately knowing where to go. Screenshot attached:

![image](https://cloud.githubusercontent.com/assets/843579/5387746/1efd7e5c-811a-11e4-95eb-e9be3f21ab06.png)

My resolution is at 2560x1440, if it helps. IMO, it's much easier to spot at lower resolution/window scaling when the bar does not overlap the laptop image.

**Comment by mitechie** [comment]
Marking this as fixed release with the new header the search button is redesigned. Please reopen with feedback if you disagree.

**Comment by axw** [comment]
@mitechie @Lucapaulina Thank you, much more eye-catching to me.
