### ISSUE TITLE
Can't login to jujucharms.com

### ISSUE THREAD

**Issue by buggtb** [canonical/jujucharms.com#280]
Hi guys

If I try and login to jujucharms.com and I just get 

"Sorry for the inconvenience, please pop back soon."

My USSO login is fine, so its something else. A while ago someone tweaked the DB for me because I changed LP names, I guess its probably related!

login email: tom@analytical-labs.com
LP name: spicule

**Comment by huwshimi** [comment]
Interestingly when I log in I don't get the error message, but it also doesn't show me as being logged in.

The USSO page shows something about being in read-only mode, I wonder if this is somehow related.

**Comment by huwshimi** [comment]
This appears to be resolved for me now. @buggtb could you confirm and see if this is still not working for you?

**Comment by buggtb** [comment]
Still not working. Thanks @huwshimi !

**Comment by buggtb** [comment]
Resolved over on https://github.com/juju/charm-tools/issues/211
