### ISSUE TITLE
Tags not formatted correctly in preview of bundle

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#281]
![image](https://cloud.githubusercontent.com/assets/51892/15609310/4d941740-23ed-11e6-83d0-50e240030ea7.png)

Visiting https://jujucharms.com/u/conjure/ and clicking either autopilot or openstack-novalxd to see the preview of the bundle the tags are listed as ['conjure-openstack', 'autopilot', 'landscape']. I imagine we want to drop the brackets and quotes.

**Comment by frankban** [comment]
Indeed, we surely need to avoid just printing the Python list.

**Comment by Lucapaulina** [comment]
There is also an issue with the visualisation. We really need to think of a
way to place the services on the canvas without them making a diagonal line.

**Comment by urosj** [comment]
No such user.

**Comment by adam-stokes** [comment]
What does no such user mean? You have the screenshot right here..

**Comment by anthonydillon** [comment]
Looks like this has been solved. I see:
![spells juju](https://cloud.githubusercontent.com/assets/1413534/18609984/78cfcdc8-7d07-11e6-847f-f9b47ab94619.png)

@battlemidget Do you see something different?
