### ISSUE TITLE
charm revoke removing results of bundles in other namespaces

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#287]
There are 2 bundles that are almost identical but separated by namespaces:

https://jujucharms.com/observable-kubernetes/bundle/0
https://jujucharms.com/u/conjure/observable-kubernetes/bundle/1

When I search for a particular tag `conjure-kubernetes` it shows 2 results listed above. However, when I run

```
charm revoke ~conjure/bundle/observable-kubernetes-1 everyone
```

Meaning I only want ~conjure/observable-kubernetes-1 removed from public view it actually removes both bundles from the search results! Note that I do _want_ ~containers/observable-kubernetes showing up in the results list.

https://jujucharms.com/q/?tags=conjure-kubernetes

**Comment by frankban** [comment]
Moved to https://github.com/juju/charmstore/issues/636
