### ISSUE TITLE
docs search is confused when searching from devel

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#288]
I was in the devel docs and searched for the term "http_proxy" and I get back two pages for "General configuration options" however one of them is not a real page. It's also using the /master in the url vs /devel? 

https://jujucharms.com/docs/master/config-general/ - no load
https://jujucharms.com/docs/master/models-config - loads but url looks off now

If I do this search from the stable version of the docs all is well and I get one result for "General configuration options" that loads fine. 

https://jujucharms.com/docs/1.25/config-general

**Comment by frankban** [comment]
This issue has been fixed.
