### ISSUE TITLE
Bundles page is broken if the bundle has no readme

### ISSUE THREAD

**Issue by hatched** [canonical/jujucharms.com#289]
See the content under the bundle vis: https://jujucharms.com/u/hatch/large-ghost/bundle/1

**Comment by frankban** [comment]
Note that the bundle has an empty readme, so technically it's a valid bundle.

**Comment by frankban** [comment]
@anthonydillon are you still planning to fix this?

**Comment by anthonydillon** [comment]
I'll free it up for anyone to take this one.
