### ISSUE TITLE
Unstyled 502 error for ingesting charm instead of nice 404

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#29]
When a charm is newly promulgated, accessing the URL for it gives a bland black and white text "502 Bad Gateway
The server returned an invalid or incomplete response."  response. It should be 404 and look pretty (or 200).

e.g. https://jujucharms.com/percona-cluster/trusty/

**Comment by mitechie** [comment]
ty for the report

**Comment by sparkiegeek** [comment]
Well I can't figure out the conditions that cause this 502, it's still happening for Percona, so I guess we can rule out it being somehow associated with ingesting.

**Comment by mitechie** [comment]
I've got a traceback from it. It's due to the data being partially loaded I think. We've got it lined up for the next release atm. We just need to be more defensive in our coding.
