### ISSUE TITLE
Promulgated charms should SEO higher than non-promulgated charms

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#292]
Currently, https://www.google.com/search?q=juju%20apache-kafka returns https://jujucharms.com/u/bigdata-dev/apache-kafka/trusty/3 as the first result, when https://jujucharms.com/apache-kafka/trusty/ should definitely rank higher.

Obviously, this will depend on which and how specific charms are referenced externally, but anything we can do to boost promulgated charms' SEO over unpromulgated would be good.

For instance, with the new promulgation, push, and publish workflow, direct links to the namespace of a promulgated charm (e.g., https://jujucharms.com/u/bigdata-charmers/apache-kafka/trusty/ is promulgated as cs:trusty/apache-kafka) should include a canonical URL link to the promulgated page (i.e., https://jujucharms.com/apache-kafka/trusty/ in this case).  This will keep search results accurate even if a charm changes maintainership.

**Comment by urosj** [comment]
@johnsca We have an update to fix this on staging and it will get on production on Monday.
