### ISSUE TITLE
Take JuJu For a Spin on Ubuntu 16.04 / Owncloud / "juju: command not found" 

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#294]
Breezed through first four instructions of JuJu Owncloud installation at webpage [](https://jujucharms.com/get-started).  I was at the 5th step to "Take JuJu For a Spin by Deploying Mediawiki" and received the error "juju: Command Not Found".  I previously installed VirtualBox thinking it would somehow be needed. Although I'd like to use JuJu, since it sounded appealing, I appreciate any help, keeping in mind I am a novice Linux user. I desperately want to get this own-cloud server working.  I tried installing Ubuntu Server 16.04 previously but failed miserable after entering 5 pages of instructions and getting hung up on one instruction that didn't produce positive results so I aborted and reverted to Ubuntu 16.04 Client. I am searching for thorough and precise instructions to setup OwnCloud Server 9.0 or 9.1, whichever you suggest?  I appreciate any help immensely.

Tim
[](http://www.stoptheglobalists.com)

**Comment by AdamIsrael** [comment]
Hi Tim,

Let me see if we can't get you up and running with Juju.

If you're running OS X, I recommend the [Vagrant Juju Workflow](https://jujucharms.com/docs/stable/howto-vagrant-workflow), using trusty. 

If you're running Ubuntu 14.04, the [getting started guide](https://jujucharms.com/docs/stable/getting-started) has the steps to follow.

If you're running Ubuntu 16.04, this [getting started guide](https://jujucharms.com/docs/devel/getting-started) will get you up and running with the latest beta version of Juju 2.0.

Once that's done, verify that Juju is installed by running `juju version`. If the above doesn't work, please let me know more about your environment (OS, version, etc).

As far as OwnCloud goes, the current charm is outdated and broken, but I am looking to see what needs to be done to fix it so you can give it a spin.

**Comment by frankban** [comment]
Thanks for reporting a documentation issue!
Closing as this does not seem to be a bug in jujucharms.com.
