### ISSUE TITLE
nova-hyperv charm (win2012hvr2 series) doesn't show up in charmstore

### ISSUE THREAD

**Issue by jhobbs** [canonical/jujucharms.com#295]
I have a hyperv charm published in the charm store but it doesn't show up on the team's page.

> ubuntu@doberman-dev:~/oil-charms/nova-compute-vmware$ charm list -u oil-charms
> cs:~oil-charms/trusty/nova-compute-vmware-0
> cs:~oil-charms/win2012hvr2/nova-hyperv-0
> 
> ubuntu@doberman-dev:~/oil-charms/nova-compute-vmware$ charm publish cs:~oil-charms/win2012hvr2/nova-hyperv-0
> url: cs:~oil-charms/win2012hvr2/nova-hyperv-0
> channel: stable
> warning: bugs-url and homepage are not set.  See set command.

It doesn't show up here though:
https://jujucharms.com/u/oil-charms/

**Comment by lazypower** [comment]
@jhobbs did you set the ACL on the charm as well?

```
charm grant ~oil-charms/nova-compute-vmware --acl=read everyone
```

As a member of the oil-charms team, you should have seen it in the listing regardless, unless you weren't logged in.

**Comment by jhobbs** [comment]
@chuckbutler thanks - I did not do that, but I could see my other charms and not this one. I've done that now and it doesn't make a difference - it still doesn't show up (though everyone should be able to see the other charms there now).

**Comment by fabricematrat** [comment]
@jhobbs a small issue with our series validation and the regexp we used, should be fixed in next release.
