### ISSUE TITLE
Search results output is inconsistent regarding counts

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#297]
"Your search for ‘mongodb’ returned 3 results" but I seem to be short one in the actual results list. 

![selection_001](https://cloud.githubusercontent.com/assets/75915/16153937/9e078326-3476-11e6-88d0-3b9ce0573515.png)

**Comment by urosj** [comment]
Was this on staging? I see 2 results. Might be a cache issue. Will track it.

**Comment by mitechie** [comment]
Yes, staging has text at the top that says 3 results, but there are only
two listed.
