### ISSUE TITLE
bundle graph is incorrect for some bundles

### ISSUE THREAD

**Issue by mikemccracken** [canonical/jujucharms.com#298]
Some bundles (apparently ones with no gui annotation?) show up with a non-sensical graph, where all services are just shown as connected in a line, where the relations shown make no sense.

Here's an example:

![image](https://cloud.githubusercontent.com/assets/1768106/16201354/d0532082-36c5-11e6-8ff3-782c971aec62.png)

**Comment by frankban** [comment]
Link to the page with the problem: https://jujucharms.com/u/conjure/openstack-novalxd
@makyo could you please take a look?

**Comment by frankban** [comment]
IIRC this problem has ben fixed. If any other bundle si found showing this issue please feel free to reopen.
