### ISSUE TITLE
Contextual bar on solutions has border

### ISSUE THREAD

**Issue by anthonydillon** [canonical/jujucharms.com#3]
The contextual bar has a bottom border but on the solutions page it makes it look disjointed.
![solutions-contextual-bar-remove-border-bottom](https://cloud.githubusercontent.com/assets/1413534/5142652/70454fc6-717d-11e4-9bf0-b8089b7de256.png)

**Comment by urosj** [comment]
@anthonydillon Could you check the new one at https://jujucharms.com/solutions 
Seems ok to me, but you know better how it should look like.

**Comment by anthonydillon** [comment]
@urosj The issue is still there. There is a 1 pixel gap between the orange link and the dark grey banner.
![solutions-juju-gap](https://cloud.githubusercontent.com/assets/1413534/5201307/36d38c82-7568-11e4-97a6-6374ec56d78e.png)
