### ISSUE TITLE
Search results show duplicate entries

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#30]
I search for "hadoop" and the results return two Trusty version. See attached screen shot.

![hadoop-duplicate](https://cloud.githubusercontent.com/assets/1707853/5481227/bb7a93d2-860b-11e4-9224-c3b560e40942.png)

**Comment by mitechie** [comment]
Thanks, this is a failure in the back end api that we've landed a fix for but didn't make this release but will be in the next one. We've got a longer term model update to the api back end that will be worked on as well.

**Comment by lazypower** [comment]
In addendum this also results in a 502 bad gateway error when clicking through on freshly promulgated charms, such as fail2ban. https://jujucharms.com/fail2ban/trusty/1

**Comment by mitechie** [comment]
That fix is also part of the comitted. We're building our deployment today and hopefully will get it through either today or tomorrow based on webops availability.
