### ISSUE TITLE
Charm store not showing charms :-(

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/jujucharms.com#300]
When trying to access a charm in my teams namespace-> http://imghub.org/image/B6cP

$ charm show cs:~dhc/whelp-20 --> http://paste.ubuntu.com/17609243/

$ `charm list` shows it -> http://paste.ubuntu.com/17607650/   

CLI seems to be making successful transactions, just not the charm store website.

**Comment by fabricematrat** [comment]
@jamesbeedy 

I think your charm is private reading the output :

perm:
  Read:
- dhc
  Write:
- dhc

So only you can see it.

As it is not published (published:
  Info: []), you will have to login first then go to https://www.jujucharms.com/u/dhc/whelp/20

It won't appear in search result either for noone.

It will be only listed in your account page once login.

**Comment by mitechie** [comment]
Fabrice, James demonstrated how he was logged into the website and had
attempted numerous logout/login attempts.

**Comment by urosj** [comment]
@jamesbeedy @mitechie The image shows 404 as the URL tried to resolve a published (in stable channel) charm. The only way to access the non-published charm is to state revision. Once the charm is published it should be available without defining the revision number. 

Closing the issue for now, but if the problem persists and charm details are not available by specifying a revision or publishing a charm, we should reopen it.
