### ISSUE TITLE
"user" page shows unpublished charms

### ISSUE THREAD

**Issue by merlijn-sebrechts** [canonical/jujucharms.com#301]
Charms that have no published revisions show up on the user page. Clicking on the charm causes a 404 since the charm is unpublished.

to reproduce:

```
charm push xyz
charm grant cs:~user/series/xyz everyone --channel unpublished
```
- Surf to https://jujucharms.com/u/user
- click on xyz

I don't think unpublished charms should show up on the user page.

**Comment by fabricematrat** [comment]
closed as a duplicate #299
