### ISSUE TITLE
README.md doesn't render '>' as blockquote

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#302]
I'm trying to get a blockquote styled correctly in my charm README.md (search for 'quickstart'):

https://api.jujucharms.com/charmstore/v5/~bigdata-dev/trusty/pig-4/archive/README.md

Github markdown says i should be able to use '>' to get a blockquote, but that's not being styled.  Here's an example (again, search for 'quickstart'):

https://jujucharms.com/u/bigdata-dev/pig/trusty/4

**Comment by lazypower** [comment]
related to #228

**Comment by kwmonroe** [comment]
This doesn't look fixed to me:

https://jujucharms.com/u/bigdata-dev/pig/trusty/4

All the strings beginning with "Note:" are prefixed by '>' in the README.md, but they are not block-quoted in the charm store rendering.  @urosj would you please reopen this?

**Comment by anthonydillon** [comment]
This is causing a rendering issue. Reopening and raising priority.
