### ISSUE TITLE
"Featured Search" on demo.jujucharms.com references very old Hadoop charm

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#303]
Not sure if this issue belongs here on on [juju-gui](https://github.com/juju/juju-gui/issues), but the "Featured Search" that comes up when adding a charm on [demo.jujucharms.com](https://demo.jujucharms.com/) (and presumably any instance of the GUI) recommends a very old [Hadoop charm](https://jujucharms.com/hadoop/).  (In fact, we plan to unpromulgate this charm soon, as it is not maintained.)  Instead, the [hadoop-processing bundle](https://jujucharms.com/hadoop-processing/) should be recommended.

**Comment by anthonydillon** [comment]
Thanks for the heads up Cory. This is intact a Juju GUI issue. I have replicated this issue on the GUI project. https://github.com/juju/juju-gui/issues/1796
