### ISSUE TITLE
Relations search returns record which 404's

### ISSUE THREAD

**Issue by hatched** [canonical/jujucharms.com#304]
https://jujucharms.com/docs/search/?text=relations&version=master

Returns an item "Defining relationships in Juju" with a link https://jujucharms.com/docs/master/charms-relationships/ which 404's

**Comment by anthonydillon** [comment]
I wonder if the results are respecting the version filter as "Defining relationships in Juju" is only available in version 1.25.

**Comment by hatched** [comment]
Here is another I came by today: 
https://jujucharms.com/docs/search/?text=storage&version=master

The very first result "Storage support" 404's
https://jujucharms.com/docs/master/storage

**Comment by evilnick** [comment]
No, the results don't seem to be respecting anything. Some of them reference pages which were deleted over two months ago.  see also #286

**Comment by mitechie** [comment]
Hit this again today: 

Searched for maas in the devel docs and the first link is a 404. 

https://jujucharms.com/docs/search/?text=maas&version=master

The fulltext engine isn't filtering it appears.
