### ISSUE TITLE
It's not possible to select text in search results

### ISSUE THREAD

**Issue by hatched** [canonical/jujucharms.com#305]
https://jujucharms.com/docs/search/?text=relations&version=master

When trying to select any of the text in the returned items it tries to drag a link instead.

**Comment by anthonydillon** [comment]
I would suggest we move the link to just the title of the result instead of over the whole row to all the text to be highlight-able? @spencerbygraves

**Comment by urosj** [comment]
@anthonydillon I'd argue that the main usage of the search results are to get to the full page, not copy-paste. Let's leave it as it is.
