### ISSUE TITLE
download archive button should name the zip after the charm name. 

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#306]
I downloaded the apache2 charm to do a local deploy and got a file "archive.zip". Then I downloaded another charm and got "archive 1.zip"

The zips should be named after the charm name so I would end up with apache2.zip and mysql.zip

**Comment by frankban** [comment]
This is due to missing Content-Disposition header on the charm store size.
Moved to https://github.com/juju/charmstore/issues/650
