### ISSUE TITLE
Searching for exact matches yields no results.

### ISSUE THREAD

**Issue by marcoceppi** [canonical/jujucharms.com#307]
I recently performed the following search terms:
- `expeto-sgw`
- `expeto`
- `sgw`

Expecting to find something useful, with zero relevant results. The goal was to find https://jujucharms.com/u/brianlbaird/sgw/trusty or really anything in the brianlbaird user space as it's all expeto.

**Comment by urosj** [comment]
We don't show community charms any more if some curated exist.
