### ISSUE TITLE
Charm links to trusty and xenial are the same, and default to xenial

### ISSUE THREAD

**Issue by panlinux** [canonical/jujucharms.com#312]
Hi,

Look at the charms in this list:
https://jujucharms.com/u/landscape-charmers/

In particular, glance-simplestreams-sync: it has a trusty and a xenial link. But both links point at the same thing: https://jujucharms.com/u/landscape-charmers/glance-simplestreams-sync

That target defaults to xenial and there is no mention of trusty or a way to select the ubuntu series.

Let's say you clicked on the trusty link, and then copied and pasted the "Add to demo" test. You would be deploying the xenial version of the charm.

**Comment by frankban** [comment]
Tracked at https://github.com/CanonicalLtd/jujucharms.com/issues/336
