### ISSUE TITLE
Configuration description is multi-line

### ISSUE THREAD

**Issue by digitalresistor** [canonical/jujucharms.com#314]
I have a configuration description that is multi-line because it describes what the format of the configuration string is supposed to be, and includes an example.

This is being rendered as a single string on the charm store thereby making it much more difficult to understand what configuration is required for the charm.

**Comment by anthonydillon** [comment]
Thanks @bertjwregeer. Could you please link me to your charm that requires multi line formatting to help deliver a fix.

**Comment by digitalresistor** [comment]
@anthonydillon My apologies for not linking to a charm:

https://jujucharms.com/u/bertjwregeer/staticroutes

I noticed it when I published my Charm today.
