### ISSUE TITLE
Very old, very deprecated kubernetes formation listed on the front of /store as featured

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#315]
Visiting the store URL:
[https://jujucharms.com/store](https://jujucharms.com/store)

I am greeted with a very old deployment formation for Kubernetes. This has been deprecated since Feb 2016, when we did the re-architecture to a single Kubernetes charm. Shouldn't this point to a promulgated bundle?

It looks like the design may have been based on that older bundle, and it simply crept into the final design piece. 

For clarity, it should link to:

[Observable Kubernetes](https://jujucharms.com/observable-kubernetes/)

**Comment by anthonydillon** [comment]
Thanks for the heads up @chuckbutler. I will update this right away.

**Comment by lazypower** [comment]
Thanks @anthonydillon for the quick turn around.
