### ISSUE TITLE
juju.ubuntu.com DNS entries and URL redirects broken

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#317]
At some point juju.ubuntu.com stopped resolving. We have marketing materials and a bunch of links to Juju documentation around the web that references this URL. For example:

https://juju.ubuntu.com/docs/howto-node.html

should just reditect to 

https://jujucharms.com/docs/stable/howto-node

**Comment by urosj** [comment]
This should be handled by juju.ubuntu.com maintainers.
