### ISSUE TITLE
"Readme" on charm pages is redundant and clutter-y

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#318]
We should just cut out the "we're putting the readme here" header on the charm pages and just render the markdown since it's user-facing: 

![certificate authority juju - google chrome_009](https://cloud.githubusercontent.com/assets/1264109/17180366/2e6f7602-53ea-11e6-912d-fb0a780c83ae.png)

**Comment by anthonydillon** [comment]
For what it's worth I agree. Once we have feedback from design, action can
be taken.

**Comment by Lucapaulina** [comment]
Go for it.

**Comment by anthonydillon** [comment]
This has landed.
