### ISSUE TITLE
Docs aren't updating/generating new pages

### ISSUE THREAD

**Issue by marcoceppi** [canonical/jujucharms.com#32]
https://juju.ubuntu.com/docs/config-onlinelabs.html

https://jujucharms.com/docs/config-onlinelabs

**Comment by mitechie** [comment]
Thanks for the report. We'll get right on checking why the cron update is failing.

**Comment by mitechie** [comment]
We thought this was fixed but it worked locally but not on prodstack. We'll be rolling another release right away with a new patch that has been tested to work on prodstack asap.

**Comment by arosales** [comment]
FYI, we still aren't see updates to jujucharms.com docs. Specifically the onlinelabs bits. I suspect there are other MPs that are still pending too.

-thanks,
Antonio

**Comment by mitechie** [comment]
It's fix-committed and we're working on a release to get the fix out to the prod site. We started the release but hit a snag and now we're going to hit a friday no-release day. We'll be working to get it to staging.jujucharms.com today though and QA the fix works properly.

**Comment by mitechie** [comment]
We believe this is fixed but will watch for the first update to the docs to make sure it's fully auto regenerating as required.

**Comment by evilnick** [comment]
when does the cron job fire? Useful to know when updates should be expected to go live

**Comment by fabricematrat** [comment]
@evilnick The cron job is every 15 minutes but the pages are cached for one hour, so you will see the changes after 1h15min.

**Comment by evilnick** [comment]
thanks!
