### ISSUE TITLE
search box jumps around

### ISSUE THREAD

**Issue by natefinch** [canonical/jujucharms.com#320]
(I'm on a 30" monitor at 2560x1600)

When I get to the charm store, the search box is off to the right of the screen. When I click on it, it slides out to the approximate center of the screen.  My focus is over on the right of the screen, and now I have to move it over to the center of the screen... check and see if where I meant to click is where I actually did, etc..  

This is especially annoying if I'm trying to edit a previous search, because I'll try to click in the middle of the word where I typoed, and then the box jumps 12" across my screen, and it's hard to tell if the cursor is now between the two letters where I tried to put it.

Moving an input box right when I click on it is perhaps the worst time to ever move a box... though I guess second to moving it just before I click on it.

**Comment by anthonydillon** [comment]
Thanks @natefinch. This was a concern when designing the search interaction. It maybe worth design taking another look at this component.

**Comment by spencerbygraves** [comment]
Thanks @natefinch We will look at a narrower search for big screens in our next design iteration.

**Comment by spencerbygraves** [comment]
We have agreed on a design update for this, which can be seen here:

https://github.com/CanonicalLtd/juju-design/issues/155

**Comment by hatched** [comment]
This issue has not yet been resolved, why was it closed @spencerbygraves ?

**Comment by spencerbygraves** [comment]
@hatched This was closed as we've agreed on a design which is over on juju-design:

https://github.com/CanonicalLtd/juju-design/issues/155

**Comment by hatched** [comment]
@spencerbygraves sure thing, we'll close the issue once it's been resolved.
