### ISSUE TITLE
author-* docs out of date

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#321]
See:

https://jujucharms.com/docs/2.0/authors-charm-writing

That's not based on layered charmming (which is the recommended way to write charms now).  Can we redirect that here?:

https://jujucharms.com/docs/2.0/developer-getting-started

**Comment by anthonydillon** [comment]
Thank you very much @kwmonroe. This issue has been ported to the juju-docs project as it is an issue the docs team should resolve.

**Comment by mbruzek** [comment]
@kwmonroe Was there a page on jujucharms.com that links to authors-charms-writing? Other than the docs themselves?

**Comment by lazypower** [comment]
@anthonydillon sorry to be dense, but i dont see a new issue for this on the docs issue-tracker here:

https://github.com/juju/docs/issues

I would like to propose this re-open until there is a bug x-reffing this issue.

**Comment by lazypower** [comment]
oh yeah, we work in open source, I can just do this myself ;) 

sorry for the noise.
