### ISSUE TITLE
deploy example copy-paste is wrong

### ISSUE THREAD

**Issue by dpb1** [canonical/jujucharms.com#322]
https://jujucharms.com/landscape-dense-maas/

It says to do this:

```
juju deploy landscape-dense-maas/1
```

But, juju deploy on beta-14 appears to only take -1 at the end, not /1.

**Comment by mitechie** [comment]
I think that the charmstore should use the -1 for now, but I also want to note this is something Juju is going to fix as well in a future beta per https://bugs.launchpad.net/juju-core/+bug/1584193.

I think in the case of this particular url that the charmstore should not include the revision number unless the url in the browser has the revision number. e.g. I'm looking at mysql/14 then the deploy command should be mysql-14.

**Comment by dpb1** [comment]
Agreed.  I think the copy and paste box should contain the version you are looking at -- including stripping the number by default to give you the 'latest'.
