### ISSUE TITLE
Revisions and dates

### ISSUE THREAD

**Issue by AdamIsrael** [canonical/jujucharms.com#323]
I'm finding that it's difficult to find information about the revisions (and the date they were published) of a charm or bundle. This makes it hard to know if I'm using a recent revision.

**Bundles**
Looking at a [bundle page](https://jujucharms.com/u/nfv/etsi-osm):
- the actual revision number is only visible in the textbox above the "Add to demo" button
- there's no way to see the date this revision was published
- there's no way to see if I'm looking at the most current revision
- there's no easy way to see what revision of a charm is included in the bundle

I think there needs to be a better call out to what the current revision is. I also think we need to see some form of revision history, with the revision number and date it was published.

The only way to see what revision of a charm is included in the bundle is to look at the url of each charm and infer from that.

I also think it would be nice to see here if the bundle is including charms that have newer revisions available. That's a flag, to me as a bundle maintainer, that I may need to publish a revised bundle to include the newer charms.

**Charms**

Looking at a [charm page](https://jujucharms.com/u/nfv/openvim-compute/2):
- the actual revision number is only visible in the textbox above the "Add to demo" button
- there's no way to see the date this revision was published
- there's no way to see if I'm looking at the most current revision

Mostly the same as issues as with the bundle page. I don't have a good window into what revision I'm looking at, how current it is, and how it's changed.

**Comment by anthonydillon** [comment]
Agreed we should do a better job of calling out the current revision number and if you are not on the latest revision details. I will pass this on to design to take a look and get a fix for this shortly.

**Comment by spencerbygraves** [comment]
Thanks @AdamIsrael We have plans to address this in some upcoming work on versions. You can see our work so far on charm channels here - https://github.com/CanonicalLtd/juju-design/issues/120

**Comment by Lukewh** [comment]
This should now be implemented.
