### ISSUE TITLE
storage examples using juju1 cli

### ISSUE THREAD

**Issue by stub42** [canonical/jujucharms.com#324]
https://jujucharms.com/docs/devel/charms-storage has lots of examples using commands like 'juju storage add' that no longer exist in Juju 2.0.

**Comment by anthonydillon** [comment]
Thank you very much @stub42. @evilnick could you please take a look at this?

**Comment by bac** [comment]
I've moved this issue to the juju/docs project. Thanks for filing it @stub42

**Comment by anthonydillon** [comment]
Thanks, closing as this is tracked in the docs project.
