### ISSUE TITLE
directions to bootstrap manual don't work

### ISSUE THREAD

**Issue by natefinch** [canonical/jujucharms.com#325]
from https://jujucharms.com/docs/stable/clouds-manual

`juju bootstrap mycloud manual/192.168.1.128`

except:

```
$ juju bootstrap -v mymanual manual/104.196.173.48
cloud "manual" not found, trying as a provider name
interpreting "104.196.173.48" as the cloud endpoint
ERROR loading credentials: credentials.google.nate: missing auth-type
```

I think you have to add-cloud first.... but I'm not 100% sure, and there's no help on how to do that with manual either.

**Comment by bac** [comment]
@natefinch reported he discovered a problem with his credential.yaml file that caused Juju to lose its mind. So it is a Juju problem but not a problem with the instructions.
