### ISSUE TITLE
juju adding machine  always stuck in pending state after successful bootstrapping 

### ISSUE THREAD

**Issue by romanyn** [canonical/jujucharms.com#326]
![image](https://cloud.githubusercontent.com/assets/21366595/18137066/431f4b4e-6fa7-11e6-81e9-c9fa328bda06.png)

please if anyone can help?
Thanks

**Comment by hatched** [comment]
@romanyn You'll have better luck asking on http://askubuntu.com/ or in #juju on freenode as this is the issue tracker for the jujucharms.com website, not for Juju support.
