### ISSUE TITLE
View all charms doesn't sort results 

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#329]

**Comment by urosj** [comment]
go to www.jujucharms.com
click on the "store" link
click "view all the charms". you will see 296 recommended charms when sorted by "most popular". The most popular is Ubuntu and mysql is about #20
change the sort option to "least popular" and there are only 294 charms. Where did the other two go?
switch sort option back to "most popular" and it shows 282 recommended charms (more disappeared), and it now shows mysql as the most popular, and the list no longer looks like it did when showing 296 recommended charms.

The proper way to show all charms is:
https://jujucharms.com/q/?type=charm&sort=-downloads

Also matching the queries by default, to show same number of results.

**Comment by frankban** [comment]
This seems to be fixed now (in the GUI). Please feel free to reopen if not.
