### ISSUE TITLE
Promulgated charm not showing up right on jujucharms.com

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#33]
I promulgated the mellanox charm last night and it is not showing up correctly on jujucharms.com

https://jujucharms.com/q/mellanox

There are two charms that show up with "No owner" and when I click on the first one I get a "502 Bad Gateway" error.  Clicking on the second one gets a "Page not found" error.

The branch in Launchpad is:  lp:~charmers/charms/trusty/mellanox/trunk

Please let me know if you need more information.  Thanks!

**Comment by mitechie** [comment]
Thanks, we're working with our team to get debug info. We cannot verify this in development but it's definitely an issue on production.

**Comment by mitechie** [comment]
The fact that there's two of them is a different bug captured in another ticket. Closing this one.
