### ISSUE TITLE
There is no "charm publish" command anymore

### ISSUE THREAD

**Issue by panlinux** [canonical/jujucharms.com#331]
The page at https://jujucharms.com/docs/stable/authors-charm-store talks about the `charm publish` command, but that command was replaced by `charm release` in 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2 which is currently in the stable juju ppa.

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. I have moved it to the documentation project.
