### ISSUE TITLE
Typo in Juju-Retry-Provisioning section

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#333]
There's a small typo in https://jujucharms.com/docs/2.0/charms-deploying#juju-retry-provisioning
page, in the given example, it mentions that "if juju status reports those 3, 27 and 57 could not be provisioned because of a 'rate limit' error, you can ask juju to retry" but in <pre>\ section of the wiki it mentions the command like : 

$ juju retry-provisioning 3 27 5

It should be 57 according to the example, not 5.

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this typo to us. Will pick this up this morning.

**Comment by anthonydillon** [comment]
This fix has been merged.
