### ISSUE TITLE
There's no information about destroying juju environment in charms-destroy page

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#335]
Hello,

There's no information about destroying juju environments in juju v2 charms-destroy document although there's a mention about "destroying environments" in the page title which is confusing :
https://jujucharms.com/docs/2.0/charms-destroy

And I know there's no `$ juju destroy-environment` anymore with the juju v2 but I believe people would want to destroy their juju environments still in v2.

I think `$ juju destroy-controller --destroy-all-models -y controller-name` should do the trick for v2.

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. I have moved it to the docs project here: https://github.com/juju/docs/issues/1374.
