### ISSUE TITLE
Different ubuntu series all link to the same one: xenial

### ISSUE THREAD

**Issue by panlinux** [canonical/jujucharms.com#336]
Hi,

I'm looking at the long charm list from https://jujucharms.com/u/openstack-charmers-next, searching for the rabbitmq-server one.

If you look at its row, it lists xenial, wily, vivid, trusty and precise as ubuntu series, but all of them have the same link to https://jujucharms.com/u/openstack-charmers-next/rabbitmq-server, which shows in the page the charm is "xenial".

I then looked at the metadata.yaml file, thinking this could be a multi-series charm, but that is not the case.

Many other charms in that list, of not all, show the same problem. The link is the same, regardless of ubuntu series.

**Comment by urosj** [comment]
Confirmed. 

This is problematic only on /u/:user profile pages, but not on search pages.

**Comment by Lukewh** [comment]
This no longer seems to be an issue. If incorrect please reopen and provide any more examples.
