### ISSUE TITLE
Mixed content warnings on some pages

### ISSUE THREAD

**Issue by mhilton** [canonical/jujucharms.com#337]
I see a mixed content warning on https://jujucharms.com/canonical-kubernetes/. This appears to be because the charm's README.md contains a link to a non-secure image.

**Comment by anthonydillon** [comment]
We could replace "http://" with "https://" when processing the Readme. That would fix this issue but may break some assets if not supplied with https.

**Comment by anthonydillon** [comment]
Do you think s/scr="http:/scr="https:/ would be sufficient to close this bug?
