### ISSUE TITLE
Replace observable-kubernetes with canonical-kubernetes

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#338]
http://jujucharms.com/store

Please replace the featured observable-kubernetes bundle with [canonical-kubernetes](http://jujucharms.com/canonical-kubernetes).

**Comment by anthonydillon** [comment]
The kubernetes section in the store has been replaced with the containers topics page link. The topics page does have canonical-kubernetes.

**Comment by anthonydillon** [comment]
This will be live with the next release of the site.

**Comment by bac** [comment]
Can can be previewed now at http://www.jujugui.org/store  <-- @castrojo
