### ISSUE TITLE
Listing all the files from a reactive charm is overwhelming and poor user experience

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#340]
An example charm built from reactive: https://jujucharms.com/u/adam-stokes/ghost

The file listing shows 86 files most of it being generated from a `charm build` using the reactive pattern.

It would be nice to clean this up so that the user either sees just the files that make up the charm in it's reactive layer form if applicable, or adds an additional tab to show the original layer files in additional to the existing file list. 

This is in reference to https://github.com/juju-solutions/charms.reactive/issues/83

**Comment by hatched** [comment]
How would you envision this working? As there isn't a guaranteed list of files that are generated by a reactive charm I don't see any way to filter this list that won't run the risk of inadvertently hiding user supplied vs generated files.

A simpler solution to this might simply be that we remove the file count from the file list. As a design or informational component I don't think it really serves any purpose anyways.

**Comment by anthonydillon** [comment]
Thanks for bringing this up. I'll bring it to design and UX team tomorrow.

**Comment by spencerbygraves** [comment]
We discussed this in our design workshop and decided to leave this as it is, because there is no way of knowing which files are important to each user. We also think the file count is useful to get an overview when they are collapsed.

**Comment by adam-stokes** [comment]
Whats the status on this now that it's reopened?

**Comment by spencerbygraves** [comment]
We've talked about it further. As we cannot separate supplied vs generated files, we will remove the file number so it's not overwhelming to the user. Thanks.

**Comment by johnsca** [comment]
Charms built from layers include a `.build-manifest` file that explicitly associates each file with a layer, although that is [currently being stripped out](https://github.com/juju/charm/issues/201).  The intention was to have the charm store use this information to only show the files relevant to the top-level charm layer, or perhaps even provide a UI to browse files per layer.

Edit: Example `.build-manifest` file: http://pastebin.ubuntu.com/23212789/
