### ISSUE TITLE
viewing by tag provides unrelated results

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#342]
Example: https://jujucharms.com/q/?tag=javascript, it does show my ghost charm but also shows a bunch of other applications that aren't tagged javascript.

**Comment by anthonydillon** [comment]
Hi @battlemidget the correct link should be: https://jujucharms.com/q/?tags=javascript. This does intact only return the ghost charm. How did you get to the URL `?tag=`?

**Comment by adam-stokes** [comment]
Going to https://jujucharms.com/ghost/0 and clicking the javascript tag under tags

![image](https://cloud.githubusercontent.com/assets/51892/18670717/3bc34202-7f0f-11e6-9228-3813565069e1.png)

**Comment by anthonydillon** [comment]
Thanks for the feedback. Will fix as soon as possible.

**Comment by anthonydillon** [comment]
This fix is now live
