### ISSUE TITLE
https://jujucharms.com/docs/2.0/reference-environment-variables include JUJU_MODEL

### ISSUE THREAD

**Issue by lutostag** [canonical/jujucharms.com#343]
In the docs, we should include a reference to JUJU_MODEL -- as from the man page:

```
JUJU_MODEL
              Provides a way for the shell environment to specify the current Juju model to use.  If the model is specified explicitly using -m MODEL, this takes precedence.
```

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. I have moved it to the juju docs project. Closing this one on this project.
