### ISSUE TITLE
yaml bundle with local charm not usable in juju 2.0

### ISSUE THREAD

**Issue by chz8494** [canonical/jujucharms.com#344]
Trying to use local charms to deploy private openstack cloud on juju 2.0.
I have a yaml file which previously worked with juju 1.25 perfectly. It has local charm defined as "charm: local:trusty/ubuntu-compute", but this doesn't work anymore with current juju 2.0 beta 18. It gives error as "ERROR cmd supercommand.go:458 cannot deploy bundle: cannot resolve URL "local:trusty/ubuntu-compute": unknown schema for charm URL "local:trusty/ubuntu-compute"
".

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. @hatched could you take a look please?

**Comment by jrwren** [comment]
Hello,

Local charms in 2.0 no longer require a series, nor is a local: prefix required.

See the 2.0 docs here: https://jujucharms.com/docs/stable/charms-deploying#deploying-from-a-local-charm

**Comment by chz8494** [comment]
I was trying to use a yaml bundle to deploy, the charm location is defined in that bundle, in a way like this:
openstack-phase1-nodes:
  series: trusty
  services:
    controller-node:
      charm: local:trusty/ubuntu-controller
      num_units: 3
      constraints: tags=controller
    compute-node-sriov:
      charm: local:trusty/ubuntu-compute-sriov
      num_units: 7
      constraints: tags=compute-sriov
    ntp:
      charm: local:trusty/ntp
      options:
        source: '192.168.x.x'
        auto_peers: true
  relations:
    - - ntp
      - [ controller-node, compute-node-sriov ]

and it works perfectly with juju 1.25 through juju-deployer.

besides this potential incompatible issue, I suspect there might be other amendments I need to change in my yaml bundle to make it be able to be deployed with juju 2.0 deploy command.

**Comment by hatched** [comment]
@anthonydillon it looks like this is not a GUI related issue but the bundle yaml is no longer valid for Juju 2 as mentioned by @jrwren

**Comment by chz8494** [comment]
@hatched @jrwren thanks for your help.
so what's the current solution for deploying bundle with local charms? I tried to search it from https://jujucharms.com/docs/stable, but it only shows example for deploying modified bundle with cs charms, not local charms, and https://jujucharms.com/docs/stable/howto-privatecloud shows "in progress"...

**Comment by bac** [comment]
Hi @chz8494,

For Juju 2, the bundle.yaml file must have a path to the local charm, like:

```
  openstack-dashboard:
    charm: ./repo/xenial/openstack-dashboard
    series: xenial
```

**Comment by chz8494** [comment]
@bac tried to change it 
 series: xenial
  services:
    controller-node:
      charm: local:./trusty/ubuntu-controller
      num_units: 3
      constraints: tags=controller
    compute-node:
      charm: local:./trusty/ubuntu-compute
      num_units: 2
      constraints: tags=compute

still errors:
invalid charm URL in application "controller-node": charm or bundle URL has invalid form: "local:./trusty/ubuntu-controller"
invalid charm URL in application "compute-node": charm or bundle URL has invalid form: "local:./trusty/ubuntu-compute"
invalid charm URL in application "ntp": charm or bundle URL has invalid form: "local:./trusty/ntp"

my bundle file is stored at ~/Openstack/charms, and controller charm's at ~/Openstack/charms/trusty/ubuntu-controller.

**Comment by bac** [comment]
The word "local" is not longer used as part of the charm line.

**Comment by chz8494** [comment]
@bac thanks buddy, it works. 👍 
series: xenial
services:
controller-node:
charm: ./trusty/ubuntu-controller
num_units: 3
constraints: tags=controller

16:26:32 DEBUG juju.cmd.juju.application bundle.go:251 added charm local:xenial/ubuntu-controller-1
16:26:32 INFO  juju.cmd.juju.application series_selector.go:101 with the series "xenial" defined by the bundle
16:26:32 DEBUG juju.cmd.juju.application bundle.go:363 application controller-node is deploying (charm local:xenial/ubuntu-controller-1)

**Comment by kcd83** [comment]
FYI as at juju 2.2.2 the GUI still exports in the form

```
  "hello-world": 
    charm: "local:xenial/hello-world-0"
```
Presumably it does not know what the directory was, but this is easy to change to a path as described above
