### ISSUE TITLE
The charmstore markdown renderer is not rendering properly.

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#347]
We pushed up a bundle.yaml to the charmstore https://jujucharms.com/canonical-kubernetes/2
The markdown is rendered incorrectly on the charm store, when compared to 3 other online markdown tools.
- https://jbt.github.io/markdown-editor/
- dillinger.io
- https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/6831ae04c8ca420f82a6cd4d33667efa99569353/README.md

I realize the renderer is not github flavored markdown, but the output on jujucharms.com look really bad and I have no idea what is wrong in the raw text file.

Here is the charmstore version. Please notice the rendering goes bad after the "conjure up" header.
![screenshot from 2016-09-26 15-41-14](https://cloud.githubusercontent.com/assets/6385185/18852414/e7bb7fac-8405-11e6-8f8a-a5a263c946ef.png)

Here is what the same section looks like in "dillinger.io" with the raw text and markdown side by side:
![screenshot from 2016-09-26 15-44-26](https://cloud.githubusercontent.com/assets/6385185/18852417/eae7d2fc-8405-11e6-9657-cb9b66540abd.png)

Here is what the section looks like in github.
![screenshot from 2016-09-26 15-46-02](https://cloud.githubusercontent.com/assets/6385185/18852418/ee4b581a-8405-11e6-80f3-3d2777740e2c.png)

**Comment by frankban** [comment]
Thanks for reporting this. We have some issues with our default markdown rendering, and I think we should add support for GFM. This issue has high priority for us.
