### ISSUE TITLE
Deploying the kubernetes-core bundle on jujucharms.com doesn't appear to work

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#349]
I've tried to deploy the canonical kubernetes bundle from the store via our prominent weblink

[The Canonical Distribution of Kubernetes](https://jujucharms.com/canonical-kubernetes/)

After clicking 'add to demo'  I was brought to the canvas, a message displaying it was fetching charms / information, and then nothing happened. A blank canvas greeted me.

I captured some WSS errors on the demo gui, I'm not sure if they are related to the bundle not being able to deploy.

![demo jujucharms com](https://cloud.githubusercontent.com/assets/246944/18897037/5391e55e-84ec-11e6-8a12-9df897de8934.png)

This is on Google Chrome Version 53.0.2785.116 (64-bit)

And the same behavior is illustrated on FireFox   49.0

![demo jujucharms com-ff](https://cloud.githubusercontent.com/assets/246944/18897131/fd1723fa-84ec-11e6-9b52-3ac9f086d4ff.png)

**Comment by hatched** [comment]
Thanks for reporting this bug @chuckbutler we are aware of it and will be releasing a new GUI which fixes this on Thursday.

Sorry for the inconvenience!

**Comment by anthonydillon** [comment]
The new GUI has been released and now works with kubernetes. Thank you for reporting this issue.
