### ISSUE TITLE
Code and pre blocks are not preformatted

### ISSUE THREAD

**Issue by marcoceppi** [canonical/jujucharms.com#350]
This means things are messy for READMEs with mutliple spaces.

Proposed change:

```
pre, code {
  white-space: pre;
}
```

Visible in the following screenshot

![screenshot from 2016-09-28 09-46-22](https://cloud.githubusercontent.com/assets/70613/18915864/720d5558-8560-11e6-858f-e52e117da195.png)

While this seems small, it impacts our README and hinders it's comprehension for Canonical Distribution of Kubernetes

**Comment by mbruzek** [comment]
I had expected the pre blocks to already do this. Please consider this request.

**Comment by fabricematrat** [comment]
We identify this issue already and we will work on it and deliver it soon.

**Comment by jrwren** [comment]
I think this is now deployed and fixed. Please reopen if this is still an issue.

**Comment by mbruzek** [comment]
Confirmed, our README looks to contain mono space text blocks. Thanks for the work on this!
