### ISSUE TITLE
No way to tell when a charm was most recently updated

### ISSUE THREAD

**Issue by jhobbs** [canonical/jujucharms.com#353]
There is no way to tell when a charm was most recently updated - no last updated timestamp, no log of changes. I would like to know if a charm I'm using is kept up to date or not.

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue. There should be an area on the right hand side of the charm details page which lists the revisions. Each revision has a date stamp. Does that help?

**Comment by jhobbs** [comment]
I don't see the list of revisions. For example:

https://jujucharms.com/u/openstack-charmers-next/tempest/xenial/

**Comment by anthonydillon** [comment]
The design team are working on surfacing the version number and highlighting if there is a newer version.

**Comment by frankban** [comment]
This is very similar to https://github.com/CanonicalLtd/jujucharms.com/issues/362
Please follow the deployment progress there.
