### ISSUE TITLE
Invalid charm URL when specifying series 

### ISSUE THREAD

**Issue by szeestraten** [canonical/jujucharms.com#354]
The link generator on the charm store generates an invalid URL for a charm when you specify the series.

Example: The [Trusty Ceph charm](https://jujucharms.com/u/openstack-charmers-next/ceph?series=trusty) from [openstack-charmers-next](https://jujucharms.com/u/openstack-charmers-next) generates the following output: 

```
juju deploy cs:trusty/~openstack-charmers-next/ceph-251
```

When trying to deploy using that charm URL, juju reports that is an invalid form:

```
zeestrat@hcc-admin9:~⟫ juju deploy cs:trusty/~openstack-charmers-next/ceph-251
ERROR charm or bundle URL has invalid form: "cs:trusty/~openstack-charmers-next/ceph-251"
```

Juju version: 2.0-rc1-xenial-amd64

**Comment by urosj** [comment]
Thans for the bug report, @szeestraten .

The link in jujucharms is wrong. https://jujucharms.com/u/openstack-charmers-next/ceph 

It should be "juju deploy cs:~openstack-charmers-next/trusty/ceph-251".

**Comment by szeestraten** [comment]
Sorry if I'm missing something, but I'm still hitting issue on jujucharms.com.

Is there an upcoming fix?

**Comment by anthonydillon** [comment]
Sorry this fix has landed and will be live with the next release of the site.
