### ISSUE TITLE
Link to Vagrant Workflow is broken on all but the 1.25 version of docs

### ISSUE THREAD

**Issue by szeestraten** [canonical/jujucharms.com#356]
The link under User Guide > How to > Vagrant Workflow is broken for all but the 1.25 version of docs.

**OK:**
https://jujucharms.com/docs/1.25/getting-started

**Broken:**
https://jujucharms.com/docs/2.0/howto-vagrant-workflow/
https://jujucharms.com/docs/stable/howto-vagrant-workflow/
https://jujucharms.com/docs/devel/howto-vagrant-workflow/

**Comment by anthonydillon** [comment]
Moved to the docs project.
