### ISSUE TITLE
Release notes only show for 1.x versions of Juju

### ISSUE THREAD

**Issue by szeestraten** [canonical/jujucharms.com#357]
The release notes are the same for all versions of the docs, however they only show release notes for 1.x versions of Juju.

**See:**
https://jujucharms.com/docs/stable/reference-release-notes
https://jujucharms.com/docs/devel/reference-release-notes
https://jujucharms.com/docs/2.0/reference-release-notes
https://jujucharms.com/docs/1.25/reference-release-notes

**Comment by evilnick** [comment]
The updates for all these have landed now
