### ISSUE TITLE
getting-started doesn't mention the required PPA on xenial

### ISSUE THREAD

**Issue by absoludity** [canonical/jujucharms.com#358]
Although the release email mentions the PPA, currently if you follow the instructions at:

https://jujucharms.com/docs/2.0/getting-started

(which doesn't currently mention the ppa) you get the xenial version which won't work with those instructions (different bootstrap arg order):

ubuntu@dev-xenial:~$ apt-cache policy juju
juju:
  Installed: 2.0~beta15-0ubuntu2.16.04.1
  Candidate: 2.0~beta15-0ubuntu2.16.04.1
  Version table:
 **\* 2.0~beta15-0ubuntu2.16.04.1 500
        500 http://nova.clouds.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0~beta4-0ubuntu2 500
        500 http://nova.clouds.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

ubuntu@dev-xenial:~$ juju bootstrap localhost lxd-test
ERROR unknown cloud "lxd-test", please try "juju update-clouds"

**Comment by evilnick** [comment]
The ppa instructions were added back in about 20 minutes ago, but thanks for being vigilant
