### ISSUE TITLE
Hard to see charm revision in the charm page

### ISSUE THREAD

**Issue by panlinux** [canonical/jujucharms.com#359]
https://jujucharms.com/u/openstack-charmers-next/rabbitmq-server/trusty

See attached screenshot. The only place where the charm revision is available is in the command line box, which is usually not wide enough to display it.

That box also has some quirks, at least in chrome, where you can't click on it and move the cursor easily all the way to the right. It insists on selecting everything, and if I hit the "end" key the page scrolls all the way to the bottom. I have to use the mouse cursor to select the text and drag to the right, then the content scrolls and I can see the revision at the very end.

I suggest to display the charm revision/version elsewhere in the page, maybe close to the charm name section.

![image](https://cloud.githubusercontent.com/assets/5117210/19388303/3b806a88-91f5-11e6-8734-c81865df2d3a.png)

**Comment by anthonydillon** [comment]
The design team are working on surfacing the version number and highlighting if there is a newer version.

There have been a number of issue relating to this one:
- https://github.com/CanonicalLtd/jujucharms.com/issues/323
- https://github.com/CanonicalLtd/jujucharms.com/issues/362

**Comment by anthonydillon** [comment]
This work has also been completed.
