### ISSUE TITLE
Windows download links

### ISSUE THREAD

**Issue by huwshimi** [canonical/jujucharms.com#36]
As we migrate away from jujucharms.com we need a new home for the Windows download info that is currently on https://juju.ubuntu.com/install/.

This page is currently linked to from https://jujucharms.com/get-started and https://jujucharms.com/docs/getting-started#windows

@Lucapaulina and @anthonydillon do either of you have any thoughts?

**Comment by anthonydillon** [comment]
I would suggest adding a windows installer section to jujucharms.com/get-started. What you think @Lucapaulina?

**Comment by Lucapaulina** [comment]
There is a link at the top of the page that takes the user to the windows install instructions. Do you both think we should expand on it in-page?

**Comment by mitechie** [comment]
@Lucapaulina the link points to juju.ubuntu.com which we're trying to deprecate away. On that page on juju.ubuntu.com there's really only a link to an exe and a note for the checksum of that exe. In talking with Huw I was thinking we could incorporate the windows instructions into the page in a really light weight way, but wanted to get some feedback from the masters.

**Comment by Lucapaulina** [comment]
@mitechie oh! I see. I'll add it as a work item and get Spencer to look at it. This will most probably be something that we can solve next week when we are all together.
