### ISSUE TITLE
Wrong command on https://jujucharms.com/docs/2.0/clouds-maas

### ISSUE THREAD

**Issue by davecore82** [canonical/jujucharms.com#361]
The following command is wrong on https://jujucharms.com/docs/2.0/clouds-maas:

Now you can create a Juju controller with the bootstrap command:
juju bootstrap prodmaas prodmaas-controller

It should be:

juju bootstrap prodmaas-controller prodmaas

**Comment by bac** [comment]
Thanks for raising the issue.  I've moved it to the documentation project referenced above.
