### ISSUE TITLE
Feature Request: Inform users there is a new version of a bundle/charm

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#362]
This is a feature request to inform users of a newer version of a charm or bundle when looking at a previous version. For example, if I am viewing:
https://jujucharms.com/u/bigdata-charmers/kafka-ingestion/0
let the user know there is:
https://jujucharms.com/u/bigdata-charmers/kafka-ingestion/1

-thanks,
Antonio

**Comment by anthonydillon** [comment]
Thanks Antonio,

The design team are working on surfacing the version number and highlighting if there is a newer version.

This work is attached to this issue:
https://github.com/CanonicalLtd/jujucharms.com/issues/323

**Comment by spencerbygraves** [comment]
Hi @arosales We're currently working on this, you can see the progress here - https://github.com/CanonicalLtd/juju-design/issues/120

Thanks

**Comment by spencerbygraves** [comment]
This work has been done and is awaiting release.
