### ISSUE TITLE
Add to demo doesn't work for individual charms

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#363]
When viewing a charm such as:
https://jujucharms.com/ghost/0
and I click on "Add to demo" it takes me to demo.jujucharms.com, but the ghost charm is not added.

Interestingly, if I try this with a bundle it does work. For example, if I click on "Add to demo" from https://jujucharms.com/hadoop-processing/
it does put the bundle on the canvas.

**Comment by urosj** [comment]
Thanks, @arosales. We've got a fix in pipeline and will be out today with GUI 2.2.2 release.

https://github.com/juju/juju-gui/pull/2141

**Comment by arosales** [comment]
@urosj and co thanks for the work on this.

**Comment by urosj** [comment]
This has been deployed to production.
