### ISSUE TITLE
Docs: outdated v1 commands at https://jujucharms.com/docs/2.0/charms-config

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#364]
Hello everyone,

There are some `juju set-config` commands at the bottom of the page https://jujucharms.com/docs/2.0/charms-config which is no longer exists in juju v2.

Those `juju set-config` commands should be updated with `juju config` according to the https://jujucharms.com/docs/2.0/command-changes doc.

**Comment by pmatulis** [comment]
Moved to https://github.com/juju/docs/issues/1481
