### ISSUE TITLE
Link styles inconsistent

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#367]
The  links in docs are now sometimes blue and sometimes black. the black versions are not underlined which makes it difficult to distinguish from normal bold text.

E.g. see
https://jujucharms.com/docs/devel/introducing-2

**Comment by anthonydillon** [comment]
This matches the new link styling [1]. The reason for the black links is due to the links being inside a list. This will need a design review to determine if we we need to change the link spec.

[1] https://github.com/CanonicalLtd/juju-design/issues/154#issuecomment-250495649

**Comment by evilnick** [comment]
I can well understand that there is a case for different link styles in some web elements across the site, but it absolutely makes no sense whatsoever to have two different links styles in the body text of documentation, especially one which makes them practically undetectable.

**Comment by kasiag** [comment]
Hi Nick, thanks for raising the issue here. We'll definitely look into it, Ant's away at the moment so it might not happen straight away though. I will keep you updated.

**Comment by spencerbygraves** [comment]
Hi @evilnick We have recently updated our link styles, you can see the spec for usage at the end of this issue - https://github.com/CanonicalLtd/juju-design/issues/154

But you're right, we should only have blue links in copy. We'll have a look and get this updated when Ant is back in the office.

Thanks for pointing it out.

**Comment by yaili** [comment]
@anthonydillon what's the status of this issue? there are still cool grey links in lists

**Comment by anthonydillon** [comment]
@yaili This is done. Where do you see cool grey links in lists?

**Comment by yaili** [comment]
Here: https://jujucharms.com/docs/stable/getting-started

**Comment by anthonydillon** [comment]
Ah that is because the lists are not paragraphs. To have links in lists as blue then they been `<p>` tags around the content. I have not been told we are moving away from the list link styling.

**Comment by yaili** [comment]
It shouldn't need to be in paragraphs

**Comment by anthonydillon** [comment]
How could we keep grey links in lists and indicate that some should be body links?

**Comment by evilnick** [comment]
I think what we would like is for any link that appears in the body of documentation to have the same link style, preferably one that is easy to see.

**Comment by anthonydillon** [comment]
Yes that would be good and is the way it is styled on docs.ubuntu.com. So once these docs are adopted into the new docs system this will happen out of the box. 

This does raise the question, do we need lists to have different link styling? Which was spec'ed out in the design documentation.

**Comment by yaili** [comment]
I don't think we do.

**Comment by anthonydillon** [comment]
@yaili @spencerbygraves can you work out a new link spec and I'd be happy to implement it.

For reference this is the current spec:
https://github.com/CanonicalLtd/juju-design/blob/master/Links/Link%20styles.png

**Comment by spencerbygraves** [comment]
If it works on docs.ubuntu.com, and that's what we're moving to, why does it need to be changed?

**Comment by anthonydillon** [comment]
Because the spec says to use bold normal font colour for lists which is
causing this issue.

**Comment by spencerbygraves** [comment]
I can add an exception to the spec for blue links in blocks of copy in a list.
