### ISSUE TITLE
Long code snippets rendered from charm/bundle readmes do not have scrollbars

### ISSUE THREAD

**Issue by szeestraten** [canonical/jujucharms.com#369]
Long code snippets rendered from charm/bundle readmes do not have scrollbars which makes it impossible to see long commands and settings on jujucharms.com.

Example: https://jujucharms.com/canonical-kubernetes/

Tested with: 
Chrome 54.0.2840.71 m (64-bit)
Firefox 49.0.2

**Comment by anthonydillon** [comment]
Thank you for the bug. This has been fixed and will be live shortly.
