### ISSUE TITLE
Missing code author for some authors/charms

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#37]
All of the revisions of the [Percona Cluster charm](https://jujucharms.com/percona-cluster/trusty/) made by James Page omit his name. It seems to be something about James rather than the charm per-se since a quick check of the [Nova Compute charm](https://jujucharms.com/nova-compute/trusty/) shows the same symptom

**Comment by urosj** [comment]
Thanks for pointing us to that, Adam.

Looks like there's a bug in bzr info ingestion from LP. We'll look if James
is special or if there are any others as well. However, this looks like an
old issue. Looking at legacy charmworld here:

https://api.jujucharms.com/v4/trusty/percona-cluster/meta/extra-info

The info on James is also missing.
