### ISSUE TITLE
doc: detail that you must provide a charm version when issuing charm attach

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#370]
The documentation here is wrong: https://jujucharms.com/docs/stable/developer-resources#charm-attach

The right way to attach is:
```
charm attach ~adam-stokes/dokuwiki-12 stable-release=/home/adam/Downloads/dokuwiki-stable.tgz
```

See https://github.com/juju/charmstore-client/issues/96 for further information

**Comment by pmatulis** [comment]
@jrwren If you will fix this issue now then great. If not, please move it to [juju/docs](https://github.com/juju/docs).

**Comment by jrwren** [comment]
https://github.com/juju/docs/pull/1512
