### ISSUE TITLE
'juju -h' includes link to wrong url: https://jujucharms.com/docs/stable/help

### ISSUE THREAD

**Issue by dooferlad** [canonical/jujucharms.com#371]
https://jujucharms.com/docs/stable/help is referenced in released versions of Juju but the page doesn't exist. Can we get a redirect to https://jujucharms.com/docs/stable/ please?

**Comment by pmatulis** [comment]
@bac This worked before didn't it? What change was needed?

**Comment by bac** [comment]
@pmatulis I don't think it worked. I could look through git for the docs branch to see if '/help' ever existed.

I added a RewriteRule to our apache config to forward to the existing page.

Should the docs team ever want to create that page you'll need to coordinate with use to remove the rewrite.

**Comment by pmatulis** [comment]
@bac It never existed but I thought we had a redirect in place.
