### ISSUE TITLE
We had an Issue with Juju Charm store user accounts.

### ISSUE THREAD

**Issue by sivaramaprasadr** [canonical/jujucharms.com#372]
We developed a charm for OpenStack Kaminario Cinder drivers.
In order to interact with Juju charm store, we need to create an Ubuntu SSO account. We followed the following link :
https://jujucharms.com/docs/2.0/authors-charm-store.

We pushed developed charm to Juju public charm store using Ubuntu SSO account through CLI.

For creating Ubuntu SSO account with username "hareeshk", we used following email id : 
Harish.Kannamthodath.CTR@kaminario.com

In charm store, our charm is published as "cs:~hareeshk/kaminario-cinder"

As per client request, we want to publish the charm as "cs:~kaminario/kaminario-cinder". 
We mean that we want to publish charm with "kaminario" username.

Next, We permanently deleted Ubuntu SSO account of username "hareeshk".

We created another Ubuntu SSO account with username "kaminario"
and with email address: "Harish.Kannamthodath.CTR@kaminario.com".

Primary ISSUE
----------------

We got one verification email to verify the created "kaminario" username account. Here we got some verification issue. Due to that, we are not able to do "charm login". So we permanently deleted the Ubuntu SSO account of username "kaminario".

We tried to create Ubuntu SSO account with the same "kaminario" username and email address "Harish.Kannamthodath.CTR@kaminario.com". But while account creation itself it gave the following issue:
"Kaminario already in use"

Later we came to know that, Before deleting Ubuntu SSO account we need to deactivate launchpad account. actually, we didn't deactivate the launchpad user accounts. Due to that account username("kaminario") stored in ubuntu server cache. 

How do we delete "kaminario" username from ubuntu server cache? 
Our intention is to create a Ubuntu SSO account with email : "Harish.Kannamthodath.CTR@kaminario.com" and username "kaminario". And then we want to push our charm to public charm store.

Secondary ISSUE
-------------------
Charm "cs:~hareeshk/kaminario-cinder" still present is charm store.
We want to revoke the access permissions of this charm. But we don't have Ubuntu SSO account with which we pushed the mentioned charm. Because we deleted that account permanently. But "hareeshk" username still stored somewhere in Ubuntu server cache.

How do we delete "hareeshk" username from Ubuntu server cache ? Our intention is to create a Ubuntu SSO account with email : "Harish.Kannamthodath.CTR@kaminario.com" and username "kaminario". And then we want to revoke the access permissions of the old published juju charm.

Please provide us the way to delete "kaminario" and "hareeshk" usernames from Ubuntu server cache.

**Comment by urosj** [comment]
@mhilton can we close this now?

**Comment by sivaramaprasadr** [comment]
@rock  :   Yes. Thank you, mhilton for your good support.
