### ISSUE TITLE
No padding on cookie warning on mobile

### ISSUE THREAD

**Issue by makyo** [canonical/jujucharms.com#373]
![screenshot_20161108-100432](https://cloud.githubusercontent.com/assets/303761/20108941/3203c018-a59b-11e6-86be-ad11fb7f2a3f.png)

**Comment by anthonydillon** [comment]
Thanks, this will be fixed when the theme is updated with this branch. https://github.com/ubuntudesign/cloud-vanilla-theme/pull/46
