### ISSUE TITLE
search results gives link to non-existent page.

### ISSUE THREAD

**Issue by jrwren** [canonical/jujucharms.com#374]
Search for "network"

The 3rd hit is "Configuring juju for openstack"

click that link and the page "https://jujucharms.com/docs/2.0/config-openstack/" does not exist.

This happens for both 2.0 and master version of docs.

**Comment by pmatulis** [comment]
Tested searching for 'network' on the 'devel' (master) branch.

My 1st hit is [How to configure more complex networks using spaces](https://jujucharms.com/docs/master/wip-spaces) and it also doesn't exist.

My 3rd hit is [Configuring Juju for use with vSphere](https://jujucharms.com/docs/master/config-vmware/) but that page doesn't exist either.

**Comment by bac** [comment]
We've clearly got something wrong with ElasticSearch when new docs are found. We will investigate tomorrow.

**Comment by frankban** [comment]
Search results seem to be ok now.
