### ISSUE TITLE
We need better docs as to what it means to deploy cs:NAME

### ISSUE THREAD

**Issue by jrwren** [canonical/jujucharms.com#377]
When I juju deploy cs:etcd it goes ~containers/trusty/etcd-3 but when I visit jujucharms.com/etcd it takes me to ~charmers/trusty/etcd-5 ?

This is surprising as I think of both of them as "cs:etcd" 

How can I know the web url for cs:etcd without expanding cs:etcd by deploying it and seeing that it expands to  ~containers/trusty/etcd-3 ?

**Comment by frankban** [comment]
@jrwren are you still having this issue? In that case, could you please file a bug against juju/docs?
