### ISSUE TITLE
Left right arrows on homepage have broken hover over

### ISSUE THREAD

**Issue by buggtb** [canonical/jujucharms.com#378]
When you're on the landing page, and you hover over the front and centre picture you have left and right arrows which have a half working tool tip appear. The right one is fine, the left one, someone has just rotated the arrow 180 degrees so it says previous upside down.
![untitled](https://cloud.githubusercontent.com/assets/103544/20431611/d6685f3e-ad92-11e6-8e11-9bd70401bd84.png)

**Comment by bac** [comment]
Thanks Tom. We've fixed the issue and will roll it out next week.
