### ISSUE TITLE
Feature Request: Details and examples for spaces, subnets, spaces constraints and endpoint bindings

### ISSUE THREAD

**Issue by iatrou** [canonical/jujucharms.com#379]
Provide a more elaborate description (including example use cases) of spaces, subnets, spaces constraints and endpoint bindings, and how they are materialized on MAAS and other cloud/substrate types.

**Comment by frankban** [comment]
Hey @iatrou ,
thanks for reporting, I moved this request to the docs tracker at https://github.com/juju/docs/issues/1695
Please check for any follow ups there.
