### ISSUE TITLE
Links to interface documentation 404

### ISSUE THREAD

**Issue by AdamIsrael** [canonical/jujucharms.com#38]
It appears that the Interfaces pages on manage.jujucharms.com are providing a link to interface documentation that no longer exists.

For example, https://manage.jujucharms.com/interfaces/http links to https://juju.ubuntu.com/Interfaces/http, which returns a 404.

It seems to be a general issue with interfaces, rather than isolated to just one interface.

**Comment by mitechie** [comment]
We've got WIP to redirect these to jujucharms.com in the next charmworld release. We don't yet have interface search/etc but will redirect to a search for that interface word in jujucharms.com as a first stab. That work is tracked in lp:charmworld so closing it here.
