### ISSUE TITLE
Getting started with Juju missing install for lxd 

### ISSUE THREAD

**Issue by ssweetin** [canonical/jujucharms.com#382]
https://jujucharms.com/docs/stable/getting-started

The section **Install the software** should also include instructions for installing lxd:

`sudo apt-get install lxd`

After installing vanilla 16.04 LTS (Xenial) could not follow the following section's instructions  `newgrp lxd` as the group lxd was not available.

**Comment by pmatulis** [comment]
In Xenial, package `lxd` is a *recommends* of `juju-2.0`. Are you using a custom APT configuration?

http://packages.ubuntu.com/xenial/juju-2.0

**Comment by ssweetin** [comment]
Thanks. No I'm not using a custom APT configuration.

Is this what's expected?
```
$ apt-cache depends juju-2.0
juju-2.0
  Depends: distro-info
  Depends: libc6
  Conflicts: <juju2>
  Breaks: juju-core
  Recommends: bash-completion
```
Ah, it looks like since 16.04.4 that `lxd` is no longer a dependency.

**Comment by nskaggs** [comment]
@pmatulis This is a packaging difference issues between ppa and archive. It's a dependency for the archive version, but not for the ppa. I will update the ppa packaging, but it won't be "fixed" until the next versions land.

That said, xenial has LXD by default, so unless you specifically removed it, you should have it.

**Comment by ssweetin** [comment]
@nskaggs I downloaded the first image I saw on https://www.ubuntu.com/download which was Ubuntu Desktop.

From what I can tell LXD is only in Xenial Ubuntu Server by default.

**Comment by nskaggs** [comment]
@ssweetin Right you are. Well, thank you for raising the bug. This should be fixed in the next stable release to the ppa (which will be 2.1). I trust you were able to continue on after installing LXD though.

**Comment by frankban** [comment]
This is fixed now.
