### ISSUE TITLE
Beta signup thank-you page profile link?

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#383]
The beta signup thank-you page (https://jujucharms.com/beta/thank-you) says that you **must** visit your profile page to complete the early access registration, but that links to https://jujucharms.com/login and my profile page (which I assume is https://jujucharms.com/u/johnsca/) doesn't include any info about the registration.

**Comment by anthonydillon** [comment]
We actually need you to visit your logged in profile page. Therefore by
directing people through the login they should land on there profile logged
in.

**Comment by frankban** [comment]
Closing this as users no longer have to follow the private beta signup process.
