### ISSUE TITLE
Wrong logos on jujucharms

### ISSUE THREAD

**Issue by udinachmany** [canonical/jujucharms.com#384]
AFAIK there is no Juju provider on IBM clouds... suggest replacing with Rackspace logo . And what about VMware vCenter? That's a big logo to have. All logos can be found on Partner Finder. Relevant links:

https://jujucharms.com/
https://jujucharms.com/about

**Comment by spencerbygraves** [comment]
The IBM logo has been kept as it's in the users and contributors section. The about page is no longer linked to from jujucharms.
