### ISSUE TITLE
I can see my models on the hosted controller, but other users don't have the same experience via jujucharms.com

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/jujucharms.com#391]
Concerning juju hosted controllers, I can login to jujucharms.com and see my models on the hosted controller, but the 3 other users on my ~creativedrive launchpad team don't have the same experience.

I've had them log in and out of jujucharms.com, and `charm login`, `charm logout` a bunch of times to no avail.

The affected users have registered with the hosted controller, and are creating their own models on it via cli.

Attached you will find a screenshot of what these users are experiencing.

Is there something I'm missing here?
![screen shot 2017-01-19 at 2 05 11 pm](https://cloud.githubusercontent.com/assets/5590546/22121075/47a8a2c4-de37-11e6-9c93-2492a8504aa8.png)

**Comment by jamesbeedy** [comment]
Also, per the screenshot, the teams count indicates 0, while this user is a member of ~creativedrive launchpad team, see https://launchpad.net/~simonbacquie

**Comment by frankban** [comment]
@jamesbeedy this is interesting. Could you please check that the models are visible now that the public beta is opened?

**Comment by frankban** [comment]
Closing this as this is a really old bug, probably related to issues encountered when the feature was launched.
