### ISSUE TITLE
unexpected behavior from jujucharms.com

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/jujucharms.com#392]
User's home page at jujucharms.com looks like this
![homepage](https://cloud.githubusercontent.com/assets/5590546/22121075/47a8a2c4-de37-11e6-9c93-2492a8504aa8.png)

When the user clicks "create new" he is redirected here
![screen shot 2017-01-19 at 2 26 07 pm](https://cloud.githubusercontent.com/assets/5590546/22121950/ce8508b6-de3a-11e6-9e20-4d36a576f94b.png)

![screen shot 2017-01-19 at 11 36 21 am](https://cloud.githubusercontent.com/assets/5590546/22121990/eec6045e-de3a-11e6-8b5f-65da9a1ed30a.png)

**Comment by jamesbeedy** [comment]
recreated this issue here: https://github.com/juju/juju-gui/issues/2340

**Comment by jamesbeedy** [comment]
`charm whoami` doesn't show membership to any of charm-beta, charm-contributors, contributor-agreement-canonical.

Could this be a possible cause?

$ charm whoami
User: simonbacquie
Group membership: creativedrive

**Comment by frankban** [comment]
This is fixed now.

**Comment by frankban** [comment]
Please reopen this bug if you still encounter this problem.
