### ISSUE TITLE
No link to report a bug against a bundle

### ISSUE THREAD

**Issue by jhobbs** [canonical/jujucharms.com#395]
Example bundle I want to report a bug against:

https://jujucharms.com/u/openstack-charmers-next/openstack-lxd/

There is no link to report a bug.

**Comment by frankban** [comment]
We need to check if the bugs page has been submitted on the bundle extra info (in the charm store) and if we detect those values properly in the store front and in the GUI. Also, the "contribute" link on bundles points to 404 pages. Is that a leftover from ingestion days?

**Comment by frankban** [comment]
Closing this as now we have a way to publish charms/bundles and specifying a link for the homepage and bugs.
