### ISSUE TITLE
Cannot signin with ubuntu one credentials

### ISSUE THREAD

**Issue by leder11011** [canonical/jujucharms.com#396]
It gives a sorry page, pop back in again...

**Comment by joedborg** [comment]
I'm getting exactly the same

**Comment by urosj** [comment]
@joedborg we've identified the issue. Could you please try again?

**Comment by joedborg** [comment]
@urosj works fine now, thanks for the quick response!

**Comment by leder11011** [comment]
@urosj sorry, not better now. I seem to be already logged in and when I click "sign in" the error page immediately appears!

**Comment by urosj** [comment]
@leder11011 could you give me your username name or email so that we can check your logins? Or is it for the first time?

**Comment by leder11011** [comment]
@urosj yes, where can I send it to?

**Comment by frankban** [comment]
@leder11011 could you please confirm that this is still an issue for you?

**Comment by leder11011** [comment]
I am very pleased: juju login and beta login work with my ubuntu one credentials now!

Ticket to be closed.
