### ISSUE TITLE
Website and store is completely different when logged in

### ISSUE THREAD

**Issue by merlijn-sebrechts** [canonical/jujucharms.com#398]
The website and store are very different when I'm logged in into the demo beta. A bunch of pages aren't accessible anymore and the search experience is degraded.

It seems that when you login, it shows the Juju UI itself instead of the `jujucharms.com` website. I need to open it in incognito modus to find what I'm looking for.

# `https://jujucharms.com/`

**Normal**

![image](https://cloud.githubusercontent.com/assets/1492981/23127274/b249ed84-f77a-11e6-9018-3fbb2c535500.png)

**logged in**

*redirects to `https://jujucharms.com/u/merlijn-sebrechts`*

![image](https://cloud.githubusercontent.com/assets/1492981/23127323/e8c9002a-f77a-11e6-91bc-7cf0eacecb3d.png)

# `https://jujucharms.com/u/tengu-team/`

**Normal**

![image](https://cloud.githubusercontent.com/assets/1492981/23127382/258579e4-f77b-11e6-9785-34d27d2afb0f.png)

**logged in**

*redirects to `https://jujucharms.com/u/merlijn-sebrechts`*

# Clicking on username on charm page

**Normal**

goes to `https://jujucharms.com/u/<username>/`

**logged in**

goes to `https://launchpad.net/~<username>/`

# clicking on username on search page

**Normal**

Goes to `https://jujucharms.com/u/<username>/`

**logged in**

Searches for `<username>`

**Comment by frankban** [comment]
The fix is in progress as part of https://github.com/juju/juju-gui/issues/2476 , and should go live this week, thanks for reporting!

**Comment by merlijn-sebrechts** [comment]
Thanks, that will solve my biggest issue.

Just to be clear, will the `jujucharms.com` website be completely replaced by the juju gui? It is quite strange that logging in into the demo results in `jujucharms.com` pointing to a Juju GUI instead of the `jujucharms.com` website. Is this intentional?

**Comment by frankban** [comment]
The two systems will converge more and more, so yes this is intentional. The GUI is already able to handle authenticated users interactions very well, and it also allows managing your models in a cleaner way. Any suggestions on how to make the integrated GUI better or this transition easier is welcome. Thanks a lot!

**Comment by merlijn-sebrechts** [comment]
**Two functions from jujucharms.com that I need in the GUI:**

- Correct "actions' section. It's incorrect for bundles and doesn't exist for charms. https://github.com/juju/juju-gui/issues/1704
- "Bundle configuration" part at the end of the bundle page (see screenshot at the bottom of this comment)

**Feature request:**

The ability to link to a heading of the Charm readme. Github has this nice little "url" icon appearing next to each heading that can be used to link to that part of the readme. Very useful for sending users to the correct part of the documentation. Example: https://github.com/ibcnservices/layer-openvpn#administration

![image](https://cloud.githubusercontent.com/assets/1492981/23160621/78b54462-f827-11e6-9a2a-26377e292c45.png)

**Comment by frankban** [comment]
@galgalesh I filed the two missing issues related to your suggestions. Thanks for your feedback!

**Comment by merlijn-sebrechts** [comment]
Thanks!

The last thing is the original issue from this thread; the "homepage" of the Juju GUI is a lot less helpful than the jujucharms.com homepage. Do I re-purpose this issue for that, or do I create a new issue on the Juju GUI issue tracker?

**Comment by frankban** [comment]
Having a new issue on the GUI project would be great, specific for homepage improvements. Thanks. I am closing this one here.
