### ISSUE TITLE
`charm build` should be `charm build .`

### ISSUE THREAD

**Issue by joedborg** [canonical/jujucharms.com#399]
Regarding https://jujucharms.com/docs/2.0/authors-charm-building

See my bug here https://bugs.launchpad.net/ubuntu/+source/charm-tools/+bug/1666301

You get different results when running `charm build` and `charm build .`

**Comment by frankban** [comment]
Hi @joedborg ,
I moved this issue to https://github.com/juju/docs/issues/1694
Thanks for reporting!
