### ISSUE TITLE
/solutions not sorted by deploys

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#40]
https://jujucharms.com/solutions does not default sorted the charm/bundle list by number of deploys. I also can sort by deploys in the header.  By default suggest to sort by deploy count (highest showed first).

-thanks,
Antonio

**Comment by mitechie** [comment]
This is still not sorting by deploys on the default solutions page. All of those are promulgated and should be treated as equals. Mysql, for instance, should be at the top.

**Comment by mitechie** [comment]
We've landed a fresh fix for this that will be in the next 0.1.14 release.
