### ISSUE TITLE
review queue link is broken.

### ISSUE THREAD

**Issue by jrwren** [canonical/jujucharms.com#401]
on page https://jujucharms.com/community/charmers
the "review queue" link goes to http://manage.jujucharms.com/tools/review-queue which is incorrect.

The "On-call Charm Review Schedule." link shows an empty calendar.

**Comment by arosales** [comment]
@jrwren 

Thanks we should do a full audit on this page. Review queue links should now go to review.jujucharms.com

Along with an update to "On-call Charm Review Schedule."  

A general update of the page and /community would be good.  We'll put this on our radar.

@castrojo ^

-thanks,
Antonio

**Comment by frankban** [comment]
Closing this as the charm/bundle publication process does not include a review queue anymore.
