### ISSUE TITLE
Broken links on Juju 2.1.0 release notes page

### ISSUE THREAD

**Issue by tytus-kurek** [canonical/jujucharms.com#403]
There are broken links on Juju 2.1.0 release notes page at https://jujucharms.com/docs/stable/reference-release-notes . Links which are broken:

https://jujucharms.com/docs/stable/2.1/charms-deploying/#deploying-with-binding
https://jujucharms.com/docs/stable/2,1/network-spaces/
https://jujucharms.com/docs/stable/2.1/charms-bundles/#binding-endpoints-of-applications-within-a-bundle

They all result in "Page not found" error message.

**Comment by frankban** [comment]
Hey, @tytus-kurek , thanks for reporting!
Moved to https://github.com/juju/docs/issues/1693
