### ISSUE TITLE
When logged in all jujucharm charm/bundle pages title = "untitled-model - Juju"

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#404]
After I log into jujucharms.com all the charm/bundle pages title are "untitled-model - Juju"

![untitled-jujucharms](https://cloud.githubusercontent.com/assets/1707853/23321237/d2ae72cc-fade-11e6-99ae-306981e64046.png)

I don't see this when I am not logged in

![correct-title-jujucharms](https://cloud.githubusercontent.com/assets/1707853/23321296/2a27cee0-fadf-11e6-8d5a-cd849f447376.png)

**Comment by hatched** [comment]
Thanks for this issue @arosales - I've created a tracking issue in the GUI project which is where this issue needs to be resolved https://github.com/juju/juju-gui/issues/2528
