### ISSUE TITLE
Unable to add credentials to GCE

### ISSUE THREAD

**Issue by hatched** [canonical/jujucharms.com#407]
When attempting to add credentials using the file upload link nothing happens.

**Comment by seman** [comment]
This might be related issue but the fields to enter GCP credentials are not visible. This seems an intermittent issue on Safari. See image below:

<img width="1120" alt="screen" src="https://cloud.githubusercontent.com/assets/1581316/23440596/ace59f8e-fdd1-11e6-9e8b-2d366162be57.png">
