### ISSUE TITLE
I can't tell what credentials JAAS is using.

### ISSUE THREAD

**Issue by abentley** [canonical/jujucharms.com#409]
I look through the GUI, and I can't find anything about my credentials.

I would expect to find them in my profile.

**Comment by hatched** [comment]
Thanks @abentley 

Next up on the roadmap we'll be introducing a place where you can view and manage your credentials. I don't have an ETA yet but soon :)

**Comment by frankban** [comment]
Yes, it's definitely o the roadmap for the near future. Closing this bug here.
