### ISSUE TITLE
Documentation link isn't about the gui

### ISSUE THREAD

**Issue by abentley** [canonical/jujucharms.com#410]
I'm confused by the gui, so I hit the help/Documentation link, and I get https://jujucharms.com/docs/stable/getting-started instead of documentation about the GUI.

**Comment by frankban** [comment]
That's the general documentation about Juju, for the GUI we are investigating with UX a more interactive way of providing help to users.

**Comment by abentley** [comment]
Perhaps it should say "juju documentation", but the lack of gui documentation is an issue too.
