### ISSUE TITLE
No obvious way to delete model from manage page

### ISSUE THREAD

**Issue by abentley** [canonical/jujucharms.com#412]
It appears you can delete a model from your profile page, but not from the model's "manage" page itself.

**Comment by frankban** [comment]
This requires an investigation from UX. @anthonydillon please file a bug in the GUI when this investigation has been done. Thanks!

**Comment by anthonydillon** [comment]
Thanks @frankban. @spencerbygraves could you take a look at this and report back with your findings.

**Comment by frankban** [comment]
Closing this for lack of updates, please reopen when/if this is on the roadmap again.
