### ISSUE TITLE
Accessing "wordpress" shows me "untitled-model" instead

### ISSUE THREAD

**Issue by abentley** [canonical/jujucharms.com#415]
When I "manage" bac's "wordpress" model, it doesn't show me the right thing.

https://jujucharms.com/u/bac/wordpress

Instead, it claims the name is "utitiled-model".

The dropdown shows "untitled-model" before I click it, but shows "bac/wordpress" when I click it.

**Comment by frankban** [comment]
Thanks for reporting @abentley .
As this is a proper GUI bugs, I've filed https://github.com/juju/juju-gui/issues/2557, and I am closing this.
