### ISSUE TITLE
Unclear what import / export buttons are supposed to do (if anything) on profile page.

### ISSUE THREAD

**Issue by abentley** [canonical/jujucharms.com#417]
When I look at my profile page, I see import/export buttons.  But it appears they are meant to import/export model data, not profile data.  When I initially export, I get
`services: {}
relations: []
machines: {}`

After I "manage" a model and go back to my profile, I get an export of the last model I managed:
`series: xenial
applications: 
  prometheus: 
    charm: "cs:~canonical-bootstack/trusty/prometheus-5"
    num_units: 1
    annotations: 
      "gui-x": "556"
      "gui-y": "3"
    to: 
      - "0"
relations: []
machines: 
  "0": 
    series: trusty
    constraints: "arch=amd64 cpu-cores=1 cpu-power=350 mem=3840 root-disk=8192"`

I think these buttons probably don't belong here.

**Comment by frankban** [comment]
Thanks for reporting, moved to the GUI tracker at https://github.com/juju/juju-gui/issues/2555
