### ISSUE TITLE
static bar at the top when scroll doesn't display the charm name

### ISSUE THREAD

**Issue by adam-stokes** [canonical/jujucharms.com#418]
![screenshot-jujucharms com 2017-03-02 14-49-02](https://cloud.githubusercontent.com/assets/51892/23524178/7d5f780c-ff57-11e6-980f-a67906d1560a.png)

I think this looks a little weird as it maybe should say the charm name when we scroll off that section of the page and the static bar comes down at the top?

**Comment by frankban** [comment]
Thanks for reporting!

**Comment by frankban** [comment]
Closing this as the sticky header is fortunately gone.
