### ISSUE TITLE
Anchors for charm config keys are not working

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#42]
When viewing a charm page, I see anchor links that I expect to jump me down the page to that config option description.

e.g. https://jujucharms.com/hacluster/trusty/#corosync_transport

... but it doesn't work, there doesn't appear to be a named anchor for it to jump to.

**Comment by mitechie** [comment]
Thanks, added to the board for a quick fix.

**Comment by sparkiegeek** [comment]
Hmm, so I see that anchors are now present on jujucharms.com, but if you try to actually use them, the top bar is hiding a lot of the content.

e.g. using the same config item I linked to above (but now with new anchor name)
https://jujucharms.com/hacluster/trusty/#charm-config-corosync_transport

I see this ![screenshot](https://cloud.githubusercontent.com/assets/246192/6332915/f8b90cce-bb80-11e4-9303-8a4e8f08e0b1.png)

note how I have to be aware that the content is hidden and scroll up.

**Comment by mitechie** [comment]
Ok, so sticky header isn't being your friend. Reopening for that purpose.

**Comment by sparkiegeek** [comment]
This is back, using an anchor to jump to a config setting once more hides the thing that you're jumping to because of the irritating header.
