### ISSUE TITLE
Notification at the top of the page not selectable, link not clickable

### ISSUE THREAD

**Issue by carlaberkers** [canonical/jujucharms.com#421]
Was browsing the Juju docs (https://jujucharms.com/docs/1.24/charms-config) when I noticed this notification "This version of the doc is no longer supported. Please check out <the stable docs>  for the latest in Juju.

It looks like there is a link there but I cannot select the link. I also cant select the text to copy it.

**Comment by bac** [comment]
Hi @carlaberkers thanks for filing this bug. Two things are going on. 1) 1.24 is deprecated and we shouldn't even be supporting that set of docs. 2) the link should work.

**Comment by frankban** [comment]
The link works now.
