### ISSUE TITLE
export is just as valid as import when there's nothing

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#423]
If I go to jujucharms.com/login as a new user w/o anything I get a nice welcome image and a "Start building". In the top are the import/export icons and the export icon looks clickable and is of no use to me at this time.

**Comment by frankban** [comment]
Thanks for reporting. @kadams54 is working on this. The bug is at https://github.com/juju/juju-gui/issues/2350 therefore closing this.
