### ISSUE TITLE
when I go to my profile page the gui says "connecting to model" 

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#426]
https://jujucharms.com/u/rick-harding%2Bguibot/

When I go there I get "loading the gui" and then "connecting to the juju model" when there's no model and nothing to connect there to. This should be updated to be something else or made removed?

**Comment by frankban** [comment]
Good catch! The spinner section will be rewoked heavily as part of https://github.com/juju/juju-gui/issues/2585 and I added your suggestion there. Thanks!
