### ISSUE TITLE
"Add to demo" doesn't work on this bundle

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#43]
There appears now way to demo this bundle: 

https://jujucharms.com/openstack/

**Comment by bac** [comment]
Thanks for the report Jorge. It appears to be a wider problem than that openstack bundle. Many of the other bundles are not found (grey deploy button) or are found (orange deploy button) but even they don't deploy to the demo.

**Comment by castrojo** [comment]
We've been made aware of the bundle's problems, thanks.

**Comment by mitechie** [comment]
This is due to the I'd mismatch from old to new. It's greyed out on
purpose. We'll be working to update shortly.
