### ISSUE TITLE
juju set-environment: unrecognized command

### ISSUE THREAD

**Issue by vds** [canonical/jujucharms.com#431]
$ juju set-environment
ERROR unrecognized command: juju set-environment

But it is mentioned in: https://jujucharms.com/docs/stable/reference-environment-variables

**Comment by frankban** [comment]
Hey Vincenzo, thanks for reporting. Yes I guess that command has been replaced by `juju model-config logging-config` or similar. Moved to the docs project at https://github.com/juju/docs/issues/1706
