### ISSUE TITLE
https://jujucharms.com/docs/1.25/wip-users suggests using a command that doesn't exist

### ISSUE THREAD

**Issue by xavpaice** [canonical/jujucharms.com#432]
Juju 1.25.6, attempting to run password changes, the instructions state to use "juju system" but this returns with "ERROR unrecognized command: juju system".

The same page also doesn't specify what should 'bob' should do with the .server file when it's been sent after creating the new user.

**Comment by frankban** [comment]
Thanks for reporting! Closing this as I moved this issue to the docs project:
https://github.com/juju/docs/issues/1774
