### ISSUE TITLE
Link to GCE credentials broken, JSON import throws error

### ISSUE THREAD

**Issue by alexlist** [canonical/jujucharms.com#434]
https://jujucharms.com/i/deploy mentions

The key information can be downloaded as a JSON file, or copied from  https://console.developers.google.com/project/apiui/credential.

This link seems to be outdated:
"URL not found
We couldn't find what you were looking for. Try one of the links below."

What I find is

https://console.developers.google.com/apis/credentials

I tried downloading a JSON file manually for deployment, and get: 

"cannot create model: cannot create model: failed to open environ: json: cannot unmarshal object into Go value of type string"

**Comment by hatched** [comment]
Thanks @alexlist for reporting this issue, I've created an issue to track it on the GUI project: https://github.com/juju/juju-gui/issues/2631

This will be resolved on the next release.
