### ISSUE TITLE
OpenStack Base bundle creates machines in Ireland??

### ISSUE THREAD

**Issue by faphdev** [canonical/jujucharms.com#437]
Why is the default Ireland? Should it be my account default with AWS?

**Comment by faphdev** [comment]
Also, no notification is sent when the process starts and nothing is sent when it is completed. I have no idea how to get started using the bundle.

**Comment by hatched** [comment]
Hi @faphdev were you using the GUI or the CLI when deploying the bundle? Was this with a self deployed controller or using jujucharms.com?

**Comment by faphdev** [comment]
Yes it was jujucharms.com JuJu as a service Beta...
Thanks!

**Comment by frankban** [comment]
Cool, thanks for reporting, we'll investigate what's going on in the GUI. Moved to https://github.com/juju/juju-gui/issues/2638, closing here.
