### ISSUE TITLE
Update community link (https://jujucharms.com/containers)

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#438]
"Use the above bundles, alter and extend them, or create your own. Get involved and find out more by visiting the _Container community_."

We'd like to update that to instead say:

"Get involved and find out more by in the Special Interest Group: [SIG-clusterops](https://github.com/kubernetes/community/blob/master/sig-cluster-ops/README.md), or the [Kubernetes mailing lists](https://groups.google.com/forum/#!forum/kubernetes-users)."

**Comment by spencerbygraves** [comment]
Hi @castrojo, the sentence you suggest doesn't read quite right, shall we remove 'by'?

Let us know what you think. Cheers.

**Comment by castrojo** [comment]
Feel free to copyedit as you wish!
