### ISSUE TITLE
in-page navigation doesn't correct for banner

### ISSUE THREAD

**Issue by merlijn-sebrechts** [canonical/jujucharms.com#439]
Clicking in-page navigation links doesn't work correctly. (Handling of `#my-link-title` and `<a name="my-link-title"></a>`)
# Reproduce

Click on https://jujucharms.com/u/tengu-team/openvpn/4#ubuntu-server-client

# Expected result

"Connect an Ubuntu Server" is at the top of the page.

![image](https://cloud.githubusercontent.com/assets/1492981/23998293/eee6129e-0a54-11e7-9673-f62503809333.png)

# Result I get

"Connect an Ubuntu Server" header is hidden by the banner.

![image](https://cloud.githubusercontent.com/assets/1492981/23998336/19551746-0a55-11e7-8e24-78265f00b530.png)

For an example of how it should work, look at how Github handles these links. https://github.com/tengu-team/layer-openvpn#ubuntu-server-client

**Comment by sparkiegeek** [comment]
Dupe of https://github.com/CanonicalLtd/jujucharms.com/issues/42?

**Comment by frankban** [comment]
Not sure it's a dupe. This is more about the anchor actually working but the sticky header hiding the title, IIUC.

**Comment by merlijn-sebrechts** [comment]
This is fixed
