### ISSUE TITLE
High Performance Batch Processing bundle 404's

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#44]
When viewing the big data topic page, the second bundle listing 404's when clicked.

https://jujucharms.com/big-data

https://jujucharms.com/u/bigdata-charmers/high-peformance-batch-processing

The repository exists in launchpad:

https://code.launchpad.net/~bigdata-charmers/charms/bundles/high-performance-batch-processing/bundle

I'm confused as to why its 404'ing

**Comment by jcsackett** [comment]
There's a typo in the url (peformance vs performance); we're landing a fix.

**Comment by castrojo** [comment]
Site is still broken, did this get deployed?

**Comment by mitechie** [comment]
Deployment rt is in progress

**Comment by castrojo** [comment]
Can someone check on this? This has been 404'ed for weeks now on one of the major pages of the site.

**Comment by mitechie** [comment]
The deployment has still not made it to production. It's rolled out to staging where you can verify the link no longer 404's. We're working with webops through deployment issues and mojo updates to get it out as fast as we can.

https://staging.jujucharms.com/big-data
