### ISSUE TITLE
feature: upgrade rails 3 to rails 5

### ISSUE THREAD

**Issue by leder11011** [canonical/jujucharms.com#440]
Hello all,

thank you for juju! I would like to see ruby on rails 5 in it...

BR
Gerrit

**Comment by hatched** [comment]
Hi @leder11011 If you'd like, you can write your own charms to run locally or upload to the charm store. You can find more information about this here: https://jujucharms.com/docs/stable/developer-getting-started or ask questions in #juju on irc.freenode.net
