### ISSUE TITLE
Some issue on the landing page

### ISSUE THREAD

**Issue by fabricematrat** [canonical/jujucharms.com#441]
![screenshot from 2017-03-17 10-37-16](https://cloud.githubusercontent.com/assets/1395842/24037358/d4cc8268-0afd-11e7-8735-c629d460f7b9.png)

**Comment by anthonydillon** [comment]
The SVG is rendering ok for me on Chrome. Which browsers are you using? Do you have a browser plugin turn backgrounds black?

**Comment by fabricematrat** [comment]
The main issure was my font setting on Chrome. and yes I have a plugin to turn everything to black !
