### ISSUE TITLE
Missing channel from charm information when logged into jujucharms.com

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#443]
When I'm browsing charms as an anonymous user - channel information is displayed on the charm informational header

![selection_007](https://cloud.githubusercontent.com/assets/246944/24067842/bbd6e4fe-0b4f-11e7-971b-586cdf1072a6.png)

After logging into the jujucharms.com ui and browsing to the same charm listing, there is no channel information about the charm revision displayed

![selection_006](https://cloud.githubusercontent.com/assets/246944/24067857/cfbb307e-0b4f-11e7-848d-8496bfc3a3a1.png)

**Comment by frankban** [comment]
Good catch! Moved to https://github.com/juju/juju-gui/issues/2654
