### ISSUE TITLE
Need help. Fresh installation getting error code: Errorno 2

### ISSUE THREAD

**Issue by Mrs-Feathers** [canonical/jujucharms.com#444]
hello. i've just now installed the juju-quickstart command as per canocal's website. it says i can just type in "juju-quickstart" and it'll set everything up for me.

i've got a fresh installation of ubuntu server LTS. nothing installed on it except openssh-server... oh and i apt-get updated and upgraded. but that's it. 

this is the only code i've typed in: 
sudo add-apt-repository ppa:juju/stable
sudo apt-get install juju-quickstart
juju-quickstart

i see a screen having me set up a and bind to a local environment. i select it and hit enter..  then it errors. here is the output. 

moth@mothgirlmusic:~$ juju-quickstart
interactive session closed
changes to the environments file have been saved
juju quickstart v2.2.4
adding the ppa:juju/stable PPA repository
sudo privileges will be required for PPA installation
sudo privileges will be used for the installation of
the following packages: juju-core, juju-local
this can take a while...
juju-quickstart: error: /usr/bin/juju: [Errno 2] No such file or directory

it should probably install juju for you, if they're going to go around on the website and tell you that you only need juju-quickstart. and advertise as "you can do all this faster than you can copy pasta commands" i'm still having issues.. for one, quickstart tries to issue a "juju bootstrap -e localhost" switch to juju and juju itself doesn't know what that means, i so i had to rewrite the command to remove the -e and just use juju bootstrap localhost, which worked. but now since quickstart is still giving that -e switch, i can't use it because juju doesn't know what quickstart is talking about. so then i find tutorial that just says to "juju deploy gui" then "juju expose gui" but now its telling me it doesn't know what that is and errors out from downloading it. --debug says its trying to connect to all these locations and can't find it so it tells me the charm or bundle doesn't exist. so i go to the store as it tells me to, but its down. and has been like all night or maybe longer. i only tried to connect to it tonight.

i dont know what to do and juju-quickstart seems to be broken and/or not being updated with the newest version of juju. 

i just want to see the GUI so i can start setting stuff up and getting work done. sadly, no forums or anything except here talk about any of the errors i'm experiencing. or mostly anything other than the "quick install" that i'm trying out that supposedly works.

am i doing something wrong or is this a legit problem for other people as well?

**Comment by Mrs-Feathers** [comment]
Linux mothgirlmusic 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

(as i said, fresh install of ubuntu server with only having installed juju-quickstart and now lxd and juju itself.)

**Comment by jrwren** [comment]
AFAIK we no longer recommend the use of juju-quickstart. Can you link to which canonical web page recommended the use of juju-quickstart?

The current getting started documentation is here: https://jujucharms.com/docs/stable/getting-started-general

I recommend following that getting started documentation and ignoring use of the older juju-quickstart tool.
