### ISSUE TITLE
Charm info page sticky header doesn't show icon or charm name

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#445]
e.g. https://jujucharms.com/nova-cloud-controller/#configuration shows as https://pageshot.net/b9E1TwHBeZug7tvj/jujucharms.com in both Firefox (v53.0a2) and Chrome on Ubuntu 16.04

**Comment by frankban** [comment]
This seems to be a duplicate of https://github.com/CanonicalLtd/jujucharms.com/issues/418
