### ISSUE TITLE
I can't copy and paste the charm URL from the upper right corner of a charm page.

### ISSUE THREAD

**Issue by jrwren** [canonical/jujucharms.com#446]
I do not want to copy the juju deploy text, only the charm URL so that I can paste it as an argument to charm show.

Alternatively, it would be nice to show READ and WRITE ACL on a charm page so that I do not have to copy the url to command line and run charm show.

**Comment by frankban** [comment]
Showing perms is a nice idea.

**Comment by mitechie** [comment]
I think that the permissions are only really useful to the charm author and is clutter for generic charm details usage. Maybe we're starting to need to look at an author view vs public view, but until we split that I think it's peachy for authors to use the charm cli. The burden is on the right place.

**Comment by barrymcgee** [comment]
This issue has been resolved.
