### ISSUE TITLE
juju gui command does not work

### ISSUE THREAD

**Issue by frankban** [canonical/jujucharms.com#447]
Something must be fixed in jimm for this to work, see https://github.com/CanonicalLtd/jem/issues/300
But also we need to check that the store front does not return an error when the juju client executes a preliminary request to check if the GUI is available at the provided URL.

**Comment by frankban** [comment]
Original report from https://bugs.launchpad.net/juju/+bug/1673265:

After registering with jimm.jujucharms.com and adding a model and deploying an application, I got the following error:

$ juju version
2.1.1-xenial-amd64

$ juju gui
ERROR Juju GUI is not available: GET https://jujucharms.com/u/bac-test/my-second-model/: unexpected content type text/html; want application/json; content: Page not found | Juju; <iframe src="//www.googletagmanager.com/ns.html?id=GTM-K9KCMZ" height="0" width="0" style="display:none;visibility:hidden"></iframe>; Jump to content; Store; How it works; Community; Docs; Try the beta; Sign in; kubernetes; elasticsearch; hdp-tez; hdp-storm; ceph; cassandra; percona-cluster; glance; mariadb; spark; Popular searches; openstack; ceph; mysql; hdp; spark; nginx; redis; jenkins; logstash; openstack; (108); applications; (248); databases; (71); app-servers; (75); file-servers; (48); monitoring; (28); misc; (279); ops; (22); If requested, in the address bar above, please allow popups; 404: Sorry, we couldnâ€™t find the page; Try a different URL, try searching for solutions or learn how to; create your own solution; Browse the store; All bundles; All charms; Submit a bug; Back to the top; Docs; Community; Blog; Install Juju; Â© 2017 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd; Legal information; Report a bug on this site; Got to the top of the ... [90 bytes omitted]

$ juju controllers
Use --refresh flag with this command to see the latest information.

Controller Model User Access Cloud/Region Models Machines HA Version
jimm-production-bac-test* my-second-model bac-test@external (unknown) 1 - - 2.0.0

**Comment by mhilton** [comment]
As noted in CanonicalLtd/jem#300. The client is doing this request unauthenticated, and is returned a 404. That is why the client doesn't think the address will succeed. Also whilst fixing CanonicalLtd/jem#300 is a good idea it certainly isn't necessary.

**Comment by frankban** [comment]
This functionality is now working properly on production.
