### ISSUE TITLE
Inaccurate information about the Canonical distribution of K8s bundle

### ISSUE THREAD

**Issue by ClaraLavina** [canonical/jujucharms.com#448]
Doing some research about K8s and reading all the available documentation and content we offer about this topic, I found some out-of-date information that should be revised as soon as possible.
Once the content has been checked and corrected, we can raise it with the web team. 

https://www.ubuntu.com/containers/kubernetes

- 'Getting started' video has a wrong cover image of the Canonical Distribution of Kubernetes bundle.
- 'Analytics on tap' section. Remove the part that says _'... a fully integrated Elastic Stack including Kibana for analysis and visualisations.'_
- 'Production features' section. Remove bullet point _'Optional: Elastic Stack for Insights with Beats log collection and monitoring and analysis and visualisation with Elasticsearch and Kibana.'_
- In ['Learn more in the Canonical Distribution of Kubernetes datasheet'](https://pages.ubuntu.com/rs/066-EOV-335/images/Datasheet_Canonical-kubernetes_28.09.16_WEB.pdf?_ga=1.267479310.1009276208.1474452978) PDF. Again here a wrong image of the bundle has been used. Also, there are some references to Elastic Stack and Elasticksearch & Kibana that should be removed.

**Comment by urosj** [comment]
@ClaraLavina This is ubuntu.com issue, not jujucharms.com issue, correct?

**Comment by ClaraLavina** [comment]
@urosj yes, just to double check with you as per @anthonydillon recommendation. Opening the issue now for ubuntu.com :)
