### ISSUE TITLE
charmstore search for private own bundle does not return results

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#449]
I've got a private bundle I've setup called "rickvpn" that I can see on my home account page. However, when I go to create a new model and search for it, I cannot find it. I get that there's no results and "build your own solution" which I've done. :)

If I search for my username, I do get a list of my charms, but not this private bundle.

**Comment by jamesbeedy** [comment]
@mitechie I'm experiencing this with private team charms too

**Comment by mitechie** [comment]
Thanks for the confirmation @jamesbeedy

**Comment by frankban** [comment]
I assume this is a GUI bug as you are logged in.
So moved to https://github.com/juju/juju-gui/issues/2764
