### ISSUE TITLE
The icon is not showing for the cloudfoundry charm.

### ISSUE THREAD

**Issue by Lucapaulina** [canonical/jujucharms.com#45]
If you look here:

https://jujucharms.com/u/lomov-as/cloudfoundry/trusty/3/

You'll see the grey generic icon. But if you look in the "Connect to:" interfaces section you'll see a cloudfoundry charm icon which links to the exact same page.

How comes it shows in the interfaces listing but not in the header?

**Comment by mitechie** [comment]
When loading the icon from bzr into chrome I get:

```
error on line 660 at column 31: Namespace prefix ns1 for connector-curvature on path is not defined
```

I'm going to guess that the api server had an issue reading the image. 
https://api.jujucharms.com/v4/~cf-charmers/trusty/cloudfoundry-201/icon.svg

However the second icon does not have that error when loaded into chrome and works properly over the api.

https://api.jujucharms.com/v4/~lomov-as/trusty/cloudfoundry-3/icon.svg

I've filed a bug on the charm about copying the good icon and once updated we should pick up the new better icon on next ingestion.

https://bugs.launchpad.net/charms/+bug/1425069

**Comment by mitechie** [comment]
I've emailed a memeber of the cf-charmers team about the issue and closing it here since it's not something we can correct without an update to the charm.

**Comment by mitechie** [comment]
The team has updated the icon but now there's a bug in the back end api. I've updated the bug here with details:

https://github.com/juju/charmstore/issues/301

and will work with the charmstore team to look into a fix.
