### ISSUE TITLE
Icons in bundle diagrams on k8s page not displaying

### ISSUE THREAD

**Issue by jcsackett** [canonical/jujucharms.com#453]
On the k8s page there are two bundle diagrams--the icons for each application within the bundle are not showing up.

The url for the svg is correct; going directly to it properly shows the icons. Additionally the same svg url is used on the bundle page, which also shows the icons properly.

**Comment by anthonydillon** [comment]
This is due to the icons loading relatively the url of the page.

To fix this the bundle diagrams need to be loaded in objects:
```html
<object wmode="transparent" width="100%" type="image/svg+xml" data="
https://api.jujucharms.com/charmstore/v5/bundle/kubernetes-core/diagram.svg
"></object>
```

Why didn't we use juju-cards here?

**Comment by Lukewh** [comment]
@anthonydillon gone done the fix already and we're not using juju-cards because of design and content differences to the bundles.

**Comment by anthonydillon** [comment]
I figured that. I guess my question is why is it different?

**Comment by Lukewh** [comment]
Valid question

**Comment by mitechie** [comment]
+1 I had hoped/expected we could leverage the cards UX for this. Ideally this would let us easily do something like a CMS where we can interchange or randomize solutions by providing different urls for different cards vs different designs/code/deploy. The more we can work towards interchangable dynamic parts the better long term. (I realize that's a bit big for this branch but want to encourage the thinking)

**Comment by frankban** [comment]
+1 we should leverage reusable parts also UX wise. Anyway, the bug seems fixed, and I guess these considerations are part of a more broader UX discussion. So closing this.
