### ISSUE TITLE
New loop device default value (juju docs)

### ISSUE THREAD

**Issue by jonatansouza** [canonical/jujucharms.com#455]
On the docs, Getting started with Juju section, the recomendation is let all default and option bellow: 
Size in GB of the new loop device (1GB minimum) [default=10GB]: 20.
however, when i installed here, the default value is now 100 GB:
its like:
Size in GB of the new loop device (1GB minimum) [default=100GB]?:

**Comment by frankban** [comment]
Thanks for reporting this inconsistency! I moved this bug to https://github.com/juju/docs/issues/1822 Please follow progress there.
