### ISSUE TITLE
Clicking on the juju card on another site causes /login url to be left. 

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#456]
I clicked on the card in this blog post: http://spicule.co.uk/devops/git/juju/2017/04/26/gitlab-charm.html

and it caused me to end up with a URL:

https://jujucharms.com/login/u/spiculecharms/gitlab-ssl

The /login should go away and not be part of the url I might mistakenly put into a blog post or share and such.

**Comment by frankban** [comment]
Closing this in favor of https://github.com/juju/juju-gui/issues/2817
