### ISSUE TITLE
Charms not showing in the charmstore

### ISSUE THREAD

**Issue by canonical-is** [canonical/jujucharms.com#46]
I have few charms which are not showing in the charmstore, they were published almost 24h ago. They all pass "charm proof" without errors (some report warnings though).

Here is the list:
lp:~canonical-sysadmins/canonical-is-charms/wordpress-services
lp:~canonical-sysadmins/canonical-is-charms/apache2-subordinate
lp:~canonical-sysadmins/canonical-is-charms/wordpress-plugin
lp:~canonical-sysadmins/canonical-is-charms/wordpress-theme
lp:~canonical-sysadmins/canonical-is-charms/squid-reverseproxy

**Comment by mitechie** [comment]
The branches need to be pushed under the charms distro. So the urls should be:

lp:~canonical-sysadmins/charms/canonical-is-charms/wordpress-services
lp:~canonical-sysadmins/charms/canonical-is-charms/wordpress-plugin
lp:~canonical-sysadmins/charms/canonical-is-charms/squid-reverseproxy

for example.

Bundles then need to be /charms/bundles. 

See the docs at https://jujucharms.com/docs/authors-charm-store#submitting for details.

**Comment by canonical-is** [comment]
I did not have permissions to push to lp:~canonical-sysadmins/charms/canonical-is-charms/<charmname>

Documentation you linked has this example:
bzr push lp:~your-launchpad-username/charms/series/nagios/trunk
so I pushed one of my charms here yesterday:
lp:~canonical-sysadmins/charms/trusty/apache2-subordinate/trunk

I cheked today and it's still not showing in the charmstore.

**Comment by mitechie** [comment]
I show the charm in the charmstore:

https://jujucharms.com/u/canonical-sysadmins/apache2-subordinate/trusty
