### ISSUE TITLE
Multi-series charms display incorrectly when logged in

### ISSUE THREAD

**Issue by paulgear** [canonical/jujucharms.com#460]
If I log into my jujucharms.com account and display a multi-series charm, the list of series is merged into a single word, as shown below:
![screenshot from 2017-05-03 15-24-44](https://cloud.githubusercontent.com/assets/107222/25648981/ea47b2c0-3014-11e7-996d-d911577f09ae.png)

**Comment by huwshimi** [comment]
@paulgear thanks for reporting that bug. The fix will be available with our next release.
