### ISSUE TITLE
Homepage & Community events are outdated

### ISSUE THREAD

**Issue by ClaraLavina** [canonical/jujucharms.com#462]
https://jujucharms.com/
> <img width="313" alt="screen shot 2017-05-08 at 11 20 24" src="https://cloud.githubusercontent.com/assets/22299251/25800310/a9d5621c-33e0-11e7-90a9-21065a7fb6ae.png">

https://jujucharms.com/community/
> ![screen shot 2017-05-08 at 10 52 02](https://cloud.githubusercontent.com/assets/22299251/25800326/bd7348c0-33e0-11e7-9b6b-78345e095ad6.png)

https://jujucharms.com/community/blog
> <img width="352" alt="screen shot 2017-05-08 at 11 23 47" src="https://cloud.githubusercontent.com/assets/22299251/25800342/d347ef02-33e0-11e7-860b-a62905af7cb5.png">

Update with https://insights.ubuntu.com/event/openstack-summit-boston/

@lukewh suggests automating how to get these events. We're not putting any extra info in there, he will try to do that instead, otherwise we'll be constantly updating these and needing to keep track of it.
@frankban @hatched any ideas? thoughts? :)

**Comment by Lukewh** [comment]
Closing as https://github.com/CanonicalLtd/blues_browser/issues/1589 has been merged and will be released at some point.
