### ISSUE TITLE
Behavior of “Search the store” magnifying glass on dark pages is surprising

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#465]
1\. Go to the jujucharms.com “[Kubernetes](https://jujucharms.com/kubernetes)”, “[Openstack](https://jujucharms.com/openstack)”, “[Big data](https://jujucharms.com/big-data) [How it works](https://jujucharms.com/how-it-works)”, or “[Jaas](https://jujucharms.com/jaas)” page.
2\. Click the icon in the header that is labelled “Search the store”.

What happens:
- [A separate page](https://jujucharms.com/q/) loads, apparently the results of a search for “”.
- “Search the store” is now revealed to be placeholder text in a text field that was previously invisible.

What should happen:
- The text field should be visible regardless of what’s around it and regardless of whether it is focused. (This seems to occur because [build.css](https://jujucharms.com/static/css/build.css) contains `body.how-it-works header.banner form.search-form .form-text {`…`border: 0;}`…`header.banner form.search-form .form-text {`…`background-color: transparent;`.)
- The field should not use placeholder text, because it’s misleading and there is plenty of room for a real label instead.
- An icon at the _left_ of a field should not submit anything.

**Comment by frankban** [comment]
That part has been recently redesigned, so please reopen if this is still a UX issue

**Comment by matthewpaulthomas** [comment]
Thanks @frankban. I mistakenly reported two bugs together on the assumption that they’d be fixed together.

It’s now much clearer that the field is a search field, but the submit behavior is unchanged, so I’ve reported that as #538.
