### ISSUE TITLE
Bad links from ubuntu.com to jujucharms.com

### ISSUE THREAD

**Issue by frankiegranato** [canonical/jujucharms.com#466]
When I try to reach jujucharms through any of the links in the "Browse on jujucharms.com" on www.ubuntu.com/cloud/juju I get an error page stating "Sorry for the inconvenience, please pop back soon.". This is an example of one of those bad links:  https://jujucharms.com/q/?tags=openstack I suggest we fix this asap.

**Comment by jcsackett** [comment]
It looks like there's a routing problem in jujucharms.com; for example https://jujucharms.com/q?tags=openstack works as expected.

I'll start a fix.

**Comment by jcsackett** [comment]
Ok--routing is working normally, and the failure appears to be intermittent. Those links worked for me last night but are now failing again.

I've requested logs to get the tracebacks associated with this failure.

**Comment by jcsackett** [comment]
The issue was with requests timing out between the storefront and the charmstore. I've had the timeout updated and the issue appears to be resolved. Please let us know if you see it again.

We'll also need to investigate performance of charmstore API as relates to these searches.
