### ISSUE TITLE
Wrong link to godoc for logging-config on models-config

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#468]
On [models-config page for 2.2](https://jujucharms.com/docs/2.2/models-config) for the `logging-config` row, the docs point to https://godoc.org/github.com/juju/loggo#ParseConfigurationString but the documentation is actually at https://godoc.org/github.com/juju/loggo#ParseConfigString

**Comment by jcsackett** [comment]
I've filed this issue with the juju docs repo at https://github.com/juju/docs/issues/1951--it's probably best to follow it there.
