### ISSUE TITLE
docs navigation is confusing

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#47]
Cross posting from
https://github.com/juju/docs/issues/272

"Someone on IRC asked about how to get started writing a charm, so I pointed them to the docs here: https://jujucharms.com/docs/authors-intro

However, I noticed the same thing I had trouble with when I started reading the docs - it's not at all clear how to navigate the site from this page.

By default, all sections of the navigation menu on the left are open, and so all the charm stuff is actually scrolled off bottom of the screen... and the actual contents of the page don't give you a way to navigate to the next page. Finally, there's no indication about which page you're on in the navigation menu, and the name of the link doesn't always match up well with the url.
"
All the nav-bar related things here are things we can't fix in docs, as jujucharms uses its own style/navigation

**Comment by mitechie** [comment]
Thanks, we can look at ways to improve the sidebar nav. My understanding is that we basically copied it from the old docs over.

**Comment by mitechie** [comment]
so just to bullet out things we can look at:
-  all sections of the navigation menu on the left are open
- indication on what page your on in the sidebar

The other things like navigating in each page and the name of the page and the url not matching are built into the docs themselves and would need updating on that end.

**Comment by evilnick** [comment]
yes. the old version of the docs had javascript which highlighted which page you had open in the nav bar.

I think it would be nicer to expand the subsection of docs you were in, but I can't think of an easy way to do that, so leaving it all open is probably better
