### ISSUE TITLE
telegraf charm confusion in the charm store search

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#470]
There is currently a 'recommended' (https://jujucharms.com/q/telegraf) telegraf charm which lags behind https://git.launchpad.net/telegraf-charm/log/

Newer versions get pushed here:
https://jujucharms.com/u/telegraf-charmers/telegraf/

It is a source of confusion as both are from telegraf-charmers but the second one does not show up in searches.

**Comment by urosj** [comment]
Hm, both have same owner, same channel and also are promulgated. We need to check ES and DB consistency. 

$ charm show telegraf
The plugin-driven server agent for collecting & reporting metrics.

Name			telegraf
Owner			telegraf-charmers
Revision		4
Supported Series	xenial, trusty
Tags			monitoring
Subordinate		true
Promulgated		true
Home page		https://launchpad.net/prometheus-charms
Bugs url		https://bugs.launchpad.net/prometheus-charms
Read			telegraf-charmers, everyone
Write			charmers

CHANNEL			CURRENT
stable			true

$ charm show ~telegraf-charmers/telegraf
The plugin-driven server agent for collecting & reporting metrics.

Name			telegraf
Owner			telegraf-charmers
Revision		11
Supported Series	xenial, trusty
Tags			monitoring
Subordinate		true
Promulgated		true
Home page		https://launchpad.net/prometheus-charms
Bugs url		https://bugs.launchpad.net/prometheus-charms
Read			telegraf-charmers, everyone
Write			charmers

CHANNEL			CURRENT
stable			true

**Comment by mhilton** [comment]
The above names refer to exactly the same thing.

$ charm show ~telegraf-charmers/telegraf hash
hash:
  Sum: f10e5ea41e5af33d4598558b4642517b3481bacbe71673aff0366d41ebccdf1e9d62ea78924a4ca51555b7f4d5850508
$ charm show telegraf hash
hash:
  Sum: f10e5ea41e5af33d4598558b4642517b3481bacbe71673aff0366d41ebccdf1e9d62ea78924a4ca51555b7f4d5850508

This is all working as specified. Promulgated and non-promulgated versions of charms have parallel version numbering. Search results will only contain the latest version of any charm, and for promulgated charms will not include the non-promulgated version. If we wish to change this we should consider the full ramifications of doing so. This is not a bug in the strictest definition, although it's clear that the interaction of the many ways of addressing charms is confusing.

**Comment by stub42** [comment]
I can confirm that they are supposed to be the same thing, and that members of ~telegraf-charmers should be pushing to cs:~telegraf-charmers/telegraf and those releases automatically copied to the top level namespace.

(I setup ~telegraf-charmers but it is a large team, per https://launchpad.net/~telegraf-charmers)

**Comment by frankban** [comment]
So this seems to be working as designed.
