### ISSUE TITLE
Charm community page for OpenStack links to out of date location

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#472]
On https://jujucharms.com/community for @javacruft 's section, there's a link to https://code.launchpad.net/~charmers/charms/bundles/openstack-base/bundle which is out of date and it should be https://github.com/openstack-charmers/openstack-bundles

**Comment by mitechie** [comment]
Code updated and will go out in the next release.

**Comment by mitechie** [comment]
Thanks for the bug and updated link!
