### ISSUE TITLE
cannot create model when deploying to GCE cloud on jujucharms.com

### ISSUE THREAD

**Issue by samantha-jp** [canonical/jujucharms.com#480]
Trying to deploy to GCE cloud gives error: cannot create model: cannot create model: failed to open environ: unexpected end of JSON input

I use the same JSON file and create a credential manually in local Juju and I am able to bootstrap on GCE successfully.

**Comment by mitechie** [comment]
Talked with the user and it works from the CLI loading the local GCE credential. Something might be up with loading the GCE credentials and using them.

**Comment by mitechie** [comment]
So I asked the user to verify that removing the gce credential pasted into the webui and running an add-model testinggce google/us-east1 works properly. It loads the local credential there. 

Something is up with the webui adding of gce credentials via the json file.

**Comment by hatched** [comment]
Thanks for bringing this to our attention, sorry for the inconvenience, we're working on a fix and will have an update out within the next day or so.

**Comment by hatched** [comment]
@samantha-jp I've created an issue in the GUI repository which you can watch to see when this issue has been resolved.
