### ISSUE TITLE
ERROR: context deadline exceeded - when trying to grant on jaas

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#486]
title says it all. Here the debug output - http://paste.ubuntu.com/25509057/

hitting this when trying to destroy a model too - http://paste.ubuntu.com/25509513/

update: I can't seem to destroy any model because of this "context deadline exceeded"

debug output for `destroy-model` http://paste.ubuntu.com/25509961/

**Comment by jamesbeedy** [comment]
@mitechie we can probably close this as it was due to the outage that day

**Comment by frankban** [comment]
Yes this does not seem to be an issue now.
