### ISSUE TITLE
Charm pages don’t use media object pattern

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#488]
Vanilla now has a version of the media object pattern with a larger icon, originally for use on snap directory pages ([vanilla-framework #1315](https://github.com/vanilla-framework/vanilla-framework/issues/1315#issuecomment-330197139)).

Many things about [charm pages](https://jujucharms.com/postgresql/) and snap pages are different for good reason. But this is one thing that could be consistent.

**Comment by matthewpaulthomas** [comment]
@hatched Could you explain why you closed this? Thanks.

**Comment by hatched** [comment]
@matthewpaulthomas oops sorry, yes, there is nothing actionable here. The designs are constantly being iterated on and we try and keep them consistent within the GUI and jujucharms.com. We also use a very old version of Vanilla and likely won't be updating anytime soon.
