### ISSUE TITLE
docs definition lists are broken and navigation is incomplete

### ISSUE THREAD

**Issue by sinzui** [canonical/jujucharms.com#49]
I updated the doc generation rules to support definition lists and attributes when I added
    https://jujucharms.com/docs/reference-releases

The markdown appears to have been generated with another mechanism that does understand definition lists attributes. The layout is loose and difficult to find the juju correct version.

The reference-releases page is not in the left navigation.

**Comment by evilnick** [comment]
When we land https://github.com/juju/docs/pull/275 hopefully jujucharms can be built with the tools in the doc tree?
 Ideally we should sync up the templating and possibly styles too.

**Comment by kadams54** [comment]
Addressed in CanonicalLtd/blues_browser#731.
