### ISSUE TITLE
bundles duplicated with different data in /u/containers

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#491]
Taking a look at the user page for /u/containers there's something fishy with several repeat bundles but they're different bundles. They're showing the same URL though. 

This is true both logged in with GUI serving results and logged out with the front end doing the work. 

![profile-bug](https://user-images.githubusercontent.com/75915/30653421-073cb7ac-9df9-11e7-922c-a222522c3818.jpg)

**Comment by hatched** [comment]
Thanks for the report. These values are being returned by the API, we'll investigate.

**Comment by frankban** [comment]
Moved to https://github.com/juju/charmstore/issues/775
