### ISSUE TITLE
developer getting started guide is outdated

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#493]
The dev guide still references the charm review queue process:

https://jujucharms.com/docs/stable/developer-getting-started#having-your-charm-reviewed

That is no longer accurate as per:

https://lists.ubuntu.com/archives/juju/2017-August/009294.html

The guide could use work in general as per the feedback in #juju:

> It could really use a bit of polish and a fully fledged example project that is kept up to date with an opinionated selection of the current best practice tooling (charmhelpers, automated functional testing with bundletester, amulet, matrix or what not). It still mentions the charm review queue for example.

At a minimum, we should at least get the inaccurate bits out.

**Comment by ghost** [comment]
See also juju/docs#2145.

**Comment by pmatulis** [comment]
@kwmonroe Your first link takes the reader to a paragraph that states that they need to submit their charm for review. How is that wrong? This links to the review process page, which, yes, needs to be updated.

I don't see anywhere how someone was supposed to submit their charm to the (now defunct) review queue. Do you?

**Comment by pmatulis** [comment]
After more reading, I see that there is indeed no review of any kind, which is odd.

**Comment by frankban** [comment]
It seems that docs have been updated and there is no mention of the review queue anymore. Thanks for reporting!
