### ISSUE TITLE
Bundle preview interferes with the sticky header

### ISSUE THREAD

**Issue by spencerbygraves** [canonical/jujucharms.com#494]
When viewing the bundle preview on the details page, the header and sticky header still appear above it, as does the embed button when you scroll.

![image](https://user-images.githubusercontent.com/9105999/31135851-36bfc7ca-a85e-11e7-9843-bba01feb2c5f.png)

![image](https://user-images.githubusercontent.com/9105999/31135832-2779cb4e-a85e-11e7-89d9-df41c187e6b0.png)

**Comment by frankban** [comment]
We historically had so many problems with sticky headers... And I wonder if they are a good idea anyway, as they kill scrolling with the space bar.

**Comment by frankban** [comment]
And we got rid of them! \o/
