### ISSUE TITLE
"Openstack Base Xenial Ocata #3" Does not install OpenStack Ocata

### ISSUE THREAD

**Issue by Tipu20** [canonical/jujucharms.com#495]
Hi All,

I am new to juju and was trying to deploy OpenStack Ocata Release using "Openstack Base Xenial Ocata #3" Charm however when i deploy this, this does not deploy Openstack Ocata and deploy much older release. 

How do i report an issue with charm ?

Regards,
Tipu

**Comment by frankban** [comment]
Sorry for the long delay before replying. If this bug is still relevant, please submit it to https://bugs.launchpad.net/openstack-bundles/+filebug which is the issue tracker for openstack bundles. Thanks!
