### ISSUE TITLE
cinder-ceph charm docs should mention the nova-compute relation

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#497]
Hello,

cinder-ceph charm should mention the nova-compute relation, if you do not add the nova-compute relation, these logs appear in /var/log/nova/nova-compute.logs while attaching the ceph backed volume to an instance via running below command : http://paste.ubuntu.com/25798028/

$ nova volume-attach demo_instance c3e5b795-654e-4938-af8e-a385fde72c86

Lack of the relation causes the generated rbd secret is missing in nova and that's why attaching volumes does not work. Adding the nova-compute relation fixes this problem.

I tested and confirmed this on an Openstack Mitaka cloud deployed on Trusty 14.04 with 17.02/stable charm set.

Charm [Doc] should mention the nova-compute relation with ceph-cinder : 

$ juju add-relation ceph-cinder nova-compute

[Doc]: https://jujucharms.com/cinder-ceph/

**Comment by gnuoy** [comment]
jujucharms.com is displaying the README.txt from the charm. Bugs for that charm are managed in launchpad here: https://bugs.launchpad.net/charm-cinder-ceph  Please file this bug there.

**Comment by hatched** [comment]
Thanks for filing this issue @aydintd but @gnuoy is correct :) Please file the issue with the charm repository.
