### ISSUE TITLE
Empty application name isn't rejected, causes issues

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#500]
Steps to reproduce

1. Add a charm to the canvas (I started with PostgreSQL but verified with K8S)
2. Configure one of the applications and empty the "Application name"

At this point, I expect a validation error, but it didn't complain... so:

3. Click deploy changes

Note that nothing happened, but look in your browser's console and see an error - http://paste.ubuntu.com/26003939/

**Comment by hatched** [comment]
Thanks for filing this issue, it's an issue with the GUI so I've moved the issue to that repository.

**Comment by frankban** [comment]
It seems that this has been fixed in the GUI.
