### ISSUE TITLE
Search text box on jujucharms.com is not visible/distinguish enough. Needs to be clearer that there is a search box.

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#501]
We had a big search text box on homepage which was the default one to be used. However with time, that got removed and we're left with the search box at the top right corner. 

Feedback has been that the search box is not visible enough and really easy to miss.

**Comment by spencerbygraves** [comment]
Here is a link to the designs in the juju-design repo - https://github.com/CanonicalLtd/juju-design/issues/338#issuecomment-345714664

**Comment by frankban** [comment]
Closing this issue as it refers to an old design.
