### ISSUE TITLE
Cookies message completely blocks deploy button in deployment flow

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#502]
See attached image. For new users, they don't really know what the next step should be.

<img width="1243" alt="cookies blocking deploy" src="https://user-images.githubusercontent.com/8036113/33017163-9087049a-cdf1-11e7-8e7f-18d428e9bc30.png">

**Comment by hatched** [comment]
Thanks for the bug, this is an issue with the GUI so I've created an issue there, this will be resolved in the next release.

**Comment by frankban** [comment]
This has been fixed.
