### ISSUE TITLE
Charm hovers can't be seen on a user page

### ISSUE THREAD

**Issue by spencerbygraves** [canonical/jujucharms.com#503]
When I go to a users page and hover over the icons, the hover is masked by the row:

![image](https://user-images.githubusercontent.com/9105999/33275082-d1d82bfc-d389-11e7-969a-2aa817e5fe85.png)

https://jujucharms.com/u/marcoceppi/

**Comment by hatched** [comment]
Closing as duplicate: https://github.com/CanonicalLtd/jujucharms.com/issues/499

**Comment by spencerbygraves** [comment]
Thanks @hatched
