### ISSUE TITLE
Remove plan ID from pricing plan "card" on charm details page

### ISSUE THREAD

**Issue by cmars** [canonical/jujucharms.com#504]
The plan ID isn't a very useful or meaningful title for the pricing plan card in the charm details page.

For example, the string "spiculecharms/pdi-plan" in https://jujucharms.com/u/spiculecharms/pentaho-data-integration/44.

I'm +1 for removing this string entirely as it's not clear what the user should do with it. The price and plan description are perfectly clear without it.

**Comment by frankban** [comment]
That charm profile page does not have plans anymore.
@hatched could you please check if this is still an issue?

**Comment by hatched** [comment]
This is no longer an issue as it's been removed from the UI. When we add it back in I'm sure that we can revisit the UI to not include something like that.
