### ISSUE TITLE
Not seeing charms I expect to see

### ISSUE THREAD

**Issue by mattyw** [canonical/jujucharms.com#508]
for reasons, yesterday I needed to answer the question "does cs~yellow/mycharm not exist, or does it exist but a certain user (not me) doesn't have permission to read it"
I went to jujucharms.com/u/yellow to have a look and once there I found that there were two charms that I would expect to see in that list, but they weren't there and I know they have read permissions
so I was then stuck, because a charm that I expected to see I couldn't.

**Comment by urosj** [comment]
Was the charm private and did you log in?

**Comment by mattyw** [comment]
Yes and yes, I even logged out and logged back in. Could it be the same issues as #509 ?

**Comment by frankban** [comment]
It seems that currently I can see my private charms, so I am closing this hoping it was a temporary issue.
