### ISSUE TITLE
/u/vtas-hyperscale-ci/hyperscale-controller charm not listed in search results.

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#509]
The charm is listed in the namespace https://jujucharms.com/u/vtas-hyperscale-ci and is reachable as stable, revision 14 here https://jujucharms.com/u/vtas-hyperscale-ci/hyperscale-controller and as edge, revision 28 here https://jujucharms.com/u/vtas-hyperscale-ci/hyperscale-controller/28 . The charm is in the store and is available for deploy. 

However, it is not listed in the search results. This looks like a bug in the search index, at least the results should include the revision in the stable channel.

**Comment by frankban** [comment]
The charm does not seem to be published anymore, so it's currently difficult to investigate this, please reopen if a similar error occurs.
