### ISSUE TITLE
Google results do not link to docs correctly.

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#51]
I searched for "juju constraints" on Google and the second link did not take me to the specific page.

Step 1:
https://www.google.com/search?&q=juju+constraints
Step 2:
Click on: "Machine Constraints - Juju Documentation - Ubuntu"
Step 3:
Notice you got sent to https://jujucharms.com/docs/ and not the charm-constraints page that you were looking for.

Can we fix that ?

**Comment by mitechie** [comment]
So the docs redirects were done on a case by case basis through webops. We'll need to ask the web team to adjust those. 

I've updated https://rt.admin.canonical.com/Ticket/Display.html?id=79080 with an effort to get this adjusted.

**Comment by mitechie** [comment]
RT to update the docs redirects are in place and the described link now redirects properly. Thanks for the bug report.
