### ISSUE TITLE
Can't destroy models from the profile

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#512]
When model is destroyed in the GUI, it is no longer listed in the profile, however "juju models" in CLI still list the model. 

Steps to reproduce:
- create model in CLI, deploy ubuntu
- go to GUI, destroy a model, verify that the model is no longer listed
- go back to CLI check if you see the model 

Using production + juju 2.3.1 client.

**Comment by cassiocassio** [comment]
I'm finding a delay of a minute-ish before it disappears at the CLI.

When you juju destroy-model you get more progressive feedback that the
model is being taken down.

**Comment by frankban** [comment]
As the model is eventually destroyed I'd not consider this critical. Currently there is no way to retrieve progressive feedback from juju. We don't have a watcher available from juju telling us when a model really goes away. We could change the profile to periodically poll for changes and in that way we could avoid hiding the model right away. Anyway, I am moving this to juju gui issue tracker.
