### ISSUE TITLE
Foldout triangles do not appear clickable

### ISSUE THREAD

**Issue by pmatulis** [canonical/jujucharms.com#515]
I think this has been reported a few times, in a few different repos but here it is again. The little foldout triangles do not appear to be things that a reader can click upon. See this [example](https://jujucharms.com/docs/stable/tools-charm-tools).

**Comment by anthonydillon** [comment]
Thanks @pmatulis, I have never been a fan of this pattern either. Even thought it is a web standard:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

I think design and UX should consider a different pattern for this style of content?

**Comment by anthonydillon** [comment]
Could I suggest putting each command on its on page? This would help when people Google commands to land on the correct information. This would also allow for further information like usage examples, etc.

**Comment by evilnick** [comment]
I think when we last had a mega discussion on this, we concluded that foldouts weren't an ideal pattern but that none of the others were either - they are used all over the Juju docs, not just in that one page. Just unbundling them makes the pages too long, turning them into thei own pages makes managing the links and all the docs unnecessarily complex, as well as causing navigation issues for readers.

We can have this discussion again if there are other ideas, but i think in the meantime adding a line of css to add a mouseover for the triangle widget is probably the best

**Comment by hatched** [comment]
Related: https://jujucharms.com/docs/stable/getting-started  

The 'choose your os' foldouts don't appear to be interactable

**Comment by frankban** [comment]
I am closing this as it seems the resolution is we have no better option. Feel free to reopen id you believe further discussion is required.

**Comment by pmatulis** [comment]
>  in the meantime adding a line of css to add a mouseover for the triangle widget is probably the best
