### ISSUE TITLE
User pages shows separate but identical copies of a bundle

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#518]
The user page, https://jujucharms.com/u/elasticsearch-charmers/, shows 2 separate copies of an ELK stack bundle, however they both point at https://jujucharms.com/u/elasticsearch-charmers/elk-stack/

**Comment by mitechie** [comment]
Thanks for the report. For some reason the two different revisions of the bundle are listed apart. This is true for both the logged in and out versions of jujucharms.com. 

    % charm show cs:~elasticsearch-charms/elk-stack
    Name			elk-stack
    Owner			elasticsearch-charmers
    Revision		2
    Promulgated		false
    Home page		https://launchpad.net/elasticsearch-charm
    Bugs url		https://bugs.launchpad.net/elasticsearch-charm
    Read			elasticsearch-charmers, everyone
    Write			elasticsearch-charmers

    CHANNEL			CURRENT
    stable			true

    % charm show cs:~elasticsearch-charmers/elk-stack-1
    Name			elk-stack
    Owner			elasticsearch-charmers
    Revision		1
    Promulgated		false
    Home page		https://launchpad.net/elasticsearch-charm
    Bugs url		https://bugs.launchpad.net/elasticsearch-charm
    Read			elasticsearch-charmers, everyone
    Write			elasticsearch-charmers

    CHANNEL			CURRENT
    stable			false
    candidate		true
    beta			true
    edge			true

    % charm show cs:~elasticsearch-charmers/elk-stack-2
    Name			elk-stack
    Owner			elasticsearch-charmers
    Revision		2
    Promulgated		false
    Home page		https://launchpad.net/elasticsearch-charm
    Bugs url		https://bugs.launchpad.net/elasticsearch-charm
    Read			elasticsearch-charmers, everyone
    Write			elasticsearch-charmers

    CHANNEL			CURRENT
    stable			true

**Comment by mitechie** [comment]
Interestingly the API doesn't return the double result. 

https://api.jujucharms.com/charmstore/v5/search?owner=elasticsearch-charmers

    {
        SearchTime: 3000000,
        Total: 4,
        Results: [
            {
                Id: "cs:elasticsearch-24"
            },
            {
                Id: "cs:kibana-19"
            },
            {
                Id: "cs:logstash-3"
            },
            {
                Id: "cs:~elasticsearch-charmers/bundle/elk-stack-2"
            }
        ]
    }

**Comment by mitechie** [comment]
This appears to be https://github.com/juju/charmstore/issues/775 so closing this one and tracking the work there. Thanks for the push on the issue.
