### ISSUE TITLE
Preformatted text mangled for not logged in user

### ISSUE THREAD

**Issue by fnordahl** [canonical/jujucharms.com#520]
I have [published](https://jujucharms.com/u/fnordahl/quagga/4) a Charm under my personal namespace. This Charm contains a README.md with some preformatted text.

If I view the Charm as a logged in user the text displays as expected. If I view the Charm as a not logged in user the text is mangled.

I am using Firefox 57.0.4 on Ubuntu. See attached screen shots.

![jujucharmstore-quagga-not-logged-in](https://user-images.githubusercontent.com/7078488/36343430-82d4d9f6-140c-11e8-9804-e993190836a5.png)
![jujucharmstore-quagga-logged-in](https://user-images.githubusercontent.com/7078488/36343433-90cadb50-140c-11e8-8bf1-fc8c2cade579.png)

**Comment by johnsca** [comment]
I also ran into this and it breaks the instructions in my README due to breaking YAML indentation.

**Comment by hatched** [comment]
Thanks for reporting this issue, the next update of jujucharms.com will have this issue resolved.

**Comment by fnordahl** [comment]
Perfect, thank you @hatched !
