### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by ernestmartinez** [canonical/jujucharms.com#521]

**Comment by mitechie** [comment]
Sorry, an update to machines has caused an outage. The team is tracking and working on it and updates will be made in this bug and in IRC #juju on freenode.

**Comment by pdgetrf** [comment]
also getting 503 when deploying with juju

Resolving charm: cs:~containers/easyrsa-27
ERROR cannot deploy bundle: cannot resolve URL "cs:~containers/easyrsa-27": cannot resolve charm URL "cs:~containers/xenial/easyrsa-27": cannot get "/~containers/xenial/easyrsa-27/meta/any?include=id&include=supported-series&include=published": unexpected response status from server: 503 Service Unavailable

could you confirm this is related to the outage?

**Comment by mitechie** [comment]
Yes, the API back end is down and that serves out the charms from the storage back end. 

We lost some hardware in an openstack and are working to add-unit and get the storage back up and running to serve the data. The data is on a redundant storage system so it should go back up pretty seamlessly in a bit.

**Comment by hatched** [comment]
We're back up!

Apologize for the inconvenience, please let us know if you encounter any further issues.

**Comment by s-monette** [comment]
Still having issue when deploying a charm:
`Resolving charm: cs:xenial/ceilometer-249
ERROR cannot deploy bundle: cannot resolve URL "cs:xenial/ceilometer-249": cannot resolve charm URL "cs:xenial/ceilometer-249": cannot get "/xenial/ceilometer-249/meta/any?include=id&include=supported-series&include=published": Get https://api.jujucharms.com/charmstore/v5/xenial/ceilometer-249/meta/any?include=id&include=supported-series&include=published: net/http: TLS handshake timeout`

**Comment by pdgetrf** [comment]
worked on my side. thanks.

**Comment by hatched** [comment]
@s-monette I'm not seeing any issues here, would you be able to give it another try, or check for routing issues to `https://api.jujucharms.com` on your end?

**Comment by s-monette** [comment]
Third time was the charm, now it work, thanks for the help.

**Comment by hatched** [comment]
Great, glad to hear it!
