### ISSUE TITLE
out of date events on homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical/jujucharms.com#524]
The two events that sit under the "Participate" heading are wildly out of date. Please insert up to date events or, if there are none, I suggest you remove the heading altogether.

**Comment by frankban** [comment]
We are fetching events from https://blog.ubuntu.com/category/events/feed?tag=juju
Is that no longer updated? Should we use another URL? Otherwise we could just remove all the code handling feeds.

**Comment by AdamIsrael** [comment]
Bumping this, as those outdated events are still showing, along with a broken image placeholder.

Can we remove the events, and perhaps move Ask the Community to its place?

**Comment by barrymcgee** [comment]
@AdamIsrael Thank you for bumping this - a fix has now landed and this issue will be resolved by the next deploy.
