### ISSUE TITLE
docs navigation is not updating

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#53]
I know this may be sort of mentioned in other issues, but I think this warrants an issue itself, if only so I can refer people to it.

The navigation bar in jujucharms.com/docs is not importing the navigation from the docs project. Changes and updates to the navigation are not reflected on jujucharms.com.

For example, the page https://jujucharms.com/docs/authors-charm-quality/ was removed as it is now redundant, but it is still listed in the navigation.

**Comment by mitechie** [comment]
Interesting, I know we worked on getting them updated, but you know...I'm not sure if we properly remove content. I bet this is a case where we build additive but don't clean out the old work. Will look into it asap.

**Comment by mitechie** [comment]
@fabricematrat can you look at in your AM please?

**Comment by mitechie** [comment]
@fabricematrat has gotten the logs from production and it appears we've hit a git issue. We're updating the docs frequently enough that we've had git on git crime and git has corrupted the checkout. We're working with webops to cowboy a fresh clone and reducing the cron job to update the docs less frequently while adding in the code a check for the existence of the .git lock file to prevent this in the future.

**Comment by evilnick** [comment]
Wow, that's an interesting bug! Good sleuthing skills!

**Comment by mitechie** [comment]
Closing as they are updating with our cowboy in place. The mentioned nav item is gone. We'll be pushing a better fix out in the next release.
