### ISSUE TITLE
https://jujucharms.com/u/openstack-charmers-next/openstack-base-bionic-queens/

### ISSUE THREAD

**Issue by jpl888** [canonical/jujucharms.com#530]
The subject bundle page has a number of issues I've discovered today whilst recreating an issue for a customer.

1. Missing Keystone v3 compatible scripts.
2. Image creation command that refers to non-existent distro "queens".
3. References to nova commands which will only work with Keystone v2 and should be converted to openstack commands.

The image creation command issue is the worst in my view. It will happily create an "image" based on the resultant http 404 response of 200 odd bytes, and then fail to launch instances with a volume based on the image, because it's not in qcow2 format.

I worked around the missing v3 scripts by using the ones in the openstack-on-lxd repo.

Please could you rectify the above issues on this bundle page and any others on which they appear? This is Canonical's shop window, so it would be good if it worked.

Thank You,

John.

**Comment by hatched** [comment]
Hi @jpl888 this is a repository for the jujucharms.com website. It appears you're having issues with the bundle itself. You'll want to get in touch with the authors of that bundle. I believe you'll have better luck here https://github.com/openstack-charmers/openstack-bundles

**Comment by jpl888** [comment]
Hi hatched,

Why are you closing this when at least some of what I said was in relation to the website itself?

**Comment by hatched** [comment]
The information that is presented on charm and bundle details pages are provided by the authors themselves in their README files. You can see this by clicking on the `README.md` file in the files list on the bundle details page you linked. So any changes to this content will have to be handled by the author directly. 

It looks like the openstack-charmers use launchpad for their bug tracking https://bugs.launchpad.net/openstack-bundles/+filebug I grabbed this link from the README on the above linked repository.

Authors are also encouraged to add the issues link to their charms and bundles under the `Contribute` heading on the top right of the page, it looks like they have not done that in this case however...

**Comment by fnordahl** [comment]
Thank you for pointing this out @jpl888.  We are in the process of releasing the 18.05 version of the charms and will publish updated bundles in conjunction with that.  Homepage/bugs-url will be set the next time we publish.
