### ISSUE TITLE
"Try the beta" button gives out the wrong message

### ISSUE THREAD

**Issue by fabricematrat** [canonical/jujucharms.com#532]
from @ktsakalozos

https://github.com/juju/charmstore/issues/782

Hi everyone,

People often ask "is Juju stable"? Has it happen to you? Someone asked again this morning on #juju. Going into the site visitors see the "Try the beta" button not realising there is a stable version. (Actually, I am not sure what is considered the stable version. Where do we draw the line?)

Are there any plans to go out of beta and remove that button? Should we be rephrase the wording on that button? Perhaps something like "Try Juju with beta features on"?

Thank you

**Comment by frankban** [comment]
We need to sync up before changing the messaging.

**Comment by matthewpaulthomas** [comment]
Until I read this bug report, twice, I hadn’t realized that there’s a separate non-beta version either.

I think the problem isn’t the messaging, it’s the placement. The biggest use cases for trying the beta would be for someone who already uses the stable version:
- I want the opportunity to give feedback on the beta, to influence its design
- I want to train/prepare my colleagues for impending changes.

The function can be shown to those people, without confusing non-users, by putting a version switcher _inside_ the signed-in UI instead. This is fairly common on other sites that have two versions running concurrently, [for example Outlook.com](https://support.office.com/en-us/article/Learn-about-the-Outlook-com-beta-e2261c7f-d413-4084-8f22-21282f42d8cf).

Oddly jujucharms.com does say “Beta” in the lower left corner when you are using it, but only in the “applications” view, and there doesn’t seem to be any way to switch back to the stable version.

![jujucharms com-beta](https://user-images.githubusercontent.com/19801137/43458601-b06e03ce-94c2-11e8-908e-f8171a344346.png)

**Comment by barrymcgee** [comment]
- The 'Try the beta' CTA has now been removed from the header of jujucharms.com (logged out)
- The 'Beta' label has since been removed from the logged-in app

There are still two instances of 'Try the beta' messaging in the Blues browser (logged out experience of jujucharms.com);

- `/how-it-works`
- `/jaas`

These are both call-to-action buttons that can be replaced with 'Try it now' as the text immediately before them explicitly describe JAAS.
