### ISSUE TITLE
Description of the CDK Bundle

### ISSUE THREAD

**Issue by idobos71** [canonical/jujucharms.com#533]
While the https://jujucharms.com/canonical-kubernetes/ bundle is now 10 machines (with 2 master nodes now), the bundle description on that page does still state it's "A nine-machine Kubernetes cluster".
In addition, the same description error is in the bundle.yaml file itself.

**Comment by hatched** [comment]
Thanks for the bug report @idobos71 . This is the issue tracker for the jujucharms.com website, I've created a new issue on the Canonical Distribution of Kubernetes bundle's repository here: https://github.com/juju-solutions/bundle-canonical-kubernetes
