### ISSUE TITLE
Behavior of search field magnifying glass is surprising

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#538]
1\. Go to any page on [jujucharms.com](https://jujucharms.com/).
2\. Click the icon in the search field.

What happens: [A separate page](https://jujucharms.com/q/) loads, apparently the results of a search for “”.

What should happen: The search field should be focused, and nothing else.

Sometimes search fields have a submit button at the _right_ end. But if a magnifying glass is at the _left_ end of a field, people are familiar with [that acting as just a label](https://developer.apple.com/design/human-interface-guidelines/macos/fields-and-labels/search-fields/). So clicking it shouldn’t submit anything.

[This is the sequel to #465.]

**Comment by frankban** [comment]
Thanks for reporting! @barrymcgee what do you think?

**Comment by frankban** [comment]
Also @cassiocassio ^^^

**Comment by barrymcgee** [comment]
Fixed by https://github.com/CanonicalLtd/blues_browser/pull/1826
