### ISSUE TITLE
unable to deploy bundle using given quickstart command

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#54]
The tooltip/command box gives me a quickstart command to deploy this bundle:

https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-scalable/

```
juju quickstart bundle:~bigdata-dev/apache-core-batch-processing-scalable-0
```

But that fails as follows:

```
$ juju quickstart bundle:~bigdata-dev/apache-core-batch-processing-scalable-0
usage: juju-quickstart [-h] [-e ENV_NAME] [-n BUNDLE_NAME] [-i]
                       [--environments-file ENV_FILE]
                       [--gui-charm-url CHARM_URL] [--no-browser]
                       [--distro-only] [--ppa] [--version] [--debug]
                       [--description] [--upload-tools]
                       [--upload-series UPLOAD_SERIES]
                       [--constraints CONSTRAINTS]
                       [bundle]
juju-quickstart: error: unable to open the bundle: invalid bundle URL: bundle:~bigdata-dev/apache-core-batch-processing-scalable-0
ERROR subprocess encountered error code 2
```

I can download the yaml and run `juju quickstart ./bundle.yaml` successfully as a workaround, but should the given syntax work?  Or is this perhaps a bug in quickstart?  Fwiw, i'm using juju-quickstart 1.6.0.

**Comment by mitechie** [comment]
Thanks for the bug report. This is a known issue at the moment. Quickstart and the jujucharms.com and gui have been updated but the release hit a snag. You can see the upcoming and more correct command here:

https://staging.jujucharms.com/u/bigdata-dev/apache-core-batch-processing-scalable/

So with quickstart v2.0 you would use

juju quickstart u/bigdata-dev/apache-core-batch-processing-scalable/0

We're working to get the release out and will leave this open until we get it solved.

**Comment by kwmonroe** [comment]
Awesome!  Thanks Rick!
