### ISSUE TITLE
Most of the “Juju” header button is unclickable

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#540]
In a private/incognito window:
1\. Go to any non-app page on jujucharms.com, for example “[How it works](https://jujucharms.com/how-it-works)”, “[JAAS](https://jujucharms.com/jaas)”, or “[Experts](https://jujucharms.com/experts)”.
2\. In the header, click on any part of the “Juju” area that is not the Juju logo itself.

What happens: Nothing.

What should happen: You‘re returned to [jujucharms.com](https://jujucharms.com/).

The logo area is 118×48 pixels:

![jujucharms com-logo-area-outer](https://user-images.githubusercontent.com/19801137/43460665-2ffec352-94c9-11e8-9e07-23054f57b4c1.png)

But the clickable area is only 78×32 pixels:

![jujucharms com-logo-area](https://user-images.githubusercontent.com/19801137/43460671-3a65c0e8-94c9-11e8-933f-ee6fb4557aec.png)

This seems to be _partly_ because the `<a>` element is inside a `<div class="p-navigation__logo">` that has `margin: 0 1rem 0 1.5rem;`. Perhaps the `<a>` element should be outside that `<div>` instead.

**Comment by frankban** [comment]
Thanks for reporting and for suggesting the possible root of the problem!

**Comment by barrymcgee** [comment]
Thanks @matthewpaulthomas - the fix you suggested did indeed do the trick.
