### ISSUE TITLE
/community - Bug on 'Latest from blog' section

### ISSUE THREAD

**Issue by anasereijo** [canonical/jujucharms.com#541]
<img width="1160" alt="screen shot 2018-08-08 at 15 29 54" src="https://user-images.githubusercontent.com/36884067/43843710-116821b0-9b20-11e8-911a-37c154ca067a.png">

**Comment by barrymcgee** [comment]
Thanks @anasereijo - this has been fixed by https://github.com/CanonicalLtd/blues_browser/pull/1815 and will land soon.
