### ISSUE TITLE
Update client logos on 'Users and Contributors' section

### ISSUE THREAD

**Issue by kwm14** [canonical/jujucharms.com#545]
## Enhancement

Currently in the process of updating client logos to use our new alignment template, so they sit on an imaginary baseline which will give logos:

- A comparable visual weight
- Fit in a given height / width
- Reduces elongated or very thin logos to appear a lot smaller

### Logos to update

Ubuntu - https://assets.ubuntu.com/v1/9c911225-2018-logo-ubuntu.svg
Deutsche Telekom - https://assets.ubuntu.com/v1/d199354d-2018-logo-deutsche-telekom.svg
IBM - https://assets.ubuntu.com/v1/9b1fe97b-2018-logo-IBM.svg
Intel - https://assets.ubuntu.com/v1/94ea495b-2018-logo-Intel.svg
Microsoft Azure - https://assets.ubuntu.com/v1/6d027c12-2018-logo-Microsoft-Azure.svg
Cisco - https://assets.ubuntu.com/v1/8a4d26de-2018-logo-cisco.svg
China Telecom - https://assets.ubuntu.com/v1/34a1f30e-2018-logo-china-telecom.svg
NEC - https://assets.ubuntu.com/v1/df2082a4-2018-logo-NEC.svg
HP - https://assets.ubuntu.com/v1/7ccf63c3-2018-logo-hp.svg
Yahoo Japan - https://assets.ubuntu.com/v1/cf17b55e-2018-logo-yahoo-japan.svg
Verizon - https://assets.ubuntu.com/v1/198d7b96-2018-logo-verizon.svg

### Current result
![screen shot 2018-09-03 at 17 36 44](https://user-images.githubusercontent.com/17748020/44996470-ff23d780-af9f-11e8-9bef-97a7949b7831.png)

### Expected result
![screen shot 2018-09-03 at 17 20 37](https://user-images.githubusercontent.com/17748020/44996387-9fc5c780-af9f-11e8-834a-bc57cb37f18b.png)

**Comment by barrymcgee** [comment]
@kwm14 When I update to these new images, due to the Vanilla margin of 1.875rem on each item, this is the result?

<img width="1768" alt="screenshot 2018-10-31 at 10 29 49" src="https://user-images.githubusercontent.com/505570/47782393-09d8bf80-dcf8-11e8-95f0-20c6c9035750.png">
