### ISSUE TITLE
Resources cannot be optional

### ISSUE THREAD

**Issue by ryan-beisner** [canonical/jujucharms.com#546]
A charm needs to be able to define a resource in metadata.yaml as either required or optional.

There are currently two production cases which require this:

 - openstack-dashboard optional theme files
 - vault optional alternate binary package

A user is expected to publish a 0kb resource blob to work around the current design, which is ok (yet awkward) for one-off human charm store interactions.  But is thorny to think about automating that across 40+ charms in a collective product where resource implementation is the exception (optional) rather than the norm.

**Comment by ryan-beisner** [comment]
```
ERROR cannot release charm or bundle: resources are missing from publish request: theme
```

**Comment by ryan-beisner** [comment]
https://bugs.launchpad.net/charm-openstack-dashboard/+bug/1778284

**Comment by hatched** [comment]
@ryan-beisner this is the issue tracker for the jujucharms.com website, did you instead mean to create this issue for the charm tool?

**Comment by ChrisMacNaughton** [comment]
@hatched I suspect that depends on if the charmstore will allow a release without a resource

**Comment by ryan-beisner** [comment]
Moved to https://github.com/juju/charm-tools/issues/439

**Comment by johnsca** [comment]
My understanding is that this is an intentional design decision on the charm store side.  I don't think there's anything that can be changed in the client to change this.

**Comment by johnsca** [comment]
Confirmed.  This is being rejected by the charm store and not the client:

```
[johnsca@murdoch:~/juju/envs/dev] $ charm release --channel=edge cs:~johnsca/test-1 --debug
11:48:58 DEBUG httpbakery logger.go:28 client do PUT https://api.jujucharms.com/charmstore/v5/~johnsca/test-1/publish {
11:48:58 INFO  httpbakery logger.go:33 HTTP response OK (status 400 Bad Request)
11:48:58 DEBUG httpbakery logger.go:28 } -> error <nil>
ERROR cannot release charm or bundle: resources are missing from publish request: test
11:48:58 DEBUG cmd supercommand.go:475 error stack: 
resources are missing from publish request: test
gopkg.in/juju/charmrepo.v4/csclient/csclient.go:1007: 
gopkg.in/juju/charmrepo.v4/csclient/csclient.go:603: 
github.com/juju/charmstore-client/cmd/charm/charmcmd/release.go:111: cannot release charm or bundle
```

**Comment by ryan-beisner** [comment]
@hatched Please re-open the issue for further discussion.  I believe it is valid against the store project.

**Comment by hatched** [comment]
Ahh yes this does look like a response from the charmstore: https://github.com/juju/charmstore
