### ISSUE TITLE
Canonical Kubernetes bundle is “by” someone with “0 bundles”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#547]
1\. Go to [the “The Canonical Distribution Of Kubernetes” page](https://jujucharms.com/canonical-kubernetes/).
2\. Follow [the publisher link](https://jujucharms.com/u/containers).

What happens:
1\. The page says that the bundle is “By [containers](https://jujucharms.com/u/containers)”.
2\. The page says “Containers” — “0 bundles 0 charms”.

![jujucharms com-containers](https://user-images.githubusercontent.com/19801137/45262786-b2178980-b415-11e8-8c8e-51d52988fcbe.png)

What should happen: either
- the bundle is not by “containers”, in which case the page should cite the correct publisher instead; or
- the bundle really is by “containers”, in which case the user page should list the bundle.

(Incidentally, “containers” is a pretty dubious name for a Canonical entity. Why isn’t it “By Canonical”?)

**Comment by hatched** [comment]
Thanks for bringing this up. The issue is actually that the request is timing out and defaulting to a 0/0 response. We're currently investigating this issue.

As far as the name of the bundle author. You're best bet would be to contact the owners of that bundle.

**Comment by matthewpaulthomas** [comment]
The “containers” publisher page now counts “12 bundles 28 charms”, and I’ve reported the publisher name issue separately.

So if the incorrect timeout behavior is either fixed or reported separately, this can be closed.
