### ISSUE TITLE
Bundles page has duelling notifications

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#548]
1\. Go to [the Store page](https://jujucharms.com/store).
2\. Choose “View all the bundles”.

What happens: The page you end up on has two stacked notifications:

![jujucharms com-bundles](https://user-images.githubusercontent.com/19801137/45262875-5948f080-b417-11e8-9e32-ad14097f63df.png)

What should happen: Either zero or one notifications.

Both of them seem to appear every time I go to the page, and neither tell me about something that has happened. This suggests that they should not be notifications at all. Regardless, though, the charms text should not be written as though the site doesn’t know you‘re looking at bundles.

**Comment by barrymcgee** [comment]
Thanks for raising - [fix submitted](https://github.com/CanonicalLtd/blues_browser/pull/1830).
