### ISSUE TITLE
Notification graphics are misaligned

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#549]
1\. Go to any page that has a notification, such as [jujucharms.com/q/?type=bundle](https://jujucharms.com/q/?type=bundle).

What you see:
- The notification has a “?” icon, jammed against the top left corner.
- The text begins with “Information:”, which is redundant with the visual design.
- There’s a close button, which is jammed against the top right corner.

![jujucharms com-bundles](https://user-images.githubusercontent.com/19801137/45262844-c27c3400-b416-11e8-8c9e-816cd2e3da01.png)

What you should see:
- Either the notification doesn’t have an icon, or it’s top-aligned with the text and not touching the side.
- The word “Information:” is not present (or, at most, it’s `alt=` text for the icon).
- Either the notification doesn’t have a close button, or it isn’t jammed against the corner.

**Comment by barrymcgee** [comment]
@matthewpaulthomas Thanks for raising this - [fix submitted](https://github.com/CanonicalLtd/blues_browser/pull/1830).
