### ISSUE TITLE
Old bundle identifiers broken

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#55]
WIth Juju Quickstart 2.0.0 existing command lines that worked with the previous version now fall over

```
⟫ juju-quickstart bundle:~landscape/landscape-dense-maas/landscape-
WARNING:root:this bundle URL is deprecated: please use the new format: u/landscape/landscape-dense-maas-landscape-dense-maas
usage: juju-quickstart [-h] [-e ENV_NAME] [-n BUNDLE_NAME] [-i]
                       [--environments-file ENV_FILE]
                       [--gui-charm-url CHARM_URL] [--no-browser]
                       [--distro-only] [--ppa] [--version] [--debug]
                       [--description] [--upload-tools]
                       [--upload-series UPLOAD_SERIES]
                       [--constraints CONSTRAINTS]
                       [BUNDLE]
juju-quickstart: error: unable to open the bundle: cannot retrieve bundle from remote URL https://api.jujucharms.com/charmstore/v4/~landscape/bundle/landscape-dense-maas-landscape-dense-maas/archive/bundle.yaml: Not Found
```

Whilst I understand that such identifiers are deprecated, my expectation is that they should still work.

I'm also unsure if the new format that quickstart is suggesting is correct, jujucharms.com suggests it's `juju quickstart u/landscape/landscape-dense-maas/8`

**Comment by sparkiegeek** [comment]
If we could have a juju-quickstart invocation which works with both 2.0 and the previous release (1.6?) that would be great.

**Comment by urosj** [comment]
The new format that quickstart shows is correct and you can get the new
bundle format here:

https://api.jujucharms.com/charmstore/v4/~landscape/landscape-dense-maas-8/archive/bundle.yaml

which was derived from the old bundle found here:

https://api.jujucharms.com/charmstore/v4/~landscape/landscape-dense-maas-8/archive/bundles.yaml.orig

I will leave the compatibility part of the answer to quickstart people.

**Comment by frankban** [comment]
The previous "bundle:" is deprecated but still supported, and should work. It does not in this case for an issue while migrating bundles to the new charm store. We are working on fixing this, either by changing the translation algorithm from API v3 to v4 or by changing how the new syntax is inferred in quickstart.
For the time being, the "u/landscape/landscape-dense-maas/8" form seems to work.

**Comment by mitechie** [comment]
The old bundle: format should reach out to the v3 api and still be supported. That will work until we EOL the v3 api at the end of the year. So this is a bug on quickstart and we'll look to move this issue over there for updating. Thanks for reporting this.

**Comment by mitechie** [comment]
Moved to quickstart bug https://bugs.launchpad.net/juju-quickstart/+bug/1429129

Closing this one as there will be no update to jujucharms.com around this issue. It is setup for the new bundle id, format, and quickstart for users.
