### ISSUE TITLE
firefox - search box hidden if the browser window isn't large enough

### ISSUE THREAD

**Issue by sajoupa** [canonical/jujucharms.com#550]
Hi,

I'm giving firefox 1/3rd of my screen width, which should be something like 853 pixels (resolution is QHD - 2560x1440).
In these conditions, the search box never appears, even if I zoom out in the browser.
This does not happen with chromium.

Thanks.

**Comment by barrymcgee** [comment]
@sajoupa Thank you for taking the time to raise this - it is a known issue and a fix has already been submitted and landed which will resolve it. The fix will be deployed in the next release.

Fixed by https://github.com/CanonicalLtd/blues_browser/pull/1826
