### ISSUE TITLE
In search results, no highlight of current site section

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#552]
1\. Go to [jujucharms.com](https://jujucharms.com/).
2\. Click “Store”.
3\. Search for something.

What happens:

1\. No part of the header is highlighted.

2\. “Store” is highlighted.
![juju-store-highlighted](https://user-images.githubusercontent.com/19801137/46338412-08987200-c628-11e8-855a-123a1bca5c07.png)

3\. No part of the header is highlighted.
![juju-store-unhighlighted](https://user-images.githubusercontent.com/19801137/46338411-07ffdb80-c628-11e8-8084-0f0f097583e2.png)

What should happen:
3\. On the search results, “Store” is still highlighted.

**Comment by barrymcgee** [comment]
@matthewpaulthomas Thank you for raising this, fix submitted.
