### ISSUE TITLE
Selecting "Latest version #XXX" results in a 404

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical/jujucharms.com#553]
On the page https://jujucharms.com/u/containers/canal/

Selecting the "Latest version" link at the top of the page goes to https://jujucharms.com/canal/151 which returns a 404.

**Comment by frankban** [comment]
Ok I am able to dupe starting from https://jujucharms.com/u/containers/canal/150
Thanks for reporting, this will be fixed on next release!
