### ISSUE TITLE
Link to documentation should be updated

### ISSUE THREAD

**Issue by pmatulis** [canonical/jujucharms.com#554]
In the site's top header there is a link ("Docs") to the Juju documentation that uses the old URL of `https://jujucharms.com/docs/`. For now, it redirects to the actual URL of `https://docs.jujucharms.com/` but it would be better to correct the actual hyperlink.

**Comment by barrymcgee** [comment]
Thanks for raising this @pmatulis - I did some work earlier on the header nav to update links so I've rolled this change in also.

PR here: https://github.com/CanonicalLtd/blues_browser/pull/1837
