### ISSUE TITLE
participation bit is 1¾ yrs  out of date.

### ISSUE THREAD

**Issue by coverme76** [canonical/jujucharms.com#555]
So I got a tweet about juju-charms and lookin' at the website,

- the [participation bit](https://jujucharms.com/#Join_the_movement) is nearly two years out of date.

I guess I am just reminiscing.

**Comment by barrymcgee** [comment]
@coverme76 Thank you for raising this issue - it was raised previously in #524 and a fix has since been submitted. It will be resolved by the next deploy.
