### ISSUE TITLE
aws-integrator throws error while granting requests:check credentials and debug-log

### ISSUE THREAD

**Issue by TarunKDas2k18** [canonical/jujucharms.com#557]
I am using vagrant and trying to  install  The Canonical Distribution of Kubernetes, i have already connected juju with my aws key and secret key

Below error i am getting in aws-integrator

![image](https://user-images.githubusercontent.com/44246599/47887894-f2d0c500-ddfe-11e8-9805-b8a8902477a3.png)

**Comment by hatched** [comment]
Hi @TarunKDas2k18 this is the issue tracker for the jujucharms.com website. It sounds like you have an issue with a charm or bundle. You'll have better luck reporting it with one of those projects or on the Juju discourse here: https://discourse.jujucharms.com/
