### ISSUE TITLE
Re: Wrong default password have install

### ISSUE THREAD

**Issue by rdwild** [canonical/jujucharms.com#559]
After the install with conjure-up the final page says what the dashboard ip is and the userid and password is admin and openstack.  But the password is not openstack, its a randomly generated password.  This can be gotten br source openrc and then doing an env and finding the password but the right password should be included on the final page of the install.

**Comment by hatched** [comment]
Is this an issue on the documentation pages on jujucharms.com or in output generated by conjure-up? If it's the latter the repository for conjure-up is here: https://github.com/conjure-up/conjure-up
