### ISSUE TITLE
502 error on mysql page

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#56]
this was reported as a broken link on juju/docs (https://github.com/juju/docs/issues/286) but it actually seems to be a server error

https://jujucharms.com/interface-mysql.html

returns a 502 on every machine I have tried so far

**Comment by evilnick** [comment]
Update: it seems there is something wrong with the link after all - sorry, I didn't expect it to return a 502 over a 404 if it couldn't find something

**Comment by mitechie** [comment]
Thanks Nick, definitely glad you found the url issue but you're right we should not be 502'ing to users. Reopning and we'll look into this.

**Comment by mitechie** [comment]
404's properly now.
