### ISSUE TITLE
Non-existent jaas.ai URL returns “Internal Server Error”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#560]
1\. Go to [jaas.ai/404test](https://jaas.ai/404test).

What you see: “Internal Server Error”

What you should see: A “Not Found” page

**Comment by pmahnke** [comment]
can you move this to the jaas.ai repo?

**Comment by anthonydillon** [comment]
https://github.com/canonical-websites/jaas.ai

**Comment by matthewpaulthomas** [comment]
Re-reported as [jaas.ai#15](https://github.com/canonical-websites/jaas.ai/issues/15).
