### ISSUE TITLE
Broken logos on homepage

### ISSUE THREAD

**Issue by squidsoup** [canonical/jujucharms.com#561]
The Ghent and Epam logos appear to be broken on the homepage.

![image](https://user-images.githubusercontent.com/130286/49484872-77e74800-f89d-11e8-90a6-9ba500aaed96.png)

**Comment by barrymcgee** [comment]
@squidsoup Thank you for catching this 👌🏻

**Comment by barrymcgee** [comment]
Fixed by https://github.com/CanonicalLtd/blues_browser/pull/1862
