### ISSUE TITLE
Cycling progress bar is deceptive

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical/jujucharms.com#562]
1\. On jujucharms.com, click [“Try Big Data Anssr Engine”](https://jujucharms.com/new/?dd=~spiculecharms/bundle/anssr-data-engine).
2\. Watch the following page.

What happens:
- A progress bar quickly fills up. Ah, great, this is going to be ready in a moment.
- The progress bar detaches from the beginning of its trough, and empties. What?
- The progress bar fills up again from the beginning. Now I don’t trust it any more.
- The progress bar detaches again.
- The progress bar fills up again from the beginning. Etc.

What should happen: [A progress bar always fills, for a successful task, exactly once.](https://docs.google.com/document/d/1UP7pD-jtX_mIn7Mw3YBS2SbKgDcNnLoMlvnAhzArfko/edit#heading=h.7srvw2rm1s1p)

A simple first iteration would be to allocate 1/7 of the progress bar to each of the currently labelled subtasks (“Requesting the code”, “Reading the configuration”, “Connecting to the backend [sic]”, “Reticulating splines” (mhm), “Establishing API connections”, “Verifying identity”, and “Checking controller information”).

A next step could be to measure what proportion of time each of those subtasks take on average, and adjust the proportions to match. Separately, perhaps one or more of the subtasks can have more granular updates.

**Comment by hatched** [comment]
In a future release of the GUI the architecture has changed and this progress bar will be removed entirely. Its original goal was simply to indicate that 'something' was happening.
