### ISSUE TITLE
Page missing from navigation

### ISSUE THREAD

**Issue by jillr** [canonical/jujucharms.com#57]
Afaict https://jujucharms.com/docs/authors-interfaces is not linked from anywhere in nav or related pages.  Content of this doc is significantly more detailed for writing interfaces than https://jujucharms.com/docs/authors-charm-interfaces however.

**Comment by mitechie** [comment]
Thanks for this report @jillr. I've copied it over to the docs themselves so the folks working on those can better provide feedback and get an update in. Once updates land in the docs it'll be auto generated/updated on jujucharms.com. 

https://github.com/juju/docs/issues/289
