### ISSUE TITLE
jujucharms.com/community page has "Get in touch" link that emails jorge

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#571]
We should send this to discourse imo. The events section is old and should just be removed. I don't know if we have the Juju partner programs any more. That should probably go. Maybe @urosj would like something mentioning becoming a Juju expert or something there?

https://jujucharms.com/community/charmers should also be gone as a whole I think and then we'd redirect the link to the charmers page from the community page to discourse as well?

**Comment by hatched** [comment]
This has now been resolved and will be fixed in an upcoming release. Thanks for reporting!
