### ISSUE TITLE
AWS Credentials help link broken

### ISSUE THREAD

**Issue by doismellburning** [canonical/jujucharms.com#577]
Attempting to deploy my new model with JAAS to AWS at https://jujucharms.com/new/i/inspector/<id>$/deploy I am offered links to

> Read more about credentials in general or setting up AWS credentials.

`setting up AWS credentials` links to https://docs.jujucharms.com/help-aws which 404s

I suspect it should link to https://docs.jujucharms.com/aws-cloud ?

**Comment by clagom** [comment]
@hatched we are not able to move this issue; this is planned for this iteration, can you add milestone, and change the pipeline accordingly please?
