### ISSUE TITLE
search filtering

### ISSUE THREAD

**Issue by celebdor** [canonical/jujucharms.com#59]
Adding filters to the search bar (in the same fashion as google has) would be very handy for the target audience of admins and developers. For example:

```
apache author:charmers series:trusty
```

**Comment by mitechie** [comment]
Thanks for this. We're working with the design team to implement a new search results UX that includes some basic filters for the next release. We should have that right at the end of the month. I'd love to get your feedback once that goes live.

**Comment by mitechie** [comment]
So our new filtering in the new search design doesn't get you what you really want. We've got some search updates scheduled for the back end that we'll look to take this into account for.

**Comment by urosj** [comment]
We've made a decision long time ago that we're not going to support complex search for now. Although it is tempting to add those filters, for now, we would rather focus on curated experience. There will be time for a way to implement a search that is being proposed in the future.
