### ISSUE TITLE
Used in "N" solutions not having a link to "show all"

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#6]
For example in https://jujucharms.com/memcached/precise/12

There should be 4 solutions, but only 2 are shown (and without a link to "show all solutions"). And by going to:

https://jujucharms.com/related/memcached/precise/12

all four are returned.

**Comment by mitechie** [comment]
Thanks uros, code landed today from @fabricematrat around this feature and will be in the next release.

**Comment by fabricematrat** [comment]
Yes for the features but the bug is valid as there should be 4 shown in the https://jujucharms.com/memcached/precise/12 page.

**Comment by jcsackett** [comment]
The fix has landed in develop.
