### ISSUE TITLE
Foldouts not rendering in docs

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#63]
The <details> tags seem to have lost their styles with the last update, e.g. check the https://jujucharms.com/docs/1.20/commands
page - each command should be a foldout. The HTML is correct, the style seems to have been overrriden.

**Comment by bac** [comment]
The page looks good to me in Safari and Chrome on OS X.

**Comment by bac** [comment]
Broken in FF on OS X

**Comment by anthonydillon** [comment]
I'm not sure what is the desired interaction here. I see the page as http://awesomescreenshot.com/0f34phic3d in both Chrome and FF on Ubuntu.

**Comment by mitechie** [comment]
@anthonydillon it might be working in ubuntu but @bac noted an issue with FF in OSX. Can you replicate that issue?

**Comment by anthonydillon** [comment]
@bac @mitechie Tested on Yosemite FF v.23 and see the same result.

**Comment by anthonydillon** [comment]
Also tryed Yosemite FF v.22 - v.10 and all seem ok. Which part of the page should fold out?

**Comment by bac** [comment]
@anthonydillon This is curious.  I now see the problem on Safari with production.

On https://jujucharms.com/docs/1.20/commands each of those bullet points for the commands should be a triangular twisty foldout, not bullets.  I now see this wrong behavior across browsers.

**Comment by evilnick** [comment]
@mitechie @bac @anthonydillon I'm really sorry guys - when I filed this I didn't realise that the browser was serving up a previous version of the docs. However, the problem is there in 

https://jujucharms.com/docs/latest/commands  in FF and likely some other places

I also know what the problem likely is. The source uses the `<details>` tag, which is HTML5. I seem to remember when we introduced these to docs, we had a CSS shim which replicated the behaviour properly in browsers which weren't so good at HTML5 - since we don't use any of that old css any more, that behaviour isn't being patched

**Comment by bac** [comment]
That was it @evilnick.  I can confirm https://jujucharms.com/docs/latest/commands works in Safari and fails in FF on OS X.

**Comment by anthonydillon** [comment]
Ah that's the stuff. Thanks guys.

**Comment by anthonydillon** [comment]
Unfortunately the details tag is not supported in FF and IE: http://caniuse.com/#feat=details.

This is purely a browser support issue.

**Comment by anthonydillon** [comment]
@mitechie @bac Can this be considered closed?

**Comment by mitechie** [comment]
@anthonydillon I was hoping we'd just add a shim in but looking at the shims out there for this it seems like it's broken and really unsupported right now:

https://mathiasbynens.be/notes/html5-details-jquery

Going down the comments in the last couple of years it's not promising.

On top of that, it's a jquery add-on and I'd rather not load jquery just for certain docs. @evilnick what are your thoughts around the details tag? Can we move to something that's cross browser supported?

**Comment by anthonydillon** [comment]
@mitechie I thought about recreating it in js for the docs but in that case we might as well use a bespoke js solution then the details tag.

**Comment by evilnick** [comment]
Well, I guess since the "broken" behaviour just seems to list out all the information anyway, nobody is missing out, so I wouldn't say this was a super high priority to fix.

We didn't use a jquery-based shim before, we used a trick similar to this (but not this exact one I don't think) http://demosthenes.info/blog/680/Feature-Detection-and-Styling-For-The-HTML5-details-Element
which does most of the work in CSS. I liked this because it sort of future-proofed things a bit - when browsers support `<details>` it doesn't get used at all. So, it doesn't seem like it is that difficult to do.

I do think the docs benefit greatly from being able to do this - the command reference and release notes for example are only made usable by this functionality, and whilst we could just come up with something else, I'd rather support half a standard than no standard at all.

**Comment by mitechie** [comment]
@evilnick thanks for the link, we'll look into it. I agree getting a shim in place would be nice, I just wasn't able to find one initially that wasn't jquery based looking at http://html5please.com/#polyfill

**Comment by anthonydillon** [comment]
@mitechie both suggested shims by html5please introduce jQuery. I don't like the idea of adding so much for just one purpose. What you think?

**Comment by fabricematrat** [comment]
@anthonydillon && @mitechie what about that one : https://github.com/chemerisuk/better-details-polyfill
?

**Comment by anthonydillon** [comment]
Thank @fabricematrat that project uses bower and I don't think we want bower as a dependency?

**Comment by fabricematrat** [comment]
@anthonydillon you probably don't need bower, you could grab:
https://github.com/chemerisuk/better-dom/blob/master/dist/better-dom.js
https://github.com/chemerisuk/better-details-polyfill/blob/master/dist/better-details-polyfill.js
package them in YUI and load them at the domready event, that would work I think.

**Comment by anthonydillon** [comment]
A fix has been committed and will live with the next release of the site.

**Comment by evilnick** [comment]
hurrah
