### ISSUE TITLE
Release notes page missing in docs

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#64]
https://jujucharms.com/docs/1.20/reference-release-notes

seems to have disappeared

**Comment by mitechie** [comment]
Note that it comes up in a search so the page is found/loaded into elasticsearch but then when clicking it's not routed for some reason.

**Comment by fabricematrat** [comment]
This bug is due to the fact we load the html in a jinja2 template.
{{ is then interpreted by jinja2.
So a quick fix in https://github.com/juju/docs/blob/master/src/en/reference-release-notes.md would be to add a space between {{ like { {.

**Comment by evilnick** [comment]
Well, i'm sure I can search and replace those, but I can't guarantee it won't happen again someplace else, '{' are fairly common.

moving forward, can we use the templates and tools in the docs repository?

**Comment by fabricematrat** [comment]
Also Fixed with https://github.com/juju/docs/pull/307 and https://github.com/juju/docs/pull/306
