### ISSUE TITLE
bundle visualization scaling issues in Firefox

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#65]

**Comment by anthonydillon** [comment]
This is caused by the transform="scale(scale(%f))" on the SVG element. This attribute is not supported in Chrome but is supported in FF [1] therefore scaling the bundle visualisation. 

The SVG are displayed correctly when removing this attribute.

[1] http://caniuse.com/#feat=svg-html

**Comment by anthonydillon** [comment]
Issue reported: https://github.com/juju/jujusvg/issues/18

**Comment by mitechie** [comment]
Closing as the issue is in the generation of the svgs.
