### ISSUE TITLE
Redirect /<charm-name> to search if no Recommended result

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#66]
Since you can now go to a Recommended charm directly via the charm name (e.g., https://jujucharms.com/hdp-hadoop), it would be nice if using the name of a non-recommended charm would redirect to the search results page instead of just returning a "not found" page.

**Comment by mitechie** [comment]
Hmm, interesting. At first I thought this would be hard to do as we have a number of root level urls, but if we get a 404 on an item, we already know those urls didn't match. 

So what we could do is:

If the charmstore api returns a 404 for a short url, redirect to a search with a query param that would then pick up and show something in the heading like:

"We could not find XXXXX but maybe what you're looking for is in here?" and then show the search results list.
