### ISSUE TITLE
Juju doc URLs should default to `latest`

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#69]
When copying and pasting the version of the docs is in the URL, we'd like it if /latest/ where the default URL instead of the version.

**Comment by evilnick** [comment]
What is currently 'latest' should not be the default. 'latest' currently maps to the master branch of the docs

though, having a /latest/ url which _does_ point to the latest numbered version is a great idea. I would prefer it if the master version of docs mapped to a url of '/dev/' or something similar.

so:

jujucharms.com/docs/dev/       --->  master
jujucharms.com/docs/latest/    --->  1.21
jujucharms.com/docs/1.21/     --->  1.21
...

**Comment by kadams54** [comment]
"latest" and "stable" are conventions shared with readthedocs.org. "stable" points to the latest version, while "latest" points to the dev branch (i.e., master).

jujucharms.com/docs/latest/ --> master
jujucharms.com/docs/stable/ --> 1.21
jujucharms.com/docs/1.21/ --> 1.21

**Comment by evilnick** [comment]
well, it doesn't strike me as a particularly useful convention, I think 'latest' in that case is very ambiguous.  i think 'beta', 'dev' or 'testing' or even 'unstable' are much clearer about what you are actually getting.

Stable makes sense though. Though I have noticed now you mention it that stable actually points to 1.20

**Comment by kadams54** [comment]
Stable pointing to 1.20 is a bug that has been fixed but not yet released. It will be corrected shortly.
