### ISSUE TITLE
Related bundles to a charm are not sorted properly when "show all solutions" is used. 

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#7]
Besides duplication of results, we need to sort prmulgated at the top: 
https://jujucharms.com/related/memcached/precise/12

This will be fixed with the new promulgation data model. Opening this not to forget to fix /meta/bundles-containing .

**Comment by mitechie** [comment]
This url actually doesn't work currently. Making this bug higher to look into what it was and how it got broken.

**Comment by huwshimi** [comment]
The url issue is that /related/ is now /solutions/ so the above url is now https://jujucharms.com/solutions/memcached/precise/12/

**Comment by huwshimi** [comment]
If you visit https://jujucharms.com/memcached/precise/12/ and click "See more" you can see that these urls have been updated correctly.
