### ISSUE TITLE
Docs graphics should be in the same directory

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#73]
Now we have versions, this is the first time I have noticed that the images aren't co-located as per
https://docs.google.com/a/canonical.com/document/d/15Rw9pEpGs05cfDzLpnx5PUei8MiBCn9T7b9oD6V_Bng

I don't really mind what structure you move things to, and I understand that we may need to update all the graphic links on current docs, but we need to have all the graphics in one place, otherwise keeping different versions of the docs becomes 3x more difficult than it needs to be. The master branch should be the only one with relevant images in.

**Comment by frankban** [comment]
This seems to be solved in docs.
