### ISSUE TITLE
openstack topic page

### ISSUE THREAD

**Issue by urosj** [canonical/jujucharms.com#74]
@anthonydillon, @Lucapaulina 

"This solution includes compute, networking, block storage (Cinder and
Ceph), Opject Storage (Ceph) identity and image management. You will
only need 4 physical machines to deploy it, and you can scale it out
by adding more containers on the same machines."

Should be - ->

"This solution includes compute, networking, block storage (Cinder and
Ceph), object storage (Ceph), identity, dashboard and image
management. You will only need 4 physical machines to deploy it, and
you can scale it out by adding more physical machines."

**Comment by mitechie** [comment]
Closing for the other one on the board and our folks will update it as part of preparing for release as I'm not sure if the EU folks will be around enough to get it landed.
