### ISSUE TITLE
stale bundles still showing up in search

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#76]
We have a few big data bundles that were created based on multiple deployment profiles in bundles.yaml.  We have since been educated that the yaml should only specify a single profile, and made the appropriate change about a week ago [1]. However, I still see these when searching for apache-hadoop bundles:

https://jujucharms.com/q/apache-core-batch-processing*

The errant bundles are:
- [apache-core-batch-processing-single-master](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-single-master/)
- [apache-core-batch-processing-single-node](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-single-node/)
- [apache-core-batch-processing-scalable](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-scalable/)

Would you please delete these 3 bundles? These have all been superceeded by the one true [apache-core-batch-processing](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing/) bundle, which only has 1 deployment profile in bundles.yaml and is the only one being maintained.

Thanks!
-Kevin

1 - http://bazaar.launchpad.net/~bigdata-dev/charms/bundles/apache-core-batch-processing/trunk/revision/2#bundles.yaml

**Comment by mitechie** [comment]
Thanks, we'll work to remove those from the charmstore. I'll update once they've been removed.

**Comment by urosj** [comment]
There's a policy of not removing content from charm store because we don't
know if we're breaking any deployment scripts doing that. What we can do
though is this:
- suggest to update the readme files for the listed bundles with a notice
  of them being deprecated and superceeded with a new bundle, also providing
  a link to that
- we'll monitor if there will be any access to the listed bundles in the
  future. If it appears that they are "dead", we can then maybe agree to
  remove them

How does that sound?

**Comment by kwmonroe** [comment]
I don't think updating the readmes is an option. The 3 superseded bundles mentioned above don't have individual backing repos, thus there are no readmes to change.  What you're seeing on those 3 landing pages is a shadow of what used to be. Take the [apache-core-batch-processing-single-node](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-single-node/) bundle for example.  Click the "View code" link on that page and you'll see it's not actually pointing to a _single-node_ source repo, but rather the [repo](http://bazaar.launchpad.net/~bigdata-dev/charms/bundles/apache-core-batch-processing/trunk/files) for the one true [apache-core-batch-processing](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing/) bundle.

I believe this came about because of some hackery to make different deployment profiles in a single bundles.yaml appear as individual bundles.  They all backed to the same source repo.  My problem now is that these faux bundles are no longer being updated to reflect changes in the real bundle (ie: the landing pages are stale).

I don't mind your monitoring suggestion -- if no deployments in the next week/month/whatever, delete them.  Or perhaps just a redirect where anyone accessing the [single-master](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-single-master/), [single-node](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-single-node/), or [scalable](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing-scalable/) landing pages gets redirected to [apache-core-batch-processing](https://jujucharms.com/u/bigdata-dev/apache-core-batch-processing/). Or just delete them and send any complaints my way ;)

I recognize that we created this problem by having multiple profiles in a single bundles.yaml, so whatever you can do to help us steer folks away from these faux bundles will be much appreciated!

**Comment by urosj** [comment]
We'll do our best to help. This was also a good use case, which we should
handle batter in the future. Thanks.

**Comment by mitechie** [comment]
These are all removed now. Thanks for your patience.
