### ISSUE TITLE
add the openstack topic page to the /solutions heading

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#77]
We've added a /openstack topic page but it's not linked or added to the /solutions page yet.

@anthonydillon do you have any designs or pre-work on this?

**Comment by anthonydillon** [comment]
I do have a design for the new solutions header.

https://docs.google.com/a/canonical.com/file/d/0B2sqJRO7vy3ZN3RCVWxCbmRBRGtPMWlMNWc0aWNYY3dnS3V3/edit?usp=docslist_api

I was waiting for a confirmed path for the openstack page before landing
this update but anyone can pick this up as I will be away until Tuesday.
