### ISSUE TITLE
Code browser doesn't follow symlinks in a charm

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#78]
In jujucharms.com/mysql, click on ha_relations.py, it does the right thing: https://api.jujucharms.com/charmstore/v4/trusty/mysql-24/archive/hooks/ha_relations.py

Click on ha_relation-joined, which is a symlink and you get this, which isn't useful: https://api.jujucharms.com/charmstore/v4/trusty/mysql-24/archive/hooks/ha-relation-joined

**Comment by mitechie** [comment]
Thanks for the report. This will require some love as the charmstore isn't tracking where the symlink goes to at the moment and exposing that over the API. We'll investigate how to make this process work out.

**Comment by frankban** [comment]
Moved to https://github.com/juju/charmstore/issues/621
