### ISSUE TITLE
Relations list sidebar text is confusing

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#79]
http://jujucharms.com/mysql

Feedback from sabdfl, the sidebar text is confusing: "Connects from" and "Connects to" doesn't really explain what's going on. For example, the top one in the top box "ceph: ceph-client" doesn't really explain what happens here. Does ceph require mysql? Or the other way around? What's the order?

Also both sets of mysql (precise and trusty) are listed in the icons, adding to the duplication and noise.

**Comment by huwshimi** [comment]
The duplication of series has now been fixed (not yet released).
