### ISSUE TITLE
Features page command line errors

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#8]
On https://jujucharms.com/about/features, the command line for "Provision your machines and control unit placement" is missing the leading `juju`, it currently reads `add-unit mysql --to lxc:4` but should be `juju add-unit mysql --to lxc:4`

**Comment by sparkiegeek** [comment]
Additionally the Scale out example is also wrong. It currently reads `juju add-unit rabbitmq-server -5` but is missing the `n` and should be `juju add-unit rabbitmq-server -n 5`

**Comment by mitechie** [comment]
Thanks @sparkiegeek for the report. We'll get that updated!
