### ISSUE TITLE
Typos on OpenStack page

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#80]
Under the "Want to make things even easier?" heading the text currently reads:
"Why not try Canonical’s OpenStack Distribution tool — the fastest and easient wat to build and manage an OpenStack cloud"

It should say:

"Why not try Canonical's OpenStack Autopilot - the fastest and easiest way to build and manage an OpenStack cloud"

**Comment by mitechie** [comment]
typo under Landscape:                                                                                       

```
"Monitor, manager and upgrade"                                                                                             
(should be "manage")                                                                                                       
```

**Comment by Lucapaulina** [comment]
New copy for the Autopilot section:

"Why not try Canonical's OpenStack Autopilot – It allows you to quickly deploy a tried and tested distribution of OpenStack on your hardware using your configuration choices, such as Swift or Ceph."

As seen on #81
