### ISSUE TITLE
OpenStack page doesn't mention Swift

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#81]
Whilst Ceph is the preferred storage mechanism, I think we should also mention Swift as an option at least.

Perhaps it could be incorporated in the section about Landscape Autopilot, along the lines  of "want Swift instead of Ceph, use the Autopilot"

**Comment by mitechie** [comment]
Can you help work with anyone from your team on more fleshed out copy changes for this please? Is there someone that works on your docs/etc that could be drawn in to help?

**Comment by Lucapaulina** [comment]
New copy for the Autopilot section:

Why not try Canonical's OpenStack Autopilot – It allows you to quickly deploy a tried and tested distribution of OpenStack on your hardware using your configuration choices, such as Swift or Ceph.

Added to #80
