### ISSUE TITLE
switching docs versions assume all pages exist on all versions

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#83]
E.g., go to https://jujucharms.com/docs/stable/config-general/
Switch versions to 1.20, and you get a 404

Would be kinder to fall back to a default page, e.g. getting started

**Comment by mitechie** [comment]
Thanks @evilnick good call.

**Comment by kadams54** [comment]
I think a 404 is still the correct response here, as the page being requested does not exist. We need to serve up the correct HTTP response code for crawlers. That said, I think a good first step would be a custom 404 for docs that would provide users with search, links to the default page, etc. A smarter version switcher that would only display links if the doc exists in those versions is one option for a subsequent follow-up enhancement.

**Comment by evilnick** [comment]
If we still need a 404 then so be it.

I think the issue is, as someone browsing the docs, I click on a version and suddenly I am on a 404 page with no navigation to take me to the version of docs I want to see. So how do I get to 1.20 from the page above? I have to guess a page that will be in 1.20, go to it and switch versions from there.

I think you are right, a smarter version switcher is the best answer

**Comment by mitechie** [comment]
we can do a custom docs 404 that's nice but sends the correct status code and the like. They key thing is that taking the user from one page to another when they're not expecting that change is generally bad form. We want to be up front with the user that what they asked for was not found. We'll work on a pretty way to doing that that doesn't break the docs browsing experience horribly.
