### ISSUE TITLE
revamp community pages on jujucharms.com

### ISSUE THREAD

**Issue by Lucapaulina** [canonical/jujucharms.com#84]
@marcoceppi is this page still needed? https://jujucharms.com/community/charmers

**Comment by marcoceppi** [comment]
Well, it's nice to have but the content on it may need to be curated as there is a bit of overlap between this page and the one in the docs @castrojo thoughts?

**Comment by arosales** [comment]
This is a critical page for our community. @castrojo is currently working with design to fold this into the jujucharms.com/community page.

**Comment by castrojo** [comment]
Here's the current spec/web design submission: https://docs.google.com/a/canonical.com/document/d/1EKsajcvH2G7uTCIBVpjRHgIdD8XfEXiBR8nqLF77p_4/edit?usp=sharing
