### ISSUE TITLE
Favicon on jujucharms.com has ugly white border

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#85]
The favicon for jujucharms.com looks bad, this was a recent (a week or two?) regression.

![jujucharms com-favicon](https://cloud.githubusercontent.com/assets/246192/7119665/96decbf8-e207-11e4-8217-d5780c870676.png)

**Comment by anthonydillon** [comment]
Thanks @sparkiegeek. A fix has landed and will be live in the next release.
