### ISSUE TITLE
Bundle name overlaps icons for large bundles

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#87]
In https://jujucharms.com/landscape-client-11/trusty/#related the name of the bundle sits "underneath" the large number (40?) of charm icons

**Comment by Lucapaulina** [comment]
I can't see anything on that page, could you maybe screenshot the bit which
looks wrong?

**Comment by sparkiegeek** [comment]
http://imgur.com/3oammFC

**Comment by Lucapaulina** [comment]
Ah, yeah. Thanks for the image Adam.
