### ISSUE TITLE
Documentation is confusing for Juju Charm Actions 

### ISSUE THREAD

**Issue by benileo** [canonical/jujucharms.com#88]
The example schema for a Juju Action specifies that the actions directory should contain the 2 executables (report and run). 

Yet the schema specified below specifies that the name of the script should be "snapshot." 

As well as the example command provided:

juju action do mysql/0 snapshot filename=out.tar.gz compression.type=gzip 

Example Schema

Charm dir
├── actions
│   ├── report  <--------------------------------- Should this be snapshot ????
│   └── run
├── actions.yaml
...

actions.yaml example
# actions.yaml

report:
snapshot: 
  description: Take a snapshot of the database.
  params:
    filename: 
      type: string
      description: The name of the snapshot file.
    compression:
      type: object
      description: The type of compression to use.
      properties:
        kind:
          type: string
          enum: [gzip, bzip2, xz]
        quality:
          description: Compression quality
          type: integer
          minimum: 0
          maximum: 9
  required: [filename]
  additionalProperties: false

**Comment by benileo** [comment]
https://jujucharms.com/docs/1.20/authors-charm-actions

About 1/3 of the way down the page.

**Comment by mitechie** [comment]
Thank you for the report. I've migrated this issue to the docs project for them to peek at. You can follow it at:

https://github.com/juju/docs/issues/378

Closing this one so that the other is the official place to track the work.

**Comment by benileo** [comment]
Great, Thanks.
