### ISSUE TITLE
OpenStack page update for new landscape-client charm

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#89]
https://jujucharms.com/openstack talks about, and links to https://jujucharms.com/landscape-client/trusty/11 which is a charm with an old icon.

It should link to https://jujucharms.com/landscape-client/trusty/12 (or better, just https://jujucharms.com/landscape-client/trusty/ so that it's always "latest") and use the newer icon: https://api.jujucharms.com/charmstore/v4/trusty/landscape-client-12/icon.svg

**Comment by mitechie** [comment]
Opening, it's fix-committed but will not close the bug until release when it's noted to be fix-released.

**Comment by sparkiegeek** [comment]
Hmm. https://jujucharms.com/static/img/topics/openstack-landscape-charm.png is still old icon
