### ISSUE TITLE
Text overflow can lead to uneven sizes for topic images

### ISSUE THREAD

**Issue by kadams54** [canonical/jujucharms.com#90]
See ![this screenshot](https://cloud.githubusercontent.com/assets/378036/7280905/16f404f0-e8f4-11e4-9436-31e2fecc5ba5.png) - it looks like the text is slightly too long in the OpenStack solutions image, leading to the box being slightly taller than the other two.

**Comment by Lucapaulina** [comment]
@spencerbygraves do you have an ideas on how we can fix this?
