### ISSUE TITLE
Feature request: Visual indicator for connection points

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#92]
In the preview of bundles, it would be very useful to be able to visually see the connection points, i.e., where the bundle has relations that you can connect to.  For example, on:

![bundle-gui](https://cloud.githubusercontent.com/assets/406082/7390454/c63657b8-ee78-11e4-9a4b-c48243832af3.png)

which is the Apache Hadoop core bundle in the GUI, the unconnected relation on the plugin service gives a powerful at-a-glance indication of where additional services, such as Apache Pig, can be connected.

**Comment by arosales** [comment]
+1 this would be a great feature to have in the GUI as we work to grow out the ecosystem and build the center of gravitates. It is very useful to an perspective user to easily envision how to plug into this mode.

-Antonio

**Comment by mitechie** [comment]
I've copied this to the jujusvg library which generates the images. 

https://github.com/juju/jujusvg/issues/31
