### ISSUE TITLE
Search Improvements - promulgated, latest series, difficult to pick out

### ISSUE THREAD

**Issue by dpb1** [canonical/jujucharms.com#93]
Take this search as an example:

```
https://jujucharms.com/q/landscape
```

I would like (as a user searching for things to deploy) to show just 5 things that match by charm/bundle name (obviously, some of things match by user, description, etc and I understand it would show those too).  At least, those I would like to show up first.
- landscape server (trusty)
- landscape client (trusty)
- landscape scalable
- landscape dense maas
- landscape dense

My suggestions:
- Make everything non-promulgated require a click through link that fills in.
- Fold multiple series of the same promulgated charm underneath the same search entry, and just show the latest release.

**Comment by mitechie** [comment]
Thank you for the feedback. Your suggestions are valid.

The second one is in review and should land sometime today and will be in the next release next week.

The first suggestion is something that UX is aware of and working on new designs for that handle the grouping of promulgated and non promulgated.

**Comment by mitechie** [comment]
copying in @Lucapaulina and @spencerbygraves

**Comment by Lucapaulina** [comment]
A new search design has been implemented which addresses these issues. Thanks for the feedback!
