### ISSUE TITLE
Copy updates required

### ISSUE THREAD

**Issue by tcallway** [canonical/jujucharms.com#95]
Asterisk used to highlight necessary copy changes...

https://jujucharms.com
_Model, build_ and scale your environments on any cloud.

https://jujucharms.com/about
Juju is the best solution to _model_ your services in the cloud. You can use it through a GUI or from the command line, scale your services and easily move your environment between clouds.

_https://jujucharms.com/about/features_
Juju’s powerful GUI and command-line interface make it easy to _model,_ deploy, manage, monitor and scale out your services to any public or private cloud.

Title: Configure and connect your services >> Model and connect your services

**Comment by mitechie** [comment]
Thanks, we'll get these into the next release.

**Comment by Lucapaulina** [comment]
I saw these copy changes come in last week or so and I thought they were ok, but after using it for a while I think "Model" and "Build" are really close in meaning, is "model" a word usually associated with configuring services? What are the differences between them?

**Comment by mitechie** [comment]
I think the wording was to bring in line the website with our marketing messaging. Perhaps @tcallway can speak a bit more specifically to the driver to the changes and discuss it with us.
