### ISSUE TITLE
https://jujucharms.com/docs 404s, should redirect to latest stable docs

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#96]
https://jujucharms.com/docs 404s. Suggest to have it redirect to something like:
  https://jujucharms.com/docs/stable/getting-started

-thanks,
Antonio

**Comment by huwshimi** [comment]
Thanks @arosales. Looks like the issue here is that we only redirect when there is a trailing slash (/docs/ works but /docs doesn't). We'll have to fix our routes to make sure both work.

**Comment by mitechie** [comment]
This is due to a fix at the last minute made to fix one route that seems to have broken others. We'll get a fix out asap.

**Comment by mitechie** [comment]
jujucharms.com/docs now redirect properly again.
