### ISSUE TITLE
User / profile pages are not visible unless logged in

### ISSUE THREAD

**Issue by johnsca** [canonical/jujucharms.com#97]
Viewing a user page, such as https://jujucharms.com/u/bigdata-dev/, when not authenticated returns a 404.  When logged in, it returns the new profile page for that user, with a list of that users bundles & charms.

I don't see any reason to restrict profile page views to authenticated users.

**Comment by mitechie** [comment]
Thanks this is a url issue from the last release and a copy of https://github.com/CanonicalLtd/jujucharms.com/issues/96 which is fix omitted and we're working to get a release update out today.

**Comment by mitechie** [comment]
my apologies, I misread this bug and it's not what I thought it was. Opening back up and looking into it.
